-- ============================================================================
-- ARMEE PHASE 3 : MOTEUR PHYSIQUE DE COMBAT
-- Trace des migrations appliquees via MCP. Ce fichier documente, il ne s'execute pas.
-- ============================================================================

-- ============================================================================
-- LOT 1 : FERMETURE DU CANAL DE DEGATS `impacts_indices_attente` (19 septembre 2026)
-- Applique sous `impacts_indices_attente_fermeture`.
--
-- La table etait en RLS mais portait une politique unique `allow_all` en ALL, USING true /
-- WITH CHECK true, et anon comme authenticated avaient INSERT/UPDATE/SELECT. N'importe qui
-- pouvait deposer un hp_set arbitraire sur n'importe quelle victime -- sans jet, sans arme, sans
-- PA, sans etre present, sans meme etre authentifie.
--
-- INVENTAIRE EXHAUSTIF, fait AVANT de fermer :
--   hp_set              x4 : Neutraliser reussi, Neutraliser echec partiel, explosion, mission
--                            militaire `assassiner`
--   poison_start        x1 : empoisonnement
--   moral_carte_postale x1 : bonus de lecture d'une carte postale
--   pop / inf / dis     x0 : consommes par le client, plus AUCUN producteur -- vestiges
--   consommateur unique : traiterImpactsEnAttente (plateau-communication.js)
--
-- DECOUVERTE AU PASSAGE : le producteur d'empoisonnement envoie `poisonType` et `statsTouchees`,
-- DEUX COLONNES QUI N'EXISTENT PAS, et omet `delta` qui est NOT NULL sans defaut. Cet INSERT a
-- donc toujours ete rejete par PostgREST, silencieusement -- l'empoisonnement n'a jamais atteint
-- sa victime. La RPC refuse desormais VISIBLEMENT (raison `schema_incomplet`) au lieu d'echouer
-- sans bruit. Le reparer demande un schema, pas un correctif de canal : lot a part.
--
-- CE QUE CETTE FERMETURE FAIT ET NE FAIT PAS : elle rend le CANAL atteste (identite, existence de
-- la victime, et CO-PRESENCE REELLE pour tout degat physique). Elle ne rend pas le JET de
-- Neutraliser serveur -- dette anterieure et distincte. Le moteur militaire, lui, n'emprunte pas
-- ce canal : il travaille en PA canoniques.
--
-- Banc 10/10 : anon et authenticated refuses en INSERT direct ; RPC a distance refusee
-- (pas_au_meme_endroit) ; co-presence acceptee ; rejeu du meme id sans second effet ; poison
-- refuse visiblement ; la victime lit sa file, un tiers ne la voit pas ; un tiers ne peut pas
-- marquer traite, la victime oui.

-- ============================================================================
-- LOT 2 : MOTEUR PHYSIQUE DE COMBAT V1 (19 septembre 2026)
-- Applique sous : combat_schema_etat_bataille, combat_primitives_jet,
-- combat_combattants_et_gilet, combat_moteur_round, combat_actions_application_rapport,
-- combat_engagement_et_decisions, combat_decisions_repli_doctrine, combat_rpc_client,
-- combat_poursuivre_participant.
--
-- FORMULE, a la lettre du GD et non ajustee :
--   Tir  : T = 20 + Tir*0.7              - PER_cible*2
--   CaC  : T = 20 + Combat_rapproche*0.7 - DUP_cible*2
--   T = clamp(round(...), 10, 85)   -- arrondi UNE fois, a la fin, puis clamp
--   jet uniforme 1..100
--   echec critique 96-100 TESTE EN PREMIER ; puis jet<=T/4 critique (-3 PA),
--   <=3T/4 reussite (-2), <=T partielle (-1), sinon echec. Seuils NON arrondis.
-- Verifie : T(0,10)=10, T(100,10)=70, T(100,0)=85, T(50,25)=10, T(50,3)=49 ;
-- a T=85 les bascules tombent exactement sur 21/22, 63/64, 85/86, et 96 est echec critique.
--
-- AUCUN PV. Les degats sont en PA canoniques. A 0 PA : PNJ MORT (supprime reellement de la
-- section, contingent diminue definitivement) ; PJ NEUTRALISE (jamais mort) et transfere a
-- l'Infirmerie de sa propre caserne (ville 'caserne', meme zone dans les quatre empires).
--
-- RIEN N'EST DUPLIQUE : PA, position, inventaire, accessoires et appartenance au groupe restent
-- lus et ecrits a leur source canonique. batailles_engagements ne dit QUE qui participe et qui
-- est sorti.
--
-- CONFIDENTIALITE STRUCTURELLE : deux lignes de rapport par round, une par camp, et chaque camp
-- ne lit que la sienne. Les pertes adverses sont degradees A L'ECRITURE via militaire_degrader --
-- la donnee exacte n'entre jamais dans la ligne lisible par l'autre. Rien n'est envoye puis masque.
--
-- ATOMICITE : verrou FOR UPDATE sur la ligne de bataille, plus un index unique
-- (bataille, numero, camp) sur les rapports, plus un index unique partiel garantissant une seule
-- bataille en cours par zone.
--
-- POINT A ARBITRER, isole dans militaire_defense_pnj() : un soldat PNJ ne porte AUCUNE
-- caracteristique defensive. DUP=3 est repris de PNJ_STATS_PAR_JOB.soldat (valeur reelle) et
-- PER=10 de la « valeur neutre deja retenue ailleurs » (neutraliserPerCible). Ce sont les seuls
-- chiffres du moteur qui ne viennent pas du cahier des charges.
--
-- BANCS (transactions annulees, zero residu) :
--   * bataille complete 6v5 : 7 rounds, victoire, 5 PNJ reellement supprimes, PV du PJ inchanges
--   * simultaneite : 60 duels a 1 PA -> 12 aneantissements mutuels, impossibles si le mort ne
--     tirait pas ; echecs critiques marques 7 fois (~5 % attendu)
--   * gilet : 50 tirs mortels -> 15 neutralisations evitees / 13 morts (50 % attendu) et
--     15 gilets fragilises ; 30 coups d'arme blanche -> 0 declenchement
--   * repli : 6 sovietiques avant et apres le decrochage (aucune riposte), survivants deplaces
--     vers la position canonique capturee a l'ouverture
--   * doctrine : tenir -> 10 morts sur 10 ; repli_50 -> decrochage a 5/10, 4 survivants
--   * concurrence : deux resolutions donnent les rounds 1 puis 2, 4 lignes de rapport
--   * securite : round, appliquer, soldat_supprimer et soldat_pa_fixer refuses a authenticated

-- ============================================================================
-- LOT 3 : INTERFACE, HISTORIQUE, ET RETRAIT DE L'ANCIEN MOTEUR (19 septembre 2026)
--
-- ANCIEN MOTEUR COLLECTIF SUPPRIME cote client : calculerPointsGroupe, getCoefsArmesPays,
-- construireCivilsCombat, verifierCombatAutomatique et resoudreCombat partent ENSEMBLE, avec
-- l'appel automatique que deposerSoldats faisait sur eux. Il formait une SECONDE resolution
-- concurrente. Rien de sa formule n'est recupere ; seule la nomenclature d'armes
-- COEF_ARME_MILITAIRE est conservee, parce que c'est le vocabulaire des categories d'arme des
-- soldats et non un morceau de moteur.
--
-- Une bataille commence desormais sur DECISION d'un chef (militaire_bataille_engager), a partir
-- d'un contact reel -- jamais comme effet de bord d'un depot de troupes.
--
-- PARCOURS CLIENT VERIFIE de bout en bout : etat (aucune bataille) -> engager -> etat (round 0,
-- leader, doctrine tenir) -> decider('continuer') -> round 1 resolu -> bilan observable. Le bilan
-- rendu au camp republicain porte « 5 a 7 soldats » pour un effectif reel de 6 : l'estimation est
-- degradee A L'ECRITURE, le navigateur ne recoit jamais le chiffre exact.

-- ============================================================================
-- LOT 4 : CORRECTIF DE CIBLAGE + FORMULE CALIBREE (20 septembre 2026)
-- Applique sous `combat_ciblage_independant_et_formule` et `combat_actions_photo_complete`.
--
-- BUG CORRIGE. militaire_bataille_actions utilisait :
--   CROSS JOIN LATERAL (SELECT d.* FROM militaire_bataille_combattants(...) d
--                        ORDER BY random() LIMIT 1) c
-- Cette sous-requete ne referencait PAS la ligne attaquante et portait sur une fonction STABLE :
-- PostgreSQL l'evaluait UNE SEULE FOIS et reutilisait la meme cible pour tous les attaquants.
-- Mesure avant correctif : 25 attaquants, 21 jets distincts, UNE seule cible distincte.
-- Consequence : surtuage massif, batailles ~45 rounds au lieu de ~30, et violation du GD
-- (« plusieurs attaquants PEUVENT viser le meme adversaire » etait devenu « visent TOUJOURS le
-- meme »). Les simulations du rapport de phase 3 en etaient faussees.
--
-- La fonction est desormais en plpgsql avec une boucle explicite : les defenseurs sont
-- photographies UNE fois dans des tableaux, puis CHAQUE attaquant tire son propre indice a chaque
-- tour de boucle. Aucune liberte laissee au planificateur.
-- Mesure apres correctif : 25 attaquants -> 15 cibles distinctes, 25 attaquants distincts,
-- 0 cible hors du roster adverse, et le PJ leader vise 40 fois sur 1000 tirs pour 38 attendus
-- (1/26) -- aucun biais leader.
--
-- FORMULE CALIBREE :
--   T = clamp(25 + competence_offensive x 0,7
--                - competence_defensive_cible x 0,5
--                - PER_ou_DUP_cible x 0,5, 10, 85)
-- La competence defend desormais autant qu'elle attaque, a poids reduit. PER/DUP porte le meme
-- coefficient mais sur une amplitude cinq fois moindre (5-20 contre 0-100) : aptitude generale
-- secondaire, jamais dominante.
--
-- La competence DEFENSIVE est celle du MEME domaine que l'attaque subie : on ne se protege pas
-- d'une balle avec son corps-a-corps.
--
-- Calibrage sur banc (simulateur en memoire, tirage independant, 2000 batailles par point) :
--   10 elites c80 vs 25 recrues c20 -> def 0,35 : 60,0 % | def 0,45 : 71,3 % |
--   def 0,50 : 74,40 % (+/-1,91) | def 0,55 : 84,0 % | def 0,70 : 89,5 %
-- Cible GD 70-75 % : def 0,50 retenu, avec base = 25 (coefficients ronds).
--
-- SIGNATURE CHANGEE : militaire_taux_combat passe de (numeric, numeric) a
-- (numeric, numeric, numeric). L'ancienne est DROPPEE explicitement -- verifie, une seule ligne
-- subsiste dans pg_proc. Elle n'etait accordee a personne, aucun client n'est concerne.
--
-- INCHANGES : de 1..100, clamp 10-85, cinq degres, degats 3/2/1, echec critique 96-100 teste
-- en premier.
--
-- VERIFICATION MOTEUR CONTRE BANC, apres correctif :
--   25c50 sym      : moteur 31,6 rounds / 20,0-20,9 morts | banc 29,9 / 19,0-19,2
--   10c80 vs 25c20 : moteur 30,1 rounds, 9 victoires sur 14 | banc 32,0 / 74,4 %
--   4c95 vs 25c50  : moteur 12,7 rounds, 4-0 | banc 13,1 / 4-0
--   4c50 vs 25c50  : moteur 4,8 rounds, 4-0  | banc 5,5 / 4-0
--
-- HORS PERIMETRE, volontairement : l'annihilation symetrique (condition de fin) et la surprise
-- (mecanique d'ouverture). Le banc a etabli qu'aucune ne depend des coefficients.
