-- GRANT sur tables, colonnes et fonctions
-- ============================================================================
-- BASELINE Human Gambit -- domaine assemblee -- phase 70 : droits
--
-- Fichier GENERE par outils/baseline/rendre.py depuis les catalogues
-- PostgreSQL. Ne pas editer a la main : toute correction passe par une
-- migration, puis par une nouvelle extraction.
--
-- ORDRE D'APPLICATION : par PHASE croissante, tous domaines confondus, et non
-- domaine par domaine. Voir baseline/README.md.
-- ============================================================================

-- DROITS SUR LES FUNCTIONS
GRANT EXECUTE ON FUNCTION public.assemblee_achat_illegal(text,text,text,text) TO anon;
GRANT EXECUTE ON FUNCTION public.assemblee_achat_illegal(text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assemblee_achat_illegal(text,text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_achat_illegal(text,text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_amender(text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assemblee_amender(text,text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_amender(text,text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_catalogue_legislatif() TO authenticated;
GRANT EXECUTE ON FUNCTION public.assemblee_catalogue_legislatif() TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_catalogue_legislatif() TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_cle_convocation(jsonb) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.assemblee_cle_convocation(jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.assemblee_cle_convocation(jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assemblee_cle_convocation(jsonb) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_cle_convocation(jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_cloturer(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_cloturer(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_cloturer_echues(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_cloturer_echues(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_compter_unites(jsonb,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_compter_unites(jsonb,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_consulter_lobbyiste(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assemblee_consulter_lobbyiste(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_consulter_lobbyiste(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_crediter_caisse(text,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_crediter_caisse(text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_crediter_joueur(text,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_crediter_joueur(text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_debiter_caisse_plafonne(text,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_debiter_caisse_plafonne(text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_debiter_joueur(text,integer,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_debiter_joueur(text,integer,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_deposer(text,text,text,text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assemblee_deposer(text,text,text,text,text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_deposer(text,text,text,text,text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_deposer_projet(text,text,text,text,text,text,text,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assemblee_deposer_projet(text,text,text,text,text,text,text,jsonb) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_deposer_projet(text,text,text,text,text,text,text,jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_detecter_partie(text,text,jsonb,text,integer,boolean) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_detecter_partie(text,text,jsonb,text,integer,boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_echeance_application(timestamp with time zone) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assemblee_echeance_application(timestamp with time zone) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_echeance_application(timestamp with time zone) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_echeance_palier(timestamp with time zone,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assemblee_echeance_palier(timestamp with time zone,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_echeance_palier(timestamp with time zone,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_exige_application(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assemblee_exige_application(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_exige_application(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_fenetre_ouverture(timestamp with time zone) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_fenetre_ouverture(timestamp with time zone) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_fret_vente_legale() TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_fret_vente_legale() TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_gouvernement_actuel(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assemblee_gouvernement_actuel(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_gouvernement_actuel(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_lier_topic(text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assemblee_lier_topic(text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_lier_topic(text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_loi_en_vigueur(text,jsonb,timestamp with time zone) TO anon;
GRANT EXECUTE ON FUNCTION public.assemblee_loi_en_vigueur(text,jsonb,timestamp with time zone) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assemblee_loi_en_vigueur(text,jsonb,timestamp with time zone) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_loi_en_vigueur(text,jsonb,timestamp with time zone) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_marchander(text,text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assemblee_marchander(text,text,text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_marchander(text,text,text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_marquer_convocations_echues(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_marquer_convocations_echues(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_mettre_en_application(text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assemblee_mettre_en_application(text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_mettre_en_application(text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_neutraliser_depute(text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assemblee_neutraliser_depute(text,text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_neutraliser_depute(text,text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_objet_vise(text,jsonb,jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.assemblee_objet_vise(text,jsonb,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assemblee_objet_vise(text,jsonb,jsonb) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_objet_vise(text,jsonb,jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_occupation_sieges(text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.assemblee_occupation_sieges(text) TO anon;
GRANT EXECUTE ON FUNCTION public.assemblee_occupation_sieges(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assemblee_occupation_sieges(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_occupation_sieges(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_ouvrir_session(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_ouvrir_session(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_ouvrir_sessions_eligibles(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_ouvrir_sessions_eligibles(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_palier_atteint(timestamp with time zone,timestamp with time zone) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assemblee_palier_atteint(timestamp with time zone,timestamp with time zone) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_palier_atteint(timestamp with time zone,timestamp with time zone) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_peut_deposer(text,text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.assemblee_peut_deposer(text,text) TO anon;
GRANT EXECUTE ON FUNCTION public.assemblee_peut_deposer(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assemblee_peut_deposer(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_peut_deposer(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_pop_du_palier(integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assemblee_pop_du_palier(integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_pop_du_palier(integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_portee_valider(jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assemblee_portee_valider(jsonb) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_portee_valider(jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_prochaine_cloture(timestamp with time zone) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_prochaine_cloture(timestamp with time zone) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_proposition_immuable() TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_proposition_immuable() TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_registre_execution(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assemblee_registre_execution(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_registre_execution(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_requete_clore(text,jsonb) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_requete_clore(text,jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_requete_ouvrir(text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_requete_ouvrir(text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_retirer(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assemblee_retirer(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_retirer(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_retirer_une_unite(jsonb,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_retirer_une_unite(jsonb,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_reveil_minuit(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_reveil_minuit(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_reveiller_depute(text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assemblee_reveiller_depute(text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_reveiller_depute(text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_sanctionner_lois_non_appliquees(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_sanctionner_lois_non_appliquees(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_sous_types_connus(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_sous_types_connus(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_stat_base(jsonb,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_stat_base(jsonb,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_taux_marchandage(jsonb,boolean) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_taux_marchandage(jsonb,boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_taux_neutralisation(text,jsonb,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_taux_neutralisation(text,jsonb,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_tracer_vente_interdite(text,text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_tracer_vente_interdite(text,text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_transaction_interdite_interne(text,text,text,jsonb,text,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_transaction_interdite_interne(text,text,text,jsonb,text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_verifier_vente(jsonb,text) TO anon;
GRANT EXECUTE ON FUNCTION public.assemblee_verifier_vente(jsonb,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assemblee_verifier_vente(jsonb,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_verifier_vente(jsonb,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_verser_indemnite(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assemblee_verser_indemnite(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_verser_indemnite(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.assemblee_voter(text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assemblee_voter(text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.assemblee_voter(text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.depute_presence(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.depute_presence(text) TO service_role;

-- DROITS SUR LES TABLES
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.assemblee_catalogue_illegal TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.assemblee_catalogue_illegal TO service_role;
GRANT SELECT ON TABLE public.assemblee_categories_interdiction TO anon;
GRANT SELECT ON TABLE public.assemblee_categories_interdiction TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.assemblee_categories_interdiction TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.assemblee_categories_interdiction TO service_role;
GRANT SELECT ON TABLE public.assemblee_indemnites TO anon;
GRANT SELECT ON TABLE public.assemblee_indemnites TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.assemblee_indemnites TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.assemblee_indemnites TO service_role;
GRANT SELECT ON TABLE public.assemblee_intentions TO anon;
GRANT SELECT ON TABLE public.assemblee_intentions TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.assemblee_intentions TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.assemblee_intentions TO service_role;
GRANT SELECT ON TABLE public.assemblee_propositions TO anon;
GRANT SELECT ON TABLE public.assemblee_propositions TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.assemblee_propositions TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.assemblee_propositions TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.assemblee_requetes TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.assemblee_requetes TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.assemblee_sanctions_paliers TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.assemblee_sanctions_paliers TO service_role;
GRANT SELECT ON TABLE public.assemblee_scrutins TO anon;
GRANT SELECT ON TABLE public.assemblee_scrutins TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.assemblee_scrutins TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.assemblee_scrutins TO service_role;
GRANT SELECT ON TABLE public.assemblee_sieges TO anon;
GRANT SELECT ON TABLE public.assemblee_sieges TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.assemblee_sieges TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.assemblee_sieges TO service_role;
GRANT SELECT ON TABLE public.assemblee_votes TO anon;
GRANT SELECT ON TABLE public.assemblee_votes TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.assemblee_votes TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.assemblee_votes TO service_role;
