-- Commentaires d'objets
-- ============================================================================
-- BASELINE Human Gambit -- domaine assemblee -- phase 80 : commentaires
--
-- Fichier GENERE par outils/baseline/rendre.py depuis les catalogues
-- PostgreSQL. Ne pas editer a la main : toute correction passe par une
-- migration, puis par une nouvelle extraction.
--
-- ORDRE D'APPLICATION : par PHASE croissante, tous domaines confondus, et non
-- domaine par domaine. Voir baseline/README.md.
-- ============================================================================

COMMENT ON COLUMN public.assemblee_propositions.appliquee_par IS 'Nom du personnage qui a prononce la mise en application. Tracabilite seule : l''autorite est verifiee au moment de l''acte, pas relue ici.';
COMMENT ON COLUMN public.assemblee_propositions.appliquee_ts IS 'Instant SERVEUR de la mise en application par le Ministre de l''Interieur. NULL = adoptee mais pas encore appliquee : la loi existe politiquement, ses effets mecaniques ne sont pas actifs. Toujours NULL pour une loi de type rp, qui n''a rien a appliquer.';
COMMENT ON FUNCTION public.assemblee_catalogue_legislatif() IS 'Tout ce qu''un juriste de l''Assemblee est autorise a connaitre : les categories d''interdiction votables (avec ce qu''elles visent et si la transformation ou la production ont un sens pour elles), les circuits reels de chaque matiere economique, et la liste FERMEE des dimensions de portee que le moteur sait appliquer. Lu en base a chaque consultation : ajouter une categorie ou une matiere suffit a ce que Seb Lex la connaisse. Ne decide rien, n''ecrit rien.';
COMMENT ON FUNCTION public.assemblee_deposer(text,text,text,text,text,text,text) IS 'RELAIS (30 septembre 2026) vers assemblee_deposer_projet, sans portee -- donc cas A par defaut pour une loi mecanique. Signature inchangee : aucun appelant deploye ne casse. Ne contient plus aucune logique.';
COMMENT ON FUNCTION public.assemblee_deposer_projet(text,text,text,text,text,text,text,jsonb) IS 'Depot d''un projet de loi, portee mecanique comprise (data.portee, validee contre une liste fermee). Porte canonique depuis le 30 septembre 2026 ; assemblee_deposer la relaie sans portee. Exige la presence dans l''hemicycle, l''eligibilite (depute, PM, ministres) et debite 1 PA -- uniquement au depot effectif.';
COMMENT ON FUNCTION public.assemblee_echeance_application(timestamp with time zone) IS 'Instant limite de mise en application : adoption + 36 heures reelles. Le chrono demarre a l''ADOPTION et appartient a la loi -- aucun changement de ministre, de gouvernement ou de president ne le remet a zero.';
COMMENT ON FUNCTION public.assemblee_exige_application(text) IS 'Un type de proposition entre-t-il dans le cycle d''execution gouvernementale ? mecanique et abrogation : oui. rp : non, une loi declarative est terminee des son adoption. Seul endroit du serveur ou cette frontiere est ecrite.';
COMMENT ON FUNCTION public.assemblee_gouvernement_actuel(text) IS 'Les titulaires du President, du Premier ministre et de tous les ministeres A CET INSTANT. La convention d''identifiant « min_ » couvre aussi un ministere cree en cours de partie. Sert aux sanctions : elles frappent ceux qui occupent les postes au moment du tick, jamais ceux qui etaient la au vote.';
COMMENT ON FUNCTION public.assemblee_loi_en_vigueur(text,jsonb,timestamp with time zone) IS 'La loi mecanique qui produit SES EFFETS sur cet objet a cet instant, ou NULL. Depuis le 30 septembre 2026, une loi adoptee mais non encore mise en application par le Ministre de l''Interieur n''est PAS en vigueur : l''adoption est parlementaire, l''entree en vigueur est executive. L''objet rendu porte la portee votee (data.portee), que lisent les gardes de transformation. Source unique pour les quatorze consommateurs -- aucun ne duplique ce test.';
COMMENT ON FUNCTION public.assemblee_mettre_en_application(text,text,text) IS 'Mise en application d''une loi adoptee par le Ministre de l''Interieur EN FONCTION. Le client ne transmet QUE l''identifiant : le serveur verifie l''identite, le poste (lu en base), l''adoption, la non-application prealable, puis relit lui-meme la portee votee. Une abrogation eteint sa cible dans la meme transaction. Idempotente par cle de requete. Aucun parametre economique ne vient du navigateur.';
COMMENT ON FUNCTION public.assemblee_objet_vise(text,jsonb,jsonb) IS 'Un objet est-il vise par une categorie, COMPTE TENU de la portee votee ? La portee restreint, elle n''elargit jamais : volet_matieres, volet_objets et sous_types ne font que retrancher a ce que la categorie recouvre. Chantier 4D.';
COMMENT ON FUNCTION public.assemblee_palier_atteint(timestamp with time zone,timestamp with time zone) IS 'Numero du dernier palier de sanction atteint a cet instant : 0 avant H+36, 1 a H+36, 2 a H+60, 3 a H+84, puis un de plus toutes les 24 heures. Arithmetique pure, sans effet de bord.';
COMMENT ON FUNCTION public.assemblee_pop_du_palier(integer) IS 'Perte de popularite d''un palier : -20 au premier (H+36), -10 a chacun des suivants. Bareme de l''arbitrage du 30 septembre 2026.';
COMMENT ON FUNCTION public.assemblee_portee_valider(jsonb) IS 'Valide la portee mecanique d''un projet de loi contre une liste FERMEE de dimensions reellement implementees. Aujourd''hui une seule : transformation_stock_interdite (cas B de l''arbitrage). Absente = cas A. Toute cle ou valeur inconnue est refusee : l''IA ne peut pas inventer un effet.';
COMMENT ON FUNCTION public.assemblee_registre_execution(text) IS 'Registre du Ministre de l''Interieur : les lois adoptees qui exigent une mise en application (mecanique, abrogation), en attente d''abord puis appliquees. Porte l''etat, l''echeance (adoption + 36 h), la portee votee, la loi cible d''une abrogation, et l''instant SERVEUR. Les lois rp n''y figurent jamais : elles sont terminees des leur adoption.';
COMMENT ON FUNCTION public.assemblee_sanctionner_lois_non_appliquees(text) IS 'Passe de sanction des lois adoptees et non mises en application. -20 POP au palier H+36, -10 a chaque palier suivant (toutes les 24 h). Strictement idempotente : la cle primaire <loi>:<palier> de assemblee_sanctions_paliers interdit tout second debit, quel que soit le rejeu, la concurrence ou l''appel manuel. Rattrape les paliers manques un par un. Frappe les titulaires du President, du Premier ministre et de tous les ministeres A L''INSTANT DU TICK. Utilise la primitive canonique personnage_ajuster_pop_inf (delta, verrou, bornes). Reservee au serveur.';
COMMENT ON FUNCTION public.assemblee_sous_types_connus(text) IS 'Les sous-types reellement presents dans le jeu pour un type d''objet, deduits du catalogue des objets illegaux et du miroir des recettes militaires. Sert a proposer au deposant un choix qui existe. Chantier 4D.';
COMMENT ON FUNCTION public.assemblee_tracer_vente_interdite(text,text,text,text) IS 'INTERNE : a appeler uniquement depuis une transaction de vente serveur. Jamais expose au client.';
COMMENT ON TABLE public.assemblee_sanctions_paliers IS 'Registre durable des paliers de sanction DEJA debites pour une loi non appliquee. La cle primaire <proposition_id>:<palier> est l''idempotence : un rejeu, deux crons concurrents ou un appel manuel ne peuvent pas debiter deux fois le meme palier. titulaires garde la trace nominative des personnages sanctionnes a cet instant.';
COMMENT ON TABLE public.assemblee_sieges IS 'Sieges de l''Assemblee. Porte l''identite PERMANENTE du depute Gamma de chaque siege : cette ligne n''est jamais videe, meme quand un PJ occupe le siege. La PRESENCE du Gamma est derivee (assemblee_occupation_sieges / depute_presence), donc reversible : quand le PJ s''en va, LE MEME depute revient. Ne jamais supprimer une ligne pour representer une absence.';
