-- SEED -- commerces_dotations
-- ============================================================================
-- Table      : public.commerces_dotations
-- Domaine    : economie
-- Categorie  : A (socle generique)
-- Strategie  : seed_complet (classification du chantier 2C)
-- Lignes     : 11
--
-- Fichier GENERE par outils/baseline/seeds.py. Ne pas editer a la main.
-- Les litteraux sont ceux que PostgreSQL lui-meme a produits (quote_nullable) :
-- aucune regle d'echappement n'a ete reimplementee.
--
-- JUSTIFICATION DU SEED (chantier 2C)
-- Dotation initiale de stock par type de commerce.
--
-- AVERTISSEMENT : CETTE TABLE EST UN MIROIR DE data.js
-- Un generateur existe deja :
-- outils/generateurs/generer_miroirs_entreprises.py. Les lignes ci-dessous
-- sont copiees depuis la base, conformement a la strategie seed_complet du
-- chantier 2C -- mais copier un miroir fige sa derive. Celui des couts
-- d'ordre avait derive de 24 lignes mortes et 19 ordres gratuits non
-- declares. A terme, ce fichier doit etre ecrit par son generateur depuis
-- data.js, et la table doit rejoindre 95_a-regenerer.
-- ============================================================================

INSERT INTO public.commerces_dotations (cle, type, caisse, stock_matieres, cout_moyen_matieres, carte, parametres) VALUES ('bar-des-pecheurs|salle_bar', 'bar', '2000', '{"cereales": 10, "fruits_legumes": 10, "produits_exotiques": 10}', '{"cereales": 3, "fruits_legumes": 4, "produits_exotiques": 6}', '["biere_pression", "vin", "cafe_boisson", "boisson_sans_alcool", "snack_buvette"]', '{"stockMax": {"vin": 20, "cafe_boisson": 20, "snack_buvette": 20, "biere_pression": 20, "boisson_sans_alcool": 20}, "prixVente": {"vin": 7, "cafe_boisson": 7, "snack_buvette": 7, "biere_pression": 7, "boisson_sans_alcool": 10}}');
INSERT INTO public.commerces_dotations (cle, type, caisse, stock_matieres, cout_moyen_matieres, carte, parametres) VALUES ('brasserie-voyageurs-montrouge', 'brasserie', '3000', '{"viande": 15, "poisson": 10, "cereales": 15}', '{"viande": 5, "poisson": 4, "cereales": 3}', '["carbonade_frites", "plat_de_poisson", "saucisse_puree"]', '{"stockMax": {"saucisse_puree": 20, "plat_de_poisson": 20, "carbonade_frites": 20}, "prixVente": {"saucisse_puree": 23, "plat_de_poisson": 23, "carbonade_frites": 23}}');
INSERT INTO public.commerces_dotations (cle, type, caisse, stock_matieres, cout_moyen_matieres, carte, parametres) VALUES ('cafe-gare-montrouge', 'cafe', '2000', '{"viande": 10, "cereales": 10, "fruits_legumes": 10, "produits_exotiques": 10}', '{"viande": 5, "cereales": 3, "fruits_legumes": 4, "produits_exotiques": 6}', '["boeuf_bourguignon", "cafe_boisson", "jus_de_fruits", "vin", "biere_pression"]', '{"stockMax": {"vin": 20, "cafe_boisson": 20, "jus_de_fruits": 20, "biere_pression": 20, "boeuf_bourguignon": 20}, "prixVente": {"vin": 7, "cafe_boisson": 7, "jus_de_fruits": 7, "biere_pression": 7, "boeuf_bourguignon": 23}}');
INSERT INTO public.commerces_dotations (cle, type, caisse, stock_matieres, cout_moyen_matieres, carte, parametres) VALUES ('cafe-tabac-cheminots-montrouge', 'cafe', '2000', '{"viande": 10, "cereales": 10, "fruits_legumes": 10, "produits_exotiques": 10}', '{"viande": 5, "cereales": 3, "fruits_legumes": 4, "produits_exotiques": 6}', '["sandwich_cheminots", "cafe_boisson", "jus_de_fruits", "vin", "biere_pression"]', '{"stockMax": {"vin": 20, "cafe_boisson": 20, "jus_de_fruits": 20, "biere_pression": 20, "sandwich_cheminots": 20}, "prixVente": {"vin": 7, "cafe_boisson": 7, "jus_de_fruits": 7, "biere_pression": 7, "sandwich_cheminots": 10}}');
INSERT INTO public.commerces_dotations (cle, type, caisse, stock_matieres, cout_moyen_matieres, carte, parametres) VALUES ('capitaine-sauvage|salle_principale', 'brasserie', '3000', '{"viande": 10, "poisson": 10, "cereales": 15, "fruits_legumes": 10}', '{"viande": 5, "poisson": 4, "cereales": 3, "fruits_legumes": 4}', '["menu_psm_1", "menu_psm_2", "menu_psm_3", "vin"]', '{"stockMax": {"vin": 20, "menu_psm_1": 20, "menu_psm_2": 20, "menu_psm_3": 20}, "prixVente": {"vin": 7, "menu_psm_1": 20, "menu_psm_2": 21, "menu_psm_3": 20}}');
INSERT INTO public.commerces_dotations (cle, type, caisse, stock_matieres, cout_moyen_matieres, carte, parametres) VALUES ('hotel-mineur', 'cafe', '1000', '{"cereales": 10}', '{"cereales": 3}', '["petit_dejeuner"]', '{"stockMax": {"petit_dejeuner": 20}, "prixVente": {"petit_dejeuner": 11}}');
INSERT INTO public.commerces_dotations (cle, type, caisse, stock_matieres, cout_moyen_matieres, carte, parametres) VALUES ('hotel-port|hall_port', 'cafe', '1000', '{"cereales": 10}', '{"cereales": 3}', '["petit_dejeuner"]', '{"stockMax": {"petit_dejeuner": 20}, "prixVente": {"petit_dejeuner": 11}}');
INSERT INTO public.commerces_dotations (cle, type, caisse, stock_matieres, cout_moyen_matieres, carte, parametres) VALUES ('hotel-republica', 'brasserie', '5000', '{"viande": 15, "poisson": 10, "cereales": 25, "fruits_legumes": 20, "produits_exotiques": 10}', '{"viande": 5, "poisson": 4, "cereales": 3, "fruits_legumes": 4, "produits_exotiques": 6}', '["menu_gastronomique_1", "menu_gastronomique_2", "menu_gastronomique_3", "vin", "cafe_boisson", "biere_pression", "snack_buvette"]', '{"stockMax": {"vin": 20, "cafe_boisson": 20, "snack_buvette": 20, "biere_pression": 20, "menu_gastronomique_1": 20, "menu_gastronomique_2": 20, "menu_gastronomique_3": 20}, "prixVente": {"vin": 7, "cafe_boisson": 7, "snack_buvette": 7, "biere_pression": 7, "menu_gastronomique_1": 120, "menu_gastronomique_2": 120, "menu_gastronomique_3": 120}}');
INSERT INTO public.commerces_dotations (cle, type, caisse, stock_matieres, cout_moyen_matieres, carte, parametres) VALUES ('marche', 'marche', '0', '{"bois": 10, "metal": 10, "viande": 10, "textile": 10, "cereales": 10, "fruits_legumes": 10, "produits_exotiques": 10}', '{"bois": 5, "metal": 15, "viande": 5, "textile": 5, "cereales": 3, "fruits_legumes": 4, "produits_exotiques": 6}', '["croque_monsieur_luthecia", "echarpe_luthecia", "carte_luthecia_institutions", "carte_luthecia_internationale", "carte_luthecia_culture", "porte_cle_palais_luthecia", "garde_republien_plomb", "figurine_maxence_monfils"]', '{"stockMax": {"echarpe_luthecia": 20, "garde_republien_plomb": 20, "carte_luthecia_culture": 20, "croque_monsieur_luthecia": 20, "figurine_maxence_monfils": 20, "porte_cle_palais_luthecia": 20, "carte_luthecia_institutions": 20, "carte_luthecia_internationale": 20}, "prixVente": {"echarpe_luthecia": 20, "garde_republien_plomb": 22, "carte_luthecia_culture": 7, "croque_monsieur_luthecia": 16, "figurine_maxence_monfils": 22, "porte_cle_palais_luthecia": 22, "carte_luthecia_institutions": 7, "carte_luthecia_internationale": 7}}');
INSERT INTO public.commerces_dotations (cle, type, caisse, stock_matieres, cout_moyen_matieres, carte, parametres) VALUES ('marche-psm|etals', 'marche', '0', '{"bois": 10, "poisson": 10, "textile": 10, "cereales": 10}', '{"bois": 5, "poisson": 4, "textile": 5, "cereales": 3}', '["cornet_friture_psm", "tshirt_psm", "carte_psm_notre_dame_mer", "carte_psm_touristique", "carte_psm_culture_marine"]', '{"stockMax": {"tshirt_psm": 20, "cornet_friture_psm": 20, "carte_psm_touristique": 20, "carte_psm_culture_marine": 20, "carte_psm_notre_dame_mer": 20}, "prixVente": {"tshirt_psm": 20, "cornet_friture_psm": 14, "carte_psm_touristique": 7, "carte_psm_culture_marine": 7, "carte_psm_notre_dame_mer": 7}}');
INSERT INTO public.commerces_dotations (cle, type, caisse, stock_matieres, cout_moyen_matieres, carte, parametres) VALUES ('stade|buvette', 'buvette', '0', '{"alcool": 10, "cereales": 5}', '{"alcool": 14, "cereales": 3}', '["biere_pression", "boisson_sans_alcool", "snack_buvette"]', '{"stockMax": {"snack_buvette": 20, "biere_pression": 20, "boisson_sans_alcool": 20}, "prixVente": {"snack_buvette": 7, "biere_pression": 7, "boisson_sans_alcool": 10}}');
