-- SEED -- mails_expediteurs_systeme
-- ============================================================================
-- Table      : public.mails_expediteurs_systeme
-- Domaine    : communication
-- Categorie  : A (socle generique)
-- Strategie  : seed_complet (classification du chantier 2C)
-- Lignes     : 28
--
-- Fichier GENERE par outils/baseline/seeds.py. Ne pas editer a la main.
-- Les litteraux sont ceux que PostgreSQL lui-meme a produits (quote_nullable) :
-- aucune regle d'echappement n'a ete reimplementee.
--
-- JUSTIFICATION DU SEED (chantier 2C)
-- 28 expediteurs systeme autorises et leurs droits de saisine. Liste blanche
-- du moteur.
-- ============================================================================

INSERT INTO public.mails_expediteurs_systeme (expediteur, note, est_prefixe, postes, autorise_soi, libre, autorise_vers_titulaire, autorise_vers_conjoint, autorise_vers_destinataire_fret) VALUES ('Administration Portuaire', 'port', 'false', '{capitaine_port}', 'false', 'false', 'false', 'false', 'true');
INSERT INTO public.mails_expediteurs_systeme (expediteur, note, est_prefixe, postes, autorise_soi, libre, autorise_vers_titulaire, autorise_vers_conjoint, autorise_vers_destinataire_fret) VALUES ('Alerte confidentielle', 'renseignement', 'false', '{juge,min_just,min_int}', 'false', 'false', 'false', 'false', 'false');
INSERT INTO public.mails_expediteurs_systeme (expediteur, note, est_prefixe, postes, autorise_soi, libre, autorise_vers_titulaire, autorise_vers_conjoint, autorise_vers_destinataire_fret) VALUES ('Anonyme', 'repli quand le nom du joueur manque', 'false', '{}', 'false', 'true', 'false', 'false', 'false');
INSERT INTO public.mails_expediteurs_systeme (expediteur, note, est_prefixe, postes, autorise_soi, libre, autorise_vers_titulaire, autorise_vers_conjoint, autorise_vers_destinataire_fret) VALUES ('Assemblée Nationale', 'assemblee', 'false', '{}', 'false', 'true', 'false', 'false', 'false');
INSERT INTO public.mails_expediteurs_systeme (expediteur, note, est_prefixe, postes, autorise_soi, libre, autorise_vers_titulaire, autorise_vers_conjoint, autorise_vers_destinataire_fret) VALUES ('Brigade Criminelle', 'police', 'false', '{}', 'true', 'false', 'false', 'false', 'false');
INSERT INTO public.mails_expediteurs_systeme (expediteur, note, est_prefixe, postes, autorise_soi, libre, autorise_vers_titulaire, autorise_vers_conjoint, autorise_vers_destinataire_fret) VALUES ('Bureau National de l''Emploi', 'emploi', 'false', '{}', 'true', 'false', 'false', 'false', 'false');
INSERT INTO public.mails_expediteurs_systeme (expediteur, note, est_prefixe, postes, autorise_soi, libre, autorise_vers_titulaire, autorise_vers_conjoint, autorise_vers_destinataire_fret) VALUES ('Chef des Douanes', 'douanes', 'false', '{chef_douanes}', 'false', 'false', 'false', 'false', 'false');
INSERT INTO public.mails_expediteurs_systeme (expediteur, note, est_prefixe, postes, autorise_soi, libre, autorise_vers_titulaire, autorise_vers_conjoint, autorise_vers_destinataire_fret) VALUES ('Chercheurs Civils', 'recherche', 'false', '{}', 'false', 'true', 'false', 'false', 'false');
INSERT INTO public.mails_expediteurs_systeme (expediteur, note, est_prefixe, postes, autorise_soi, libre, autorise_vers_titulaire, autorise_vers_conjoint, autorise_vers_destinataire_fret) VALUES ('Commandement', 'militaire', 'false', '{commandant}', 'false', 'false', 'false', 'false', 'false');
INSERT INTO public.mails_expediteurs_systeme (expediteur, note, est_prefixe, postes, autorise_soi, libre, autorise_vers_titulaire, autorise_vers_conjoint, autorise_vers_destinataire_fret) VALUES ('Détachement militaire', 'militaire', 'false', '{}', 'false', 'true', 'false', 'false', 'false');
INSERT INTO public.mails_expediteurs_systeme (expediteur, note, est_prefixe, postes, autorise_soi, libre, autorise_vers_titulaire, autorise_vers_conjoint, autorise_vers_destinataire_fret) VALUES ('Événement', 'evenement', 'false', '{}', 'false', 'true', 'false', 'false', 'false');
INSERT INTO public.mails_expediteurs_systeme (expediteur, note, est_prefixe, postes, autorise_soi, libre, autorise_vers_titulaire, autorise_vers_conjoint, autorise_vers_destinataire_fret) VALUES ('Événement mystérieux', 'evenement', 'false', '{}', 'false', 'true', 'false', 'false', 'false');
INSERT INTO public.mails_expediteurs_systeme (expediteur, note, est_prefixe, postes, autorise_soi, libre, autorise_vers_titulaire, autorise_vers_conjoint, autorise_vers_destinataire_fret) VALUES ('Jérémy', 'quete d accueil — PNJ', 'false', '{}', 'true', 'false', 'false', 'false', 'false');
INSERT INTO public.mails_expediteurs_systeme (expediteur, note, est_prefixe, postes, autorise_soi, libre, autorise_vers_titulaire, autorise_vers_conjoint, autorise_vers_destinataire_fret) VALUES ('Jodie Moitout', 'presse — PNJ', 'false', '{}', 'true', 'false', 'false', 'false', 'false');
INSERT INTO public.mails_expediteurs_systeme (expediteur, note, est_prefixe, postes, autorise_soi, libre, autorise_vers_titulaire, autorise_vers_conjoint, autorise_vers_destinataire_fret) VALUES ('Lieutenant ', 'prefixe : « Lieutenant <nom> », hierarchie militaire', 'true', '{lieutenant,capitaine,commandant}', 'false', 'false', 'false', 'false', 'false');
INSERT INTO public.mails_expediteurs_systeme (expediteur, note, est_prefixe, postes, autorise_soi, libre, autorise_vers_titulaire, autorise_vers_conjoint, autorise_vers_destinataire_fret) VALUES ('Ligue Officielle', 'championnat', 'false', '{}', 'false', 'true', 'false', 'false', 'false');
INSERT INTO public.mails_expediteurs_systeme (expediteur, note, est_prefixe, postes, autorise_soi, libre, autorise_vers_titulaire, autorise_vers_conjoint, autorise_vers_destinataire_fret) VALUES ('Mairie', 'mairie', 'false', '{maire,maire_adjoint}', 'false', 'false', 'false', 'true', 'false');
INSERT INTO public.mails_expediteurs_systeme (expediteur, note, est_prefixe, postes, autorise_soi, libre, autorise_vers_titulaire, autorise_vers_conjoint, autorise_vers_destinataire_fret) VALUES ('Ministère de la Défense', 'militaire', 'false', '{min_def}', 'false', 'false', 'false', 'false', 'false');
INSERT INTO public.mails_expediteurs_systeme (expediteur, note, est_prefixe, postes, autorise_soi, libre, autorise_vers_titulaire, autorise_vers_conjoint, autorise_vers_destinataire_fret) VALUES ('Ministère de la Justice', 'justice', 'false', '{min_just}', 'false', 'false', 'false', 'false', 'false');
INSERT INTO public.mails_expediteurs_systeme (expediteur, note, est_prefixe, postes, autorise_soi, libre, autorise_vers_titulaire, autorise_vers_conjoint, autorise_vers_destinataire_fret) VALUES ('Ministère des Affaires Étrangères', 'diplomatie', 'false', '{min_ae}', 'false', 'false', 'false', 'false', 'false');
INSERT INTO public.mails_expediteurs_systeme (expediteur, note, est_prefixe, postes, autorise_soi, libre, autorise_vers_titulaire, autorise_vers_conjoint, autorise_vers_destinataire_fret) VALUES ('Ministère des Finances', 'economie', 'false', '{min_fin}', 'false', 'false', 'false', 'false', 'false');
INSERT INTO public.mails_expediteurs_systeme (expediteur, note, est_prefixe, postes, autorise_soi, libre, autorise_vers_titulaire, autorise_vers_conjoint, autorise_vers_destinataire_fret) VALUES ('Office Notarial', 'successions / ventes', 'false', '{}', 'false', 'true', 'false', 'false', 'false');
INSERT INTO public.mails_expediteurs_systeme (expediteur, note, est_prefixe, postes, autorise_soi, libre, autorise_vers_titulaire, autorise_vers_conjoint, autorise_vers_destinataire_fret) VALUES ('Préfecture', 'administration', 'false', '{min_int}', 'true', 'false', 'true', 'false', 'false');
INSERT INTO public.mails_expediteurs_systeme (expediteur, note, est_prefixe, postes, autorise_soi, libre, autorise_vers_titulaire, autorise_vers_conjoint, autorise_vers_destinataire_fret) VALUES ('Service de l''Immigration', 'naturalisation', 'false', '{min_int}', 'true', 'false', 'true', 'false', 'false');
INSERT INTO public.mails_expediteurs_systeme (expediteur, note, est_prefixe, postes, autorise_soi, libre, autorise_vers_titulaire, autorise_vers_conjoint, autorise_vers_destinataire_fret) VALUES ('Services municipaux', 'mairie', 'false', '{maire,maire_adjoint}', 'false', 'false', 'true', 'false', 'false');
INSERT INTO public.mails_expediteurs_systeme (expediteur, note, est_prefixe, postes, autorise_soi, libre, autorise_vers_titulaire, autorise_vers_conjoint, autorise_vers_destinataire_fret) VALUES ('Système', 'avis technique', 'false', '{}', 'false', 'true', 'false', 'false', 'false');
INSERT INTO public.mails_expediteurs_systeme (expediteur, note, est_prefixe, postes, autorise_soi, libre, autorise_vers_titulaire, autorise_vers_conjoint, autorise_vers_destinataire_fret) VALUES ('Tribunal', 'justice', 'false', '{juge,min_just}', 'false', 'false', 'false', 'false', 'false');
INSERT INTO public.mails_expediteurs_systeme (expediteur, note, est_prefixe, postes, autorise_soi, libre, autorise_vers_titulaire, autorise_vers_conjoint, autorise_vers_destinataire_fret) VALUES ('Un citoyen', 'repli quand le nom du joueur manque', 'false', '{}', 'false', 'true', 'false', 'false', 'false');
