-- SEED -- pnj_axes_autorite
-- ============================================================================
-- Table      : public.pnj_axes_autorite
-- Domaine    : socle PNJ
-- Categorie  : A (socle generique)
-- Strategie  : seed_complet (classification du chantier 2C)
-- Lignes     : 40
--
-- Fichier GENERE par outils/baseline/seeds.py. Ne pas editer a la main.
-- Les litteraux sont ceux que PostgreSQL lui-meme a produits (quote_nullable) :
-- aucune regle d'echappement n'a ete reimplementee.
--
-- JUSTIFICATION DU SEED (chantier 2C)
-- Matrice « ou vit la verite » axe par axe. Regle du socle, renseignee en
-- entier.
-- ============================================================================

INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('agent', 'argent', 'blob', 'Magasin historique : agents_renseignement, qui porte deja position, leader_courant et detention_id. 13 fonctions les ecrivent ou les lisent. Basculer cet axe est une refonte : voir la note de pnj_familles_classes pour la liste et les trois bloquants.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('agent', 'pa', 'socle', 'Au socle depuis le 27/09/2026 : 12 PA jamais consommes (classe beta), et propriete institutionnelle `renseignement` avec le pays pour perimetre.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('agent', 'position_leader', 'blob', 'RESTE AU METIER, volontairement. agents_renseignement porte la position et le leader de chaque OCCURRENCE DE MISSION. Or le jeu autorise plusieurs cellules simultanees (aucune garde de quota ; pool de 6 couvertures par sexe et par pays cible pour 3 H + 1 F par cellule, donc 2 cellules par pays et 4 pays = jusqu''a 8), et les 12 lignes historiques en portent la trace : deux cellules ont coexiste 13 h les 21-22/09, la meme identite y etant engagee deux fois, a deux positions. Une identite unique au socle ne peut avoir qu''UNE position : basculer exige un arbitrage.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('agent', 'possessions', 'blob', 'Magasin historique : agents_renseignement, qui porte deja position, leader_courant et detention_id. 13 fonctions les ecrivent ou les lisent. Basculer cet axe est une refonte : voir la note de pnj_familles_classes pour la liste et les trois bloquants.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('agent', 'propriete', 'socle', 'Au socle depuis le 27/09/2026 : 12 PA jamais consommes (classe beta), et propriete institutionnelle `renseignement` avec le pays pour perimetre.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('depute', 'argent', 'institution', 'Classe gamma : l''institution qui porte ce PNJ decide, le socle ne decide rien. Le verrou d''axe est donc ferme, par construction.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('depute', 'pa', 'institution', 'Classe gamma : l''institution qui porte ce PNJ decide, le socle ne decide rien. Le verrou d''axe est donc ferme, par construction.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('depute', 'position_leader', 'institution', 'Classe gamma : l''institution qui porte ce PNJ decide, le socle ne decide rien. Le verrou d''axe est donc ferme, par construction.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('depute', 'possessions', 'institution', 'Classe gamma : l''institution qui porte ce PNJ decide, le socle ne decide rien. Le verrou d''axe est donc ferme, par construction.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('depute', 'propriete', 'institution', 'Classe gamma : l''institution qui porte ce PNJ decide, le socle ne decide rien. Le verrou d''axe est donc ferme, par construction.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('douanier', 'argent', 'socle', NULL);
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('douanier', 'pa', 'socle', 'Sans objet : la classe beta interdit tout debit.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('douanier', 'position_leader', 'institution', 'La position d''un agent de la force publique EST son poste : le miroir la derive du batiment ou vit son effectif. Aucune RPC ne le deplace, et il ne suit aucun leader. Ce n''est donc pas un magasin concurrent a basculer : il n''y a personne a qui prendre l''autorite. Rendre le socle autoritaire ici n''ajouterait aucune capacite et lui ferait seulement cesser de suivre son institution. Deplacer un agent est une mecanique qui n''existe pas ; l''inventer demanderait un arbitrage.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('douanier', 'possessions', 'socle', 'Aucune possession dans le magasin historique.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('douanier', 'propriete', 'socle', NULL);
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('employe', 'argent', 'socle', 'Bascule du 27/09/2026 : employe_recruter / employe_liberer ecrivent pnj_membres, et la production ne contenait aucun employe a migrer. Les structures clientes (state.employes, escort_active) deviennent des projections d''affichage.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('employe', 'pa', 'socle', 'Bascule du 27/09/2026 : employe_recruter / employe_liberer ecrivent pnj_membres, et la production ne contenait aucun employe a migrer. Les structures clientes (state.employes, escort_active) deviennent des projections d''affichage.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('employe', 'position_leader', 'socle', 'Bascule du 27/09/2026 : employe_recruter / employe_liberer ecrivent pnj_membres, et la production ne contenait aucun employe a migrer. Les structures clientes (state.employes, escort_active) deviennent des projections d''affichage.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('employe', 'possessions', 'socle', 'Bascule du 27/09/2026 : employe_recruter / employe_liberer ecrivent pnj_membres, et la production ne contenait aucun employe a migrer. Les structures clientes (state.employes, escort_active) deviennent des projections d''affichage.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('employe', 'propriete', 'socle', 'Bascule du 27/09/2026 : employe_recruter / employe_liberer ecrivent pnj_membres, et la production ne contenait aucun employe a migrer. Les structures clientes (state.employes, escort_active) deviennent des projections d''affichage.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('militant', 'argent', 'socle', 'Bascule du 27/09/2026 : militant_recruter ecrit pnj_membres, et militants_recrutes etait vide -- rien a migrer. Le registre historique reste alimente car sbGetMesMilitants le lit encore. La position du militant est PROPRE (il ne suit personne) et son affichage a l''universite reste pilote par enterRoom.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('militant', 'pa', 'socle', 'Bascule du 27/09/2026 : militant_recruter ecrit pnj_membres, et militants_recrutes etait vide -- rien a migrer. Le registre historique reste alimente car sbGetMesMilitants le lit encore. La position du militant est PROPRE (il ne suit personne) et son affichage a l''universite reste pilote par enterRoom.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('militant', 'position_leader', 'socle', 'Bascule du 27/09/2026 : militant_recruter ecrit pnj_membres, et militants_recrutes etait vide -- rien a migrer. Le registre historique reste alimente car sbGetMesMilitants le lit encore. La position du militant est PROPRE (il ne suit personne) et son affichage a l''universite reste pilote par enterRoom.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('militant', 'possessions', 'socle', 'Bascule du 27/09/2026 : militant_recruter ecrit pnj_membres, et militants_recrutes etait vide -- rien a migrer. Le registre historique reste alimente car sbGetMesMilitants le lit encore. La position du militant est PROPRE (il ne suit personne) et son affichage a l''universite reste pilote par enterRoom.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('militant', 'propriete', 'socle', 'Bascule du 27/09/2026 : militant_recruter ecrit pnj_membres, et militants_recrutes etait vide -- rien a migrer. Le registre historique reste alimente car sbGetMesMilitants le lit encore. La position du militant est PROPRE (il ne suit personne) et son affichage a l''universite reste pilote par enterRoom.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('policier', 'argent', 'socle', NULL);
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('policier', 'pa', 'socle', 'Sans objet : la classe beta interdit tout debit.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('policier', 'position_leader', 'institution', 'La position d''un agent de la force publique EST son poste : le miroir la derive du batiment ou vit son effectif. Aucune RPC ne le deplace, et il ne suit aucun leader. Ce n''est donc pas un magasin concurrent a basculer : il n''y a personne a qui prendre l''autorite. Rendre le socle autoritaire ici n''ajouterait aucune capacite et lui ferait seulement cesser de suivre son institution. Deplacer un agent est une mecanique qui n''existe pas ; l''inventer demanderait un arbitrage.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('policier', 'possessions', 'socle', 'Aucune possession dans le magasin historique.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('policier', 'propriete', 'socle', NULL);
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('soldat', 'argent', 'socle', 'Le blob militaire n''a aucune notion d''argent : cet axe n''a jamais eu de concurrent.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('soldat', 'pa', 'socle', 'Bascule checkpoint A : consommation Alpha generique via pnj_pa_debiter/crediter/fixer ; le metier ne fixe que les couts.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('soldat', 'position_leader', 'socle', 'Bascule checkpoint A : 5 ecrivains de position/leader passent par pnj_membres puis militaire_blob_projeter.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('soldat', 'possessions', 'socle', 'Bascule le 27/09/2026 (lot 4). Les trois ecrivains -- equiper_accessoire, gilet_absorber, ordre_collectif -- ecrivent le socle. Le miroir de cet axe est arrete : `accessoires` dans le blob est un vestige gele, conserve mais plus lu.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('soldat', 'propriete', 'socle', 'Propriete et autorite sont resolues par le socle et le registre des institutions depuis le 27/09. Le blob ne decide que le PERIMETRE -- section ou reserve -- qui est une donnee metier et le reste.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('titulaire_poste', 'argent', 'institution', 'Classe gamma : l''institution qui porte ce PNJ decide, le socle ne decide rien. Le verrou d''axe est donc ferme, par construction.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('titulaire_poste', 'pa', 'institution', 'Classe gamma : l''institution qui porte ce PNJ decide, le socle ne decide rien. Le verrou d''axe est donc ferme, par construction.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('titulaire_poste', 'position_leader', 'institution', 'Classe gamma : l''institution qui porte ce PNJ decide, le socle ne decide rien. Le verrou d''axe est donc ferme, par construction.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('titulaire_poste', 'possessions', 'institution', 'Classe gamma : l''institution qui porte ce PNJ decide, le socle ne decide rien. Le verrou d''axe est donc ferme, par construction.');
INSERT INTO public.pnj_axes_autorite (famille, axe, autorite, note) VALUES ('titulaire_poste', 'propriete', 'institution', 'Classe gamma : l''institution qui porte ce PNJ decide, le socle ne decide rien. Le verrou d''axe est donc ferme, par construction.');
