-- SEED -- pnj_familles_classes
-- ============================================================================
-- Table      : public.pnj_familles_classes
-- Domaine    : socle PNJ
-- Categorie  : A (socle generique)
-- Strategie  : seed_complet (classification du chantier 2C)
-- Lignes     : 8
--
-- Fichier GENERE par outils/baseline/seeds.py. Ne pas editer a la main.
-- Les litteraux sont ceux que PostgreSQL lui-meme a produits (quote_nullable) :
-- aucune regle d'echappement n'a ete reimplementee.
--
-- JUSTIFICATION DU SEED (chantier 2C)
-- Classe par defaut d'une famille de PNJ. Regle du moteur, aucune fonction
-- ne l'ecrit.
-- ============================================================================

INSERT INTO public.pnj_familles_classes (famille, classe, note) VALUES ('agent', 'beta', 'Agent de renseignement. Famille 100 % SERVEUR et PLEINEMENT ACTIVE : 12 agents, 3 cellules, convoques par quatre par le Ministre de la Defense (3 PA du ministre + 500 FR sur la caisse min_def). Aucun PA d''agent, aucun salaire recurrent : une echeance a J+10 balayee par le cron. NON CONVERGEE, VOLONTAIREMENT : 24 fonctions touchent agents_renseignement, dont 13 ecrivent sa position ou son leader_courant, plus le cycle carceral et le contre-espionnage. C''est une refonte, pas une bascule d''axe. BLOQUANTS : (a) aucun profil de caracteristiques arbitre -- seule DUP existe, fixee par role (garde 10, coordinateur 12, conseillere 13, traducteur 15) ; (b) sa table porte deja position/leader/detention, donc un miroir creerait la duplication que l''architecture combat ; (c) l''identite de COUVERTURE, propre a cette famille, n''a aucun equivalent au socle.');
INSERT INTO public.pnj_familles_classes (famille, classe, note) VALUES ('depute', 'gamma', 'Depute PNJ siegeant a l''Assemblee. Donnees : assemblee_sieges (9 lignes, 3 par ville). Vote, son intention se marchande (assemblee_marchander), et un joueur peut l''endormir (assemblee_neutraliser_depute) jusqu''a assemblee_reveil_minuit. Cette entrave est METIER : elle ne tue pas, ne deplace pas, n''approprie pas. Aucun PA : aucune fonction de l''Assemblee n''en touche. Pas inscrit dans pnj_membres, pour la meme raison que le titulaire de poste.');
INSERT INTO public.pnj_familles_classes (famille, classe, note) VALUES ('douanier', 'beta', 'Raccordee au lot 2. 12 PA presents, jamais debites : pnj_pa_garde refuse toute variation de PA hors classe alpha. Un ordre a 0 PA est donc COHERENT avec Beta et ne doit pas etre "corrige". Six caracteristiques renseignees : INT 10 CHA 8 VOL 12 PER 12 DUP 8 ENT 10. Autorite = Chef des Douanes du perimetre, et "personne" est un etat valide. Reste au blob : position_leader.');
INSERT INTO public.pnj_familles_classes (famille, classe, note) VALUES ('employe', 'beta', 'Famille employable du joueur. METIERS attestes dans le champ job : escort, informateur, codetenu, plus le job generique. Stockage : state.employes, persiste dans personnages_donnees.employes -- donc COTE CLIENT. Salaire preleve PAR LE NAVIGATEUR a l''ordre Dormir (payerEmployes / payerEscorts), sans cron ni RPC. Coquille socle prete et vide : pnj_employes_metier. AUCUN PA nulle part, ce qui est coherent avec Beta. BLOQUEE : (a) le recrutement generique est mure volontairement -- confirmerPnjRecrut sort sur "Temporairement indisponible" et tout le code dessous est mort ; (b) les caracteristiques sont TIREES AU HASARD a l''embauche (escort CHA 12-18, DUP 10-16, INT 8-14 ; informateur PER 12-18 ; codetenu FOR et DUP 8-12) et VOL, PER, ENT manquent -- les figer est un arbitrage ; (c) le metier codetenu est MORT-NE, aucun PNJ du jeu ne porte job=codetenu ; (d) deplacer le salaire au serveur changerait des consequences reelles (plainte au tribunal, -20 POP, article de presse) : mecanique existante, hors mandat.');
INSERT INTO public.pnj_familles_classes (famille, classe, note) VALUES ('militant', 'beta', 'Militant recrute par un membre d''une organisation syndicale, 2 PA du JOUEUR, gratuit a vie (aucun salaire, ni navigateur ni cron). Stockage double : table militants_recrutes ET organisations.membres[]. Coquille socle prete et vide : pnj_militants_metier. Pose dans room.persons a l''universite, ne suit jamais personne. BLOQUEE : les six caracteristiques manquent toutes, et sa seule utilite -- le blocus syndical -- est morte en amont (getMonSyndicatEtGrade lit chargerOrgas et state.orgas, qui n''existent ni l''un ni l''autre ; la vraie liste est state.organisations). 0 ligne en production : la famille n''a jamais servi. Reparer ce chemin est un correctif de gameplay, pas une migration.');
INSERT INTO public.pnj_familles_classes (famille, classe, note) VALUES ('policier', 'beta', 'Raccordee au lot 3. 12 PA presents, jamais debites. Multi-ville : le perimetre porte la ville, l''autorite est le Commissaire DE CETTE VILLE, et la caisse municipale n''est accessible qu''a l''autorite de la meme ville. Paye deplacee du navigateur vers le cron de minuit (50 FR/jour, 100 pour le cynophile). Six caracteristiques renseignees : INT 10 CHA 8 VOL 12 PER 12 DUP 8 ENT 10. Reste au blob : position_leader.');
INSERT INTO public.pnj_familles_classes (famille, classe, note) VALUES ('soldat', 'alpha', 'Famille pilote Alpha, entierement au socle depuis le 27 septembre 2026. Position, leader, PA, possessions, argent et propriete font autorite dans pnj_membres ; compagnies_militaires reste le magasin METIER (armes, stockArmes, formation, sections, reserve, missions, mutinerie, compteurs ration/bivouac) et en recoit une projection par militaire_blob_projeter. Ses PA se consomment par les primitives generiques pnj_pa_debiter/crediter/fixer, qui ne tuent jamais : atteindre 0 PA est une constatation rendue au metier, pas un evenement du socle. Ses six caracteristiques metier ne sont PAS renseignees et attendent un arbitrage.');
INSERT INTO public.pnj_familles_classes (famille, classe, note) VALUES ('titulaire_poste', 'gamma', 'Occupe un poste vacant tant qu''aucun PJ ne le prend. Donnees : titulaires_pnj (16 lignes, poste_id + city, la ville NULL valant national). Aucune caracteristique, aucun PA, aucune possession, aucune position stockee. N''EST PAS UNE AUTORITE : un poste tenu par un PNJ laisse l''autorite humaine vacante, et "personne" est un etat valide. Pas inscrit dans pnj_membres : sa position physique n''est definie nulle part et l''inventer serait un arbitrage.');
