-- SEED -- pnj_metiers_profils
-- ============================================================================
-- Table      : public.pnj_metiers_profils
-- Domaine    : socle PNJ
-- Categorie  : A (socle generique)
-- Strategie  : seed_complet (classification du chantier 2C)
-- Lignes     : 10
--
-- Fichier GENERE par outils/baseline/seeds.py. Ne pas editer a la main.
-- Les litteraux sont ceux que PostgreSQL lui-meme a produits (quote_nullable) :
-- aucune regle d'echappement n'a ete reimplementee.
--
-- JUSTIFICATION DU SEED (chantier 2C)
-- Caracteristiques FIXES par metier. Source unique du recrutement, aucun
-- tirage aleatoire.
-- ============================================================================

INSERT INTO public.pnj_metiers_profils (metier, car_int, car_cha, car_vol, car_per, car_dup, car_ent, note, pa_initial, cout_initial, cout_jour, quota_note, classe, role_libelle, recrutable, quota_par_joueur, ordre_fn) VALUES ('agent', '13', '12', '12', '13', '13', '10', 'Metier de la famille agent, classe beta. Profil UNIQUE pour les quatre identites reelles : le role est une specialisation de CAPACITES, pas un profil de caracteristiques. Seule DUP est mecaniquement lue (risque de trace, contre-espionnage) ; INT, CHA, VOL, PER et ENT sont presentes sans mecanique -- aucun effet ne leur est cree.', '0', '0', NULL, 'Quatre identites, une par role. Convoquees par quatre par le Ministre de la Defense : 3 PA du MINISTRE et 500 FR sur la caisse min_def, jamais un cout de l''agent.', NULL, 'Agent de renseignement', 'false', NULL, NULL);
INSERT INTO public.pnj_metiers_profils (metier, car_int, car_cha, car_vol, car_per, car_dup, car_ent, note, pa_initial, cout_initial, cout_jour, quota_note, classe, role_libelle, recrutable, quota_par_joueur, ordre_fn) VALUES ('agent_securite', '10', '8', '16', '12', '8', '10', 'Metier de la famille employe, destine a la classe ALPHA (posee sur l''individu a sa creation, pas ici). Agent de securite prive de l''agence Grobras Securite, Luthecia. VOL 16 et PER 12 arbitres par le GD le 5 octobre 2026 ; INT/CHA/DUP/ENT recopies du profil policier, le metier deja arbitre le plus proche. Aucune valeur inventee.', '1', '500', '0', 'Quota 4 par joueur (arbitrage GD du 5 octobre 2026), porte par quota_par_joueur et applique par employeur_embaucher. Le plafond commun de 10 employes s''applique en plus, pas a la place.', 'alpha', 'Agent de sécurité', 'true', '4', 'embaucher_agent_securite');
INSERT INTO public.pnj_metiers_profils (metier, car_int, car_cha, car_vol, car_per, car_dup, car_ent, note, pa_initial, cout_initial, cout_jour, quota_note, classe, role_libelle, recrutable, quota_par_joueur, ordre_fn) VALUES ('codetenu', '10', '10', '10', '12', '12', '10', 'Metier de la famille employe, classe beta. Profil conserve pour le futur : le metier n''est PAS active, aucun PNJ du jeu ne porte job=codetenu.', '0', '100', '100', 'Un seul. METIER NON ACTIVE : aucun PNJ du jeu ne porte job=codetenu.', 'beta', 'Codétenu', 'false', NULL, NULL);
INSERT INTO public.pnj_metiers_profils (metier, car_int, car_cha, car_vol, car_per, car_dup, car_ent, note, pa_initial, cout_initial, cout_jour, quota_note, classe, role_libelle, recrutable, quota_par_joueur, ordre_fn) VALUES ('douanier', '10', '8', '12', '12', '8', '10', 'Metier des effectifs du service des Douanes, classe beta. Valeurs identiques a celles deja posees au lot 2 : cette ligne devient leur source unique.', '0', '0', NULL, 'Effectifs institutionnels : payes par le cron de minuit sur la caisse du service (50 FR/jour, 100 pour le cynophile), jamais par un joueur.', NULL, 'Douanier', 'false', NULL, NULL);
INSERT INTO public.pnj_metiers_profils (metier, car_int, car_cha, car_vol, car_per, car_dup, car_ent, note, pa_initial, cout_initial, cout_jour, quota_note, classe, role_libelle, recrutable, quota_par_joueur, ordre_fn) VALUES ('escort', '10', '15', '10', '10', '12', '10', 'Metier de la famille employe, classe beta. Remplace le tirage aleatoire CHA 12-18 / DUP 10-16 / INT 8-14 de confirmerRecrutementEscort.', '0', '800', '800', 'Aucun quota par genre depuis le 1er octobre 2026 : plusieurs escorts par joueur, c''est le game design. Seul subsiste le plafond commun de 10 employes.', 'beta', 'Escort', 'false', NULL, NULL);
INSERT INTO public.pnj_metiers_profils (metier, car_int, car_cha, car_vol, car_per, car_dup, car_ent, note, pa_initial, cout_initial, cout_jour, quota_note, classe, role_libelle, recrutable, quota_par_joueur, ordre_fn) VALUES ('informateur', '10', '10', '8', '15', '12', '8', 'Metier de la famille employe, classe beta. Remplace le tirage aleatoire PER 12-18 de doRecruterInformateurPNJ.', '1', '150', '150', 'Un seul, tous genres confondus. Le plafond commun de 10 n''est pas verifie par le chemin historique -- ecart releve, non corrige ici.', 'beta', 'Informateur', 'true', '1', 'recruter_informateur_pnj');
INSERT INTO public.pnj_metiers_profils (metier, car_int, car_cha, car_vol, car_per, car_dup, car_ent, note, pa_initial, cout_initial, cout_jour, quota_note, classe, role_libelle, recrutable, quota_par_joueur, ordre_fn) VALUES ('maitre_chien', '10', '8', '14', '16', '8', '10', 'Metier de la famille employe, destine a la classe ALPHA (posee sur l''individu a sa creation, pas ici). Maitre-chien de l''agence Grobras Securite, Luthecia. PER 16 et VOL 14 arbitres par le GD le 5 octobre 2026 ; INT/CHA/DUP/ENT recopies du profil policier. Le chien n''est PAS un PNJ : il fait partie du maitre, comme le cynophile de la police (pnj_force_publique_metier.type_unite = ''cynophile'', chien_nom) n''a jamais eu de ligne propre.', '1', '700', '0', 'Quota 2 par joueur (arbitrage GD du 5 octobre 2026). Le chien n''est PAS un PNJ : il fait partie du maitre, comme le cynophile de la police n''a jamais eu de ligne propre. Son nom vit dans l''accroche du candidat.', 'alpha', 'Maître-chien', 'true', '2', 'embaucher_maitre_chien');
INSERT INTO public.pnj_metiers_profils (metier, car_int, car_cha, car_vol, car_per, car_dup, car_ent, note, pa_initial, cout_initial, cout_jour, quota_note, classe, role_libelle, recrutable, quota_par_joueur, ordre_fn) VALUES ('militant', '9', '12', '15', '9', '8', '12', 'Famille militant, classe beta. Profil conserve : le recrutement existe mais sa seule utilite (blocus syndical) est morte en amont.', '2', '0', NULL, 'Deux au maximum, un recrutement par jour. Gratuit a vie : aucun cout recurrent.', NULL, 'Militant', 'false', NULL, NULL);
INSERT INTO public.pnj_metiers_profils (metier, car_int, car_cha, car_vol, car_per, car_dup, car_ent, note, pa_initial, cout_initial, cout_jour, quota_note, classe, role_libelle, recrutable, quota_par_joueur, ordre_fn) VALUES ('policier', '10', '8', '12', '12', '8', '10', 'Metier des effectifs de police, classe beta. Valeurs identiques a celles deja posees au lot 3 : cette ligne devient leur source unique.', '0', '0', NULL, 'Effectifs institutionnels : payes par le cron de minuit sur la caisse du service (50 FR/jour, 100 pour le cynophile), jamais par un joueur.', NULL, 'Policier', 'false', NULL, NULL);
INSERT INTO public.pnj_metiers_profils (metier, car_int, car_cha, car_vol, car_per, car_dup, car_ent, note, pa_initial, cout_initial, cout_jour, quota_note, classe, role_libelle, recrutable, quota_par_joueur, ordre_fn) VALUES ('soldat', '9', '8', '12', '10', '8', '12', 'Famille soldat, classe alpha. Profil arbitre le 27/09/2026 : comble les six caracteristiques qui manquaient aux 96 hommes depuis le lot 1.', '0', '0', NULL, 'Filiere militaire : pas de recrutement individuel paye, pas de paye personnelle.', NULL, 'Soldat', 'false', NULL, NULL);
