-- ETAT INITIAL A CONSTRUIRE -- caisses_batiments
-- ============================================================================
-- Table     : public.caisses_batiments
-- Domaine   : finances publiques
-- Strategie annoncee au chantier 2C : reconstruction_explicite
--
-- CE FICHIER NE CONTIENT AUCUNE DONNEE, ET C'EST VOLONTAIRE.
-- Un TODO explicite vaut mieux qu'un faux etat initial reconstruit depuis la
-- beta. Tant que la decision ci-dessous n'est pas prise, un monde neuf naît
-- sans ces lignes.
--
-- CE QUE L'OBSERVATION ETABLIT
-- 151 caisses. La ligne doit exister au depart, mais le solde est vivant. 14
-- RPC peuvent en creer : une partie des lignes a donc ete engendree en jeu,
-- et rien dans la table ne les distingue des lignes initiales.
--
-- CE QU'IL FAUT DECIDER
-- ARBITRAGE RENDU : les dotations d'amorcage sont definies PAR EMPIRE. Ni
-- constante universelle du moteur, ni soldes de bêta, ni deduction aveugle
-- du journal. PREMIERE VALEUR ARBITREE LE 5 OCTOBRE 2026 : la caisse
-- republic_gouvernement-min_def, budget initial du ministere de la Defense
-- de Republia, vaut 35 000 FR. Le ministre transfere ensuite lui-meme vers
-- la caserne ; la creation d'une compagnie coute 20 000 FR. Les 54 autres
-- caisses de Republia restent a arbitrer. Les valeurs a fixer sont listees,
-- ligne par ligne, dans baseline/arbitrages/dotations-initiales-republia.csv
-- -- un tableau prepare pour etre rempli, qui ne propose aucun montant
-- deduit d'un solde de bêta.
--
-- CE QU'IL NE FAUT PAS FAIRE
-- Ne jamais deduire une dotation initiale d'un solde courant.
-- ============================================================================

-- Rien a appliquer. Ce fichier deviendra un seed le jour ou la decision sera
-- prise et ou les lignes voulues seront ecrites -- a la main ou par un
-- generateur, jamais par une copie de la base de beta.
