-- GRANT sur tables, colonnes et fonctions
-- ============================================================================
-- BASELINE Human Gambit -- domaine socle PNJ -- phase 70 : droits
--
-- Fichier GENERE par outils/baseline/rendre.py depuis les catalogues
-- PostgreSQL. Ne pas editer a la main : toute correction passe par une
-- migration, puis par une nouvelle extraction.
--
-- ORDRE D'APPLICATION : par PHASE croissante, tous domaines confondus, et non
-- domaine par domaine. Voir baseline/README.md.
-- ============================================================================

-- DROITS SUR LES FUNCTIONS
GRANT EXECUTE ON FUNCTION public.pnj_administrateur(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_administrateur(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_argent_transferer(text,numeric,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.pnj_argent_transferer(text,numeric,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_argent_transferer(text,numeric,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_autorite_de(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_autorite_de(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_autorite_de_perimetre(text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_autorite_de_perimetre(text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_axe_au_socle(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_axe_au_socle(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_axe_position_refus(text[]) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_axe_position_refus(text[]) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_axe_verrouille(text[],text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_axe_verrouille(text[],text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_caracteristique_base(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_caracteristique_base(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_caracteristiques_base(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_caracteristiques_base(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_caracteristiques_cles() TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_caracteristiques_cles() TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_classe_de(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_classe_de(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_classe_decor(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_classe_decor(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_co_present(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_co_present(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_comparer_agents() TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_comparer_agents() TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_comparer_douaniers(text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_comparer_douaniers(text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_comparer_policiers(text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_comparer_policiers(text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_comparer_soldats(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_comparer_soldats(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_copier_soldats(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_copier_soldats(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_employe_debaucher(text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.pnj_employe_debaucher(text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_employe_debaucher(text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_evenements_lire(integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.pnj_evenements_lire(integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_evenements_lire(integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_fonction_recrutable(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_fonction_recrutable(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_garde_dissolution_compagnie() TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_garde_dissolution_compagnie() TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_garde_suppression() TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_garde_suppression() TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_membres_ici(text,text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.pnj_membres_ici(text,text,text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_membres_ici(text,text,text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_metier_de(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_metier_de(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_metier_profil(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_metier_profil(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_miroir_compagnie(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_miroir_compagnie(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_miroir_compagnie_trg() TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_miroir_compagnie_trg() TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_miroir_douane(text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_miroir_douane(text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_miroir_douane_declencheur() TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_miroir_douane_declencheur() TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_miroir_police(text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_miroir_police(text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_miroir_police_declencheur() TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_miroir_police_declencheur() TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_miroir_possessions(text,jsonb) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_miroir_possessions(text,jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_miroir_possessions_si_axe_blob(text,jsonb) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_miroir_possessions_si_axe_blob(text,jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_mon_inventaire() TO authenticated;
GRANT EXECUTE ON FUNCTION public.pnj_mon_inventaire() TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_mon_inventaire() TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_mourir(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_mourir(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_mouvement_individuel_refus(text[]) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_mouvement_individuel_refus(text[]) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_objet_transferer(text,integer,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.pnj_objet_transferer(text,integer,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_objet_transferer(text,integer,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_pa_crediter(text[],integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_pa_crediter(text[],integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_pa_debiter(text[],integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_pa_debiter(text[],integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_pa_fixer(text[],integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_pa_fixer(text[],integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_pa_garde(text[]) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_pa_garde(text[]) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_pa_max() TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_pa_max() TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_pas_de_sous_hierarchie() TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_pas_de_sous_hierarchie() TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_peut_administrer(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_peut_administrer(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_peut_conduire(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_peut_conduire(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_position_effective(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_position_effective(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_possessions_lire(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.pnj_possessions_lire(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_possessions_lire(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_prendre(text[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.pnj_prendre(text[]) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_prendre(text[]) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_quitter_groupe(text[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.pnj_quitter_groupe(text[]) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_quitter_groupe(text[]) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_rollback_soldats(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_rollback_soldats(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_social_contexte(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.pnj_social_contexte(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_social_contexte(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_social_entrer(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.pnj_social_entrer(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_social_entrer(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_social_noter(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.pnj_social_noter(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_social_noter(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pnj_transferer(text[],text,boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.pnj_transferer(text[],text,boolean) TO postgres;
GRANT EXECUTE ON FUNCTION public.pnj_transferer(text[],text,boolean) TO service_role;

-- DROITS SUR LES SEQUENCES
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.pnj_evenements_id_seq TO anon;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.pnj_evenements_id_seq TO authenticated;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.pnj_evenements_id_seq TO postgres;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.pnj_evenements_id_seq TO service_role;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.pnj_possessions_id_seq TO anon;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.pnj_possessions_id_seq TO authenticated;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.pnj_possessions_id_seq TO postgres;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.pnj_possessions_id_seq TO service_role;

-- DROITS SUR LES TABLES
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_axes_autorite TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_axes_autorite TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_candidats_catalogue TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_candidats_catalogue TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_employes_metier TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_employes_metier TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_employeurs TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_employeurs TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_evenements TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_evenements TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_familles_classes TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_familles_classes TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_fonctions TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_fonctions TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_force_publique_metier TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_force_publique_metier TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_institutions TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_institutions TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_membres TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_membres TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_metiers_profils TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_metiers_profils TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_militants_metier TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_militants_metier TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_mouvement_individuel TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_mouvement_individuel TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_possessions TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_possessions TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_referents TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_referents TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_referents_pedagogie TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_referents_pedagogie TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_referents_sujets_connus TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_referents_sujets_connus TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_social_escort_choisi TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_social_escort_choisi TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_social_jalons_regles TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_social_jalons_regles TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_social_relations TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_social_relations TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_soldats_metier TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_soldats_metier TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_transitions TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pnj_transitions TO service_role;
