-- GRANT sur tables, colonnes et fonctions
-- ============================================================================
-- BASELINE Human Gambit -- domaine presse -- phase 70 : droits
--
-- Fichier GENERE par outils/baseline/rendre.py depuis les catalogues
-- PostgreSQL. Ne pas editer a la main : toute correction passe par une
-- migration, puis par une nouvelle extraction.
--
-- ORDRE D'APPLICATION : par PHASE croissante, tous domaines confondus, et non
-- domaine par domaine. Voir baseline/README.md.
-- ============================================================================

-- DROITS SUR LES FUNCTIONS
GRANT EXECUTE ON FUNCTION public.calomnie_appliquer_effet(text,integer,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.calomnie_appliquer_effet(text,integer,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.calomnie_distribuer(text,text,text,text,integer) TO anon;
GRANT EXECUTE ON FUNCTION public.calomnie_distribuer(text,text,text,text,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.calomnie_distribuer(text,text,text,text,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.calomnie_distribuer(text,text,text,text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.calomnie_distribuer_interne(text,text,text,text,integer,timestamp with time zone) TO postgres;
GRANT EXECUTE ON FUNCTION public.calomnie_distribuer_interne(text,text,text,text,integer,timestamp with time zone) TO service_role;
GRANT EXECUTE ON FUNCTION public.calomnie_inscrire_mandat(text,text,text,text,timestamp with time zone) TO postgres;
GRANT EXECUTE ON FUNCTION public.calomnie_inscrire_mandat(text,text,text,text,timestamp with time zone) TO service_role;
GRANT EXECUTE ON FUNCTION public.corruption_presse_affaires(text,timestamp with time zone) TO anon;
GRANT EXECUTE ON FUNCTION public.corruption_presse_affaires(text,timestamp with time zone) TO authenticated;
GRANT EXECUTE ON FUNCTION public.corruption_presse_affaires(text,timestamp with time zone) TO postgres;
GRANT EXECUTE ON FUNCTION public.corruption_presse_affaires(text,timestamp with time zone) TO service_role;
GRANT EXECUTE ON FUNCTION public.corruption_presse_etat(text) TO anon;
GRANT EXECUTE ON FUNCTION public.corruption_presse_etat(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.corruption_presse_etat(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.corruption_presse_etat(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.corruption_presse_tenter(text,text,text,text,integer,timestamp with time zone) TO authenticated;
GRANT EXECUTE ON FUNCTION public.corruption_presse_tenter(text,text,text,text,integer,timestamp with time zone) TO postgres;
GRANT EXECUTE ON FUNCTION public.corruption_presse_tenter(text,text,text,text,integer,timestamp with time zone) TO service_role;
GRANT EXECUTE ON FUNCTION public.fuite_publier(bigint,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fuite_publier(bigint,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.fuite_publier(bigint,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.fuite_reserver(text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fuite_reserver(text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.fuite_reserver(text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.fuite_traces_eligibles(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.fuite_traces_eligibles(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.imprimerie_cession_finaliser(text,text,text,numeric,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.imprimerie_cession_finaliser(text,text,text,numeric,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.imprimerie_cession_finaliser(text,text,text,numeric,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.imprimerie_produire_tracts(text,text,text,text,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.imprimerie_produire_tracts(text,text,text,text,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.imprimerie_produire_tracts(text,text,text,text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.journal_edition_lire(text) TO anon;
GRANT EXECUTE ON FUNCTION public.journal_edition_lire(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.journal_edition_lire(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.journal_edition_lire(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.journal_edition_rattacher_au_titre() TO postgres;
GRANT EXECUTE ON FUNCTION public.journal_edition_rattacher_au_titre() TO service_role;
GRANT EXECUTE ON FUNCTION public.presse_acteur_directeur(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.presse_acteur_directeur(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.presse_delegation_accorder(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.presse_delegation_accorder(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.presse_delegation_accorder(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.presse_delegation_retirer(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.presse_delegation_retirer(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.presse_delegation_retirer(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.presse_delegations_purger() TO postgres;
GRANT EXECUTE ON FUNCTION public.presse_delegations_purger() TO service_role;
GRANT EXECUTE ON FUNCTION public.presse_designer_successeur(text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.presse_designer_successeur(text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.presse_designer_successeur(text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.presse_directeur_du_journal(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.presse_directeur_du_journal(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.presse_groupe_fonder(text,text,text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.presse_groupe_fonder(text,text,text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.presse_journal_creer(text,text,text,text,text,boolean) TO postgres;
GRANT EXECUTE ON FUNCTION public.presse_journal_creer(text,text,text,text,text,boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.presse_nommer_redacteur_chef(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.presse_nommer_redacteur_chef(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.presse_nommer_redacteur_chef(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.presse_quitter(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.presse_quitter(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.presse_quitter(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.presse_recruter(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.presse_recruter(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.presse_recruter(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.presse_succession_apres_depart() TO postgres;
GRANT EXECUTE ON FUNCTION public.presse_succession_apres_depart() TO service_role;
GRANT EXECUTE ON FUNCTION public.scandale_publier(bigint,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.scandale_publier(bigint,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.scandale_publier(bigint,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.scandale_taux(text,jsonb,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.scandale_taux(text,jsonb,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.scandale_tenter(text,text,text,text,integer,timestamp with time zone) TO authenticated;
GRANT EXECUTE ON FUNCTION public.scandale_tenter(text,text,text,text,integer,timestamp with time zone) TO postgres;
GRANT EXECUTE ON FUNCTION public.scandale_tenter(text,text,text,text,integer,timestamp with time zone) TO service_role;
GRANT EXECUTE ON FUNCTION public.tracts_appliquer_effet_pop(text,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.tracts_appliquer_effet_pop(text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.tracts_donner_joueur(text,text,text,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tracts_donner_joueur(text,text,text,jsonb) TO postgres;
GRANT EXECUTE ON FUNCTION public.tracts_donner_joueur(text,text,text,jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.tracts_electoraux_distribuer(text,text,text,text,text,text,integer) TO anon;
GRANT EXECUTE ON FUNCTION public.tracts_electoraux_distribuer(text,text,text,text,text,text,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tracts_electoraux_distribuer(text,text,text,text,text,text,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.tracts_electoraux_distribuer(text,text,text,text,text,text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.tracts_electoraux_distribuer_interne(text,text,text,text,text,text,integer,timestamp with time zone) TO postgres;
GRANT EXECUTE ON FUNCTION public.tracts_electoraux_distribuer_interne(text,text,text,text,text,text,integer,timestamp with time zone) TO service_role;
GRANT EXECUTE ON FUNCTION public.tracts_electoraux_nom_pnj(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.tracts_electoraux_nom_pnj(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.tracts_electoraux_taux(numeric,numeric,numeric) TO anon;
GRANT EXECUTE ON FUNCTION public.tracts_electoraux_taux(numeric,numeric,numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tracts_electoraux_taux(numeric,numeric,numeric) TO postgres;
GRANT EXECUTE ON FUNCTION public.tracts_electoraux_taux(numeric,numeric,numeric) TO service_role;
GRANT EXECUTE ON FUNCTION public.tracts_reclamer_don(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tracts_reclamer_don(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.tracts_reclamer_don(text,text) TO service_role;

-- DROITS SUR LES SEQUENCES
GRANT SELECT, USAGE ON SEQUENCE public.calomnies_actes_id_seq TO anon;
GRANT SELECT, USAGE ON SEQUENCE public.calomnies_actes_id_seq TO authenticated;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.calomnies_actes_id_seq TO postgres;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.calomnies_actes_id_seq TO service_role;
GRANT SELECT, USAGE ON SEQUENCE public.corruptions_presse_id_seq TO anon;
GRANT SELECT, USAGE ON SEQUENCE public.corruptions_presse_id_seq TO authenticated;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.corruptions_presse_id_seq TO postgres;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.corruptions_presse_id_seq TO service_role;
GRANT SELECT, USAGE ON SEQUENCE public.fuites_journalistiques_id_seq TO anon;
GRANT SELECT, USAGE ON SEQUENCE public.fuites_journalistiques_id_seq TO authenticated;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.fuites_journalistiques_id_seq TO postgres;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.fuites_journalistiques_id_seq TO service_role;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.presse_membres_rang_seq TO postgres;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.presse_membres_rang_seq TO service_role;
GRANT SELECT, USAGE ON SEQUENCE public.scandales_presse_id_seq TO anon;
GRANT SELECT, USAGE ON SEQUENCE public.scandales_presse_id_seq TO authenticated;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.scandales_presse_id_seq TO postgres;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.scandales_presse_id_seq TO service_role;

-- DROITS SUR LES TABLES
GRANT SELECT ON TABLE public.calomnies_actes TO anon;
GRANT SELECT ON TABLE public.calomnies_actes TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.calomnies_actes TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.calomnies_actes TO service_role;
GRANT SELECT ON TABLE public.chronique_nationale TO anon;
GRANT INSERT, SELECT ON TABLE public.chronique_nationale TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.chronique_nationale TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.chronique_nationale TO service_role;
GRANT SELECT ON TABLE public.corruptions_presse TO anon;
GRANT SELECT ON TABLE public.corruptions_presse TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.corruptions_presse TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.corruptions_presse TO service_role;
GRANT SELECT ON TABLE public.fuites_journalistiques TO anon;
GRANT SELECT ON TABLE public.fuites_journalistiques TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.fuites_journalistiques TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.fuites_journalistiques TO service_role;
GRANT SELECT ON TABLE public.groupes_presse TO anon;
GRANT SELECT ON TABLE public.groupes_presse TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.groupes_presse TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.groupes_presse TO service_role;
GRANT SELECT ON TABLE public.interviews_jodie TO anon;
GRANT SELECT ON TABLE public.interviews_jodie TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.interviews_jodie TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.interviews_jodie TO service_role;
GRANT SELECT ON TABLE public.journal_articles_en_attente TO anon;
GRANT SELECT ON TABLE public.journal_articles_en_attente TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.journal_articles_en_attente TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.journal_articles_en_attente TO service_role;
GRANT SELECT ON TABLE public.journal_editions TO anon;
GRANT SELECT ON TABLE public.journal_editions TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.journal_editions TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.journal_editions TO service_role;
GRANT SELECT ON TABLE public.journaux TO anon;
GRANT SELECT ON TABLE public.journaux TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.journaux TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.journaux TO service_role;
GRANT SELECT ON TABLE public.journaux_redacteurs TO anon;
GRANT SELECT ON TABLE public.journaux_redacteurs TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.journaux_redacteurs TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.journaux_redacteurs TO service_role;
GRANT SELECT ON TABLE public.petites_annonces TO anon;
GRANT INSERT, SELECT, UPDATE ON TABLE public.petites_annonces TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.petites_annonces TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.petites_annonces TO service_role;
GRANT SELECT ON TABLE public.presse_membres TO anon;
GRANT SELECT ON TABLE public.presse_membres TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.presse_membres TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.presse_membres TO service_role;
GRANT SELECT ON TABLE public.scandales_presse TO anon;
GRANT SELECT ON TABLE public.scandales_presse TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.scandales_presse TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.scandales_presse TO service_role;
GRANT SELECT ON TABLE public.scandales_tentatives TO anon;
GRANT SELECT ON TABLE public.scandales_tentatives TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.scandales_tentatives TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.scandales_tentatives TO service_role;
GRANT SELECT ON TABLE public.tribune_articles_etouffes TO anon;
GRANT INSERT, SELECT ON TABLE public.tribune_articles_etouffes TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.tribune_articles_etouffes TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.tribune_articles_etouffes TO service_role;
