#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Transforme un export JSON des catalogues en fichiers SQL lisibles du baseline.

Entree  : un repertoire contenant les fichiers export_*.json produits par les
          requetes de requetes.py (voir le README : l'extraction se fait en deux
          temps, l'assistant executant le SQL via MCP).
Sortie  : baseline/domaines/<domaine>/<phase>_<categorie>.sql + MANIFESTE.json

PHASES. Les fichiers sont numerotes par PHASE de reconstruction, pas par domaine.
Au moment d'assembler le baseline complet, on applique la phase 10 de TOUS les
domaines, puis la phase 20 de tous, et ainsi de suite -- jamais un domaine
entier d'un coup. C'est ce qui permet qu'une cle etrangere ou une policy d'un
domaine pointe vers un objet d'un autre sans imposer d'ordre entre domaines.

    10 tables       (colonnes, defauts, identites/serials -- sans contraintes)
    20 fonctions    (creables dans n'importe quel ordre : corps plpgsql/sql non
                     valides a la creation, aucun cycle constate)
    30 contraintes  (PK, UNIQUE, CHECK puis FK)
    35 index        (uniquement les index autonomes : ceux portes par une
                     contrainte sont recrees par la contrainte)
    40 vues
    50 triggers     (exigent leur fonction et leur table)
    60 rls          (activation, puis policies -- exigent leurs fonctions)
    70 droits       (GRANT table, colonne et fonction)
    80 commentaires

Usage :
    python3 outils/baseline/rendre.py <domaine> <repertoire_export>

Cet outil n'accede pas a la base. Il lit du JSON et ecrit des fichiers.
"""

import glob
import hashlib
import json
import os
import sys

ICI = os.path.dirname(os.path.abspath(__file__))
RACINE = os.path.dirname(os.path.dirname(ICI))
DOMAINES = os.path.join(ICI, "domaines.json")

ENTETE = """-- {titre}
-- ============================================================================
-- BASELINE Human Gambit -- domaine {domaine} -- phase {phase} : {categorie}
--
-- Fichier GENERE par outils/baseline/rendre.py depuis les catalogues
-- PostgreSQL. Ne pas editer a la main : toute correction doit passer par une
-- migration, puis par une nouvelle extraction.
--
-- ORDRE D'APPLICATION : par PHASE croissante, tous domaines confondus, et non
-- domaine par domaine. Voir baseline/README.md.
-- ============================================================================

"""

SERIALS = {"bigint": "bigserial", "integer": "serial", "smallint": "smallserial"}


def titre(txt):
    return txt


def rendre_colonne(col, sequences_par_colonne):
    """Rend une ligne de definition de colonne.

    Regle du serial : si le defaut est nextval() sur une sequence POSSEDEE par
    cette colonne (pg_depend deptype='a'), on ecrit `bigserial` plutot que
    `bigint DEFAULT nextval(...)`. C'est stricement equivalent -- PostgreSQL
    recree la sequence, le defaut et le lien de propriete -- et c'est lisible.
    Une sequence autonome, elle, serait emise separement.
    """
    nom, typ = col["attname"], col["type"]
    defaut = col.get("defaut")
    morceaux = [nom]
    cle = (col["tbl"], nom)
    if defaut and defaut.startswith("nextval(") and cle in sequences_par_colonne and typ in SERIALS:
        morceaux.append(SERIALS[typ])
    else:
        morceaux.append(typ)
        if col.get("identity") == "a":
            morceaux.append("GENERATED ALWAYS AS IDENTITY")
        elif col.get("identity") == "d":
            morceaux.append("GENERATED BY DEFAULT AS IDENTITY")
        elif defaut:
            morceaux.append("DEFAULT " + defaut)
    if col.get("non_nul"):
        morceaux.append("NOT NULL")
    if col.get("collation"):
        morceaux.insert(2, 'COLLATE "%s"' % col["collation"])
    return " ".join(morceaux)


def phase_tables(exp, manifeste):
    seq_par_col = {(s["tbl"], s["colonne"]): s["sequence"]
                   for s in exp.get("sequences", []) if s.get("lien") == "a"}
    par_table = {}
    for c in exp["colonnes"]:
        par_table.setdefault(c["tbl"], []).append(c)
    out = []
    for tbl in sorted(par_table):
        cols = sorted(par_table[tbl], key=lambda c: c["attnum"])
        lignes = [rendre_colonne(c, seq_par_col) for c in cols]
        out.append("CREATE TABLE public.%s (\n  %s\n);" % (tbl, ",\n  ".join(lignes)))
        manifeste["tables"].append({"nom": tbl, "colonnes": len(cols)})
    autonomes = [s for s in exp.get("sequences", []) if s.get("lien") != "a"]
    if autonomes:
        out.append("\n-- Sequences autonomes (non possedees par une colonne)")
        for s in autonomes:
            out.append("CREATE SEQUENCE public.%s;" % s["sequence"])
    return "\n\n".join(out) + "\n"


def phase_fonctions(exp, manifeste):
    out = []
    for f in sorted(exp["fonctions"], key=lambda x: x["signature"]):
        out.append("-- %s -> %s | %s | %s%s"
                   % (f["signature"], f["retour"], f["langage"],
                      "SECURITY DEFINER" if f["security_definer"] else "SECURITY INVOKER",
                      (" | " + ", ".join(f["configuration"])) if f.get("configuration") else ""))
        out.append(f["definition"].rstrip() + "\n")
        manifeste["fonctions"].append({"signature": f["signature"], "empreinte": f["empreinte"],
                                       "security_definer": f["security_definer"]})
    return "\n".join(out)


def phase_contraintes(exp, manifeste):
    ordre = {"p": 1, "u": 2, "c": 3, "f": 4}
    out, courant = [], None
    for k in sorted(exp["contraintes"], key=lambda x: (ordre.get(x["genre"], 9), x["tbl"], x["nom"])):
        genre = {"p": "cles primaires", "u": "contraintes d'unicite",
                 "c": "contraintes de validation", "f": "cles etrangeres"}.get(k["genre"], k["genre"])
        if genre != courant:
            out.append("\n-- %s" % genre.upper())
            courant = genre
        out.append("ALTER TABLE public.%s ADD CONSTRAINT %s %s;" % (k["tbl"], k["nom"], k["definition"]))
        manifeste["contraintes"].append({"tbl": k["tbl"], "nom": k["nom"],
                                         "genre": k["genre"], "empreinte": k["empreinte"]})
    return "\n".join(out).lstrip() + "\n"


def phase_index(exp, manifeste):
    out = []
    portes = [i for i in exp["index"] if i.get("contrainte")]
    autonomes = [i for i in exp["index"] if not i.get("contrainte")]
    out.append("-- %d index sont portes par une contrainte et NE SONT PAS recrees ici :"
               % len(portes))
    for i in sorted(portes, key=lambda x: x["nom"]):
        out.append("--   %s  (contrainte %s)" % (i["nom"], i["contrainte"]))
    out.append("")
    if autonomes:
        out.append("-- Index autonomes :")
        for i in sorted(autonomes, key=lambda x: x["nom"]):
            out.append(i["definition"] + ";")
            manifeste["index_autonomes"].append({"nom": i["nom"], "empreinte": i["empreinte"]})
    else:
        out.append("-- Aucun index autonome dans ce domaine.")
    return "\n".join(out) + "\n"


def phase_triggers(exp, manifeste):
    out = []
    for t in sorted(exp["triggers"], key=lambda x: (x["tbl"], x["nom"])):
        out.append(t["definition"] + ";")
        if t.get("actif") != "O":
            out.append("ALTER TABLE public.%s DISABLE TRIGGER %s;" % (t["tbl"], t["nom"]))
        manifeste["triggers"].append({"tbl": t["tbl"], "nom": t["nom"],
                                      "fonction": t["fonction"], "empreinte": t["empreinte"]})
    return "\n".join(out) + "\n"


def phase_rls(exp, manifeste):
    out = ["-- Activation de la RLS. Une table dont la RLS est active SANS policy est",
           "-- fermee a tout role soumis a la RLS : c'est un etat VOULU, pas un oubli.", ""]
    for r in sorted(exp["rls"], key=lambda x: x["tbl"]):
        if r["active"]:
            out.append("ALTER TABLE public.%s ENABLE ROW LEVEL SECURITY;" % r["tbl"])
        if r.get("forcee"):
            out.append("ALTER TABLE public.%s FORCE ROW LEVEL SECURITY;" % r["tbl"])
        manifeste["rls"].append({"tbl": r["tbl"], "active": r["active"], "forcee": r.get("forcee")})
    out.append("")
    courant = None
    for p in sorted(exp["policies"], key=lambda x: (x["tbl"], x["nom"])):
        if p["tbl"] != courant:
            out.append("\n-- %s" % p["tbl"])
            courant = p["tbl"]
        out.append(p["definition"])
        manifeste["policies"].append({"tbl": p["tbl"], "nom": p["nom"], "empreinte": p["empreinte"]})
    return "\n".join(out) + "\n"


def phase_droits(exp, manifeste):
    out, courant = [], None
    for d in sorted(exp["droits"], key=lambda x: (x["genre"], x["objet"], x["beneficiaire"])):
        if d["genre"] != courant:
            out.append("\n-- DROITS SUR LES %sS" % d["genre"])
            courant = d["genre"]
        cible = ("public." + d["objet"]) if d["genre"] == "TABLE" else ("public." + d["objet"])
        out.append("GRANT %s ON %s %s TO %s;"
                   % (d["privileges"], d["genre"], cible, d["beneficiaire"]))
        manifeste["droits"].append({"genre": d["genre"], "objet": d["objet"],
                                    "beneficiaire": d["beneficiaire"], "privileges": d["privileges"]})
    for d in exp.get("droits_colonnes", []):
        out.append("-- DROIT AU NIVEAU COLONNE : invisible dans relacl, a ne jamais oublier")
        out.append("GRANT %s (%s) ON TABLE public.%s TO %s;"
                   % (d["privileges"], d["colonne"], d["tbl"], d["beneficiaire"]))
        manifeste["droits_colonnes"].append(d)
    return "\n".join(out).lstrip() + "\n"


def phase_commentaires(exp, manifeste):
    if not exp.get("commentaires"):
        return "-- Aucun commentaire d'objet dans ce domaine.\n"
    out = []
    for c in sorted(exp["commentaires"], key=lambda x: (x["genre"], x["objet"], x.get("colonne") or "")):
        texte = c["texte"].replace("'", "''")
        if c["genre"] == "TABLE":
            cible = "TABLE public." + c["objet"]
        elif c["genre"] == "COLUMN":
            cible = "COLUMN public.%s.%s" % (c["objet"], c["colonne"])
        elif c["genre"] == "FUNCTION":
            cible = "FUNCTION public." + c["objet"]
        else:
            cible = "CONSTRAINT %s ON public.%s" % (c["colonne"], c["objet"])
        out.append("COMMENT ON %s IS '%s';" % (cible, texte))
        manifeste["commentaires"].append({"genre": c["genre"], "objet": c["objet"]})
    return "\n".join(out) + "\n"


PHASES = [
    (10, "tables", "Tables, colonnes, defauts et identites", phase_tables),
    (20, "fonctions", "Fonctions et procedures stockees", phase_fonctions),
    (30, "contraintes", "Cles primaires, unicite, validation, cles etrangeres", phase_contraintes),
    (35, "index", "Index autonomes", phase_index),
    (50, "triggers", "Declencheurs", phase_triggers),
    (60, "rls-policies", "Activation RLS et policies", phase_rls),
    (70, "droits", "GRANT sur tables, colonnes et fonctions", phase_droits),
    (80, "commentaires", "Commentaires d'objets", phase_commentaires),
]


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        return 2
    domaine, rep = sys.argv[1], sys.argv[2]
    conf = json.load(open(DOMAINES, encoding="utf-8"))[domaine]

    exp = {}
    for f in sorted(glob.glob(os.path.join(rep, "export_*.json"))):
        exp.update(json.load(open(f, encoding="utf-8")))
    manquants = [c for c in ("colonnes", "fonctions", "contraintes", "index",
                             "triggers", "rls", "policies", "droits") if c not in exp]
    if manquants:
        raise SystemExit("export incomplet, categories manquantes : " + ", ".join(manquants))

    cible = os.path.join(RACINE, "baseline", "domaines", domaine)
    os.makedirs(cible, exist_ok=True)

    manifeste = {"domaine": domaine, "libelle": conf["libelle"],
                 "tables": [], "fonctions": [], "contraintes": [], "index_autonomes": [],
                 "triggers": [], "rls": [], "policies": [], "droits": [],
                 "droits_colonnes": [], "commentaires": [], "fichiers": {}}

    for num, cat, lib, fonc in PHASES:
        corps = fonc(exp, manifeste)
        nom = "%02d_%s.sql" % (num, cat)
        contenu = ENTETE.format(titre=lib, domaine=domaine, phase=num, categorie=cat) + corps
        with open(os.path.join(cible, nom), "w", encoding="utf-8", newline="") as fh:
            fh.write(contenu)
        manifeste["fichiers"][nom] = hashlib.md5(contenu.encode("utf-8")).hexdigest()
        print("  %-24s %6d octets" % (nom, len(contenu.encode("utf-8"))))

    manifeste["dependances_externes"] = conf["dependances_externes"]
    with open(os.path.join(cible, "MANIFESTE.json"), "w", encoding="utf-8") as fh:
        json.dump(manifeste, fh, indent=1, ensure_ascii=False, sort_keys=True)
    print("  MANIFESTE.json")
    print("\nObjets rendus : %d tables, %d fonctions, %d contraintes, %d index autonomes,"
          " %d triggers, %d policies, %d lignes de droits"
          % (len(manifeste["tables"]), len(manifeste["fonctions"]), len(manifeste["contraintes"]),
             len(manifeste["index_autonomes"]), len(manifeste["triggers"]),
             len(manifeste["policies"]), len(manifeste["droits"])))
    return 0


if __name__ == "__main__":
    sys.exit(main())
