-- GRANT sur tables, colonnes et fonctions
-- ============================================================================
-- BASELINE Human Gambit -- domaine militaire -- phase 70 : droits
--
-- Fichier GENERE par outils/baseline/rendre.py depuis les catalogues
-- PostgreSQL. Ne pas editer a la main : toute correction passe par une
-- migration, puis par une nouvelle extraction.
--
-- ORDRE D'APPLICATION : par PHASE croissante, tous domaines confondus, et non
-- domaine par domaine. Voir baseline/README.md.
-- ============================================================================

-- DROITS SUR LES FUNCTIONS
GRANT EXECUTE ON FUNCTION public.camion_batiment_interieur() TO authenticated;
GRANT EXECUTE ON FUNCTION public.camion_batiment_interieur() TO postgres;
GRANT EXECUTE ON FUNCTION public.camion_batiment_interieur() TO service_role;
GRANT EXECUTE ON FUNCTION public.camion_deplacer(text,text,boolean,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.camion_deplacer(text,text,boolean,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.camion_deplacer(text,text,boolean,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.camion_descendre(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.camion_descendre(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.camion_descendre(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.camion_destinations(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.camion_destinations(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.camion_etat(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.camion_etat(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.camion_etat(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.camion_grade_commandant(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.camion_grade_commandant(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.camion_monter(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.camion_monter(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.camion_monter(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.camion_occupants(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.camion_occupants(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.camions_ici(text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.camions_ici(text,text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.camions_ici(text,text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.caserne_reverser_au_ministere(numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.caserne_reverser_au_ministere(numeric) TO postgres;
GRANT EXECUTE ON FUNCTION public.caserne_reverser_au_ministere(numeric) TO service_role;
GRANT EXECUTE ON FUNCTION public.caserne_stock_mouvement(text,text,integer,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.caserne_stock_mouvement(text,text,integer,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.caserne_virement_journalier_fixer(integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.caserne_virement_journalier_fixer(integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.caserne_virement_journalier_fixer(integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.effort_commande_annuler(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.effort_commande_annuler(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.effort_commande_annuler(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.effort_commande_creer(text,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.effort_commande_creer(text,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.effort_commande_creer(text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.effort_produire_lot(text,text,text,jsonb,jsonb,numeric,text,text,text,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.effort_produire_lot(text,text,text,jsonb,jsonb,numeric,text,text,text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.effort_ravitailler(text,jsonb,jsonb,jsonb) TO postgres;
GRANT EXECUTE ON FUNCTION public.effort_ravitailler(text,jsonb,jsonb,jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.effort_reserve_appliquer(text,jsonb,text[],numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.effort_reserve_appliquer(text,jsonb,text[],numeric) TO postgres;
GRANT EXECUTE ON FUNCTION public.effort_reserve_appliquer(text,jsonb,text[],numeric) TO service_role;
GRANT EXECUTE ON FUNCTION public.guerre_acteur_poste(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.guerre_acteur_poste(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.guerre_acteur_poste(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.guerre_cessez_le_feu_activer(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.guerre_cessez_le_feu_activer(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.guerre_cessez_le_feu_activer(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.guerre_declarer(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.guerre_declarer(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.guerre_declarer(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.guerre_treve_proposer(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.guerre_treve_proposer(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.guerre_treve_proposer(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.guerre_treve_repondre(text,boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.guerre_treve_repondre(text,boolean) TO postgres;
GRANT EXECUTE ON FUNCTION public.guerre_treve_repondre(text,boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_accepter_capitaine(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_accepter_capitaine(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_accepter_capitaine(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_accepter_lieutenant(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_accepter_lieutenant(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_accepter_lieutenant(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_accessoires_section(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_accessoires_section(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_accessoires_section(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_affectation_decouvrir() TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_affectation_decouvrir() TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_affectation_decouvrir() TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_affectations_expirer() TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_affectations_expirer() TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_affecter_leader(text,text,integer,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_affecter_leader(text,text,integer,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_affecter_leader(text,text,integer,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_arme_operationnelle(text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.militaire_arme_operationnelle(text) TO anon;
GRANT EXECUTE ON FUNCTION public.militaire_arme_operationnelle(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_arme_operationnelle(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_arme_operationnelle(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_arme_recalculer(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_arme_recalculer(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_arme_recalculer(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_armurerie_transfert(text,text,text,integer,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_armurerie_transfert(text,text,text,integer,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_armurerie_transfert(text,text,text,integer,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_assigner_mission(text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_assigner_mission(text,text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_assigner_mission(text,text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_autorite_de_perimetre(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_autorite_de_perimetre(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_bande_distance(text,text,text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_bande_distance(text,text,text,text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_bande_distance(text,text,text,text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_actions(bigint,text,integer,boolean) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_actions(bigint,text,integer,boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_appliquer(bigint,jsonb,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_appliquer(bigint,jsonb,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_arbitrer_groupes(bigint,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_arbitrer_groupes(bigint,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_avancer(bigint) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_avancer(bigint) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_combattants(bigint,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_combattants(bigint,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_decider(bigint,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_decider(bigint,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_decider(bigint,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_decision_effective(bigint,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_decision_effective(bigint,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_decrocher_groupe(bigint,text,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_decrocher_groupe(bigint,text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_doctrine(bigint,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_doctrine(bigint,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_doctrine(bigint,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_engager() TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_engager() TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_engager() TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_etat(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_etat(bigint) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_etat(bigint) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_groupes_constituer(bigint) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_groupes_constituer(bigint) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_mon_camp(bigint,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_mon_camp(bigint,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_poursuivre(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_poursuivre(bigint) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_poursuivre(bigint) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_rapport(bigint,text,text,integer,jsonb,integer,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_rapport(bigint,text,text,integer,jsonb,integer,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_recruter(bigint,text,text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_recruter(bigint,text,text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_round(bigint) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_bataille_round(bigint) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_blob_projeter(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_blob_projeter(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_bonus_arme(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_bonus_arme(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_calepin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_calepin() TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_calepin() TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_camouflage_groupe(numeric,integer,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_camouflage_groupe(numeric,integer,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_camouflage_groupe(numeric,integer,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_camps_hostiles(bigint,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_camps_hostiles(bigint,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_candidater_soldat(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_candidater_soldat(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_candidater_soldat(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_candidature_accepter(text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_candidature_accepter(text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_candidature_accepter(text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_candidature_deposer(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_candidature_deposer(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_candidature_deposer(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_candidature_refuser(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_candidature_refuser(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_candidature_refuser(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_candidature_retirer(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_candidature_retirer(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_candidature_retirer(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_candidature_traiter(text,boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_candidature_traiter(text,boolean) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_candidature_traiter(text,boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_candidatures_a_traiter() TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_candidatures_a_traiter() TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_candidatures_a_traiter() TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_candidatures_relancer() TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_candidatures_relancer() TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_chance_detection(numeric,numeric,integer,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_chance_detection(numeric,numeric,integer,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_chance_detection(numeric,numeric,integer,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_compagnie_creer() TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_compagnie_creer() TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_compagnie_creer() TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_compagnies_lisibles() TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_compagnies_lisibles() TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_compagnies_lisibles() TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_competences(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_competences(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_competences(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_decorer(text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_decorer(text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_decorer(text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_defense_pnj(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_defense_pnj(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_degats_pct(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_degats_pct(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_degrader(text,integer,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_degrader(text,integer,text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_degrader(text,integer,text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_degre_combat(integer,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_degre_combat(integer,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_degre_par_rang(integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_degre_par_rang(integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_degre_rang(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_degre_rang(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_demettre_lieutenant(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_demettre_lieutenant(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_demettre_lieutenant(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_deposer_soldats(text,text,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_deposer_soldats(text,text,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_deposer_soldats(text,text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_desertions_verifier(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_desertions_verifier(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_desertions_verifier(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_detachement_ici() TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_detachement_ici() TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_detachement_ici() TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_engagement_affecter_compagnie(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_engagement_affecter_compagnie(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_engagement_affecter_compagnie(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_engagement_affecter_section(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_engagement_affecter_section(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_engagement_affecter_section(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_engagement_creer() TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_engagement_creer() TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_engagement_creer() TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_entrainer_section(text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_entrainer_section(text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_entrainer_section(text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_entree_zone() TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_entree_zone() TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_entree_zone() TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_equiper_accessoire(text,text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_equiper_accessoire(text,text,text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_equiper_accessoire(text,text,text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_equiper_soldat(text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_equiper_soldat(text,text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_equiper_soldat(text,text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_gilet_absorber(boolean,text,text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_gilet_absorber(boolean,text,text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_grade_effectif(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_grade_effectif(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_grade_effectif(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_groupe_sous_seuil(bigint,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_groupe_sous_seuil(bigint,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_inspection_perimetre() TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_inspection_perimetre() TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_inspection_perimetre() TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_lien_operationnel_rompre(text,text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_lien_operationnel_rompre(text,text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_ma_section() TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_ma_section() TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_malus_taille(integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_malus_taille(integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_malus_taille(integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_mes_batailles(integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_mes_batailles(integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_mes_batailles(integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_mes_candidatures() TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_mes_candidatures() TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_mes_candidatures() TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_mobilisation_fixer(boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_mobilisation_fixer(boolean) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_mobilisation_fixer(boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_modif_distance(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_modif_distance(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_modif_distance(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_mon_pays() TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_mon_pays() TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_mon_pays() TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_mutinerie_declencher() TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_mutinerie_declencher() TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_mutinerie_declencher() TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_objet_signature(jsonb) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.militaire_objet_signature(jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.militaire_objet_signature(jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_objet_signature(jsonb) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_objet_signature(jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_observer() TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_observer() TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_observer() TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_ordre_collectif(text,text,text,text,text[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_ordre_collectif(text,text,text,text,text[]) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_ordre_collectif(text,text,text,text,text[]) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_ordre_pnj(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_ordre_pnj(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_ordre_pnj(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_pa_restants(integer,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_pa_restants(integer,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_places_libres_grade(text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_places_libres_grade(text,text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_places_libres_grade(text,text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_position_repli(text,text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_position_repli(text,text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_presentation_affectation() TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_presentation_affectation() TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_presentation_affectation() TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_proposer_capitaine(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_proposer_capitaine(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_proposer_capitaine(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_proposer_lieutenant(text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_proposer_lieutenant(text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_proposer_lieutenant(text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_ration_consommer() TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_ration_consommer() TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_ration_consommer() TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_rations_retirer(integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_rations_retirer(integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_rations_retirer(integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_recruteur_de_moi() TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_recruteur_de_moi() TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_recuperer_soldats(text,text,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_recuperer_soldats(text,text,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_recuperer_soldats(text,text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_reposer_section(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_reposer_section(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_reposer_section(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_requisition_civile(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_requisition_civile(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_requisition_civile(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_retrait(text,text,integer,text,text,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_retrait(text,text,integer,text,text,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_retrait(text,text,integer,text,text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_section_de_moi(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_section_de_moi(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_sections_remplacer(jsonb,text,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_sections_remplacer(jsonb,text,jsonb) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_sections_remplacer(jsonb,text,jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_service_fermer(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_service_fermer(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_service_jours(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_service_jours(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_service_jours(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_service_ouvrir(text,text,text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_service_ouvrir(text,text,text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_soldat_pa_fixer(text,text,text,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_soldat_pa_fixer(text,text,text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_soldat_retirer(text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_soldat_retirer(text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_soldat_retirer(text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_soldat_supprimer(text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_soldat_supprimer(text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_solde_percevoir() TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_solde_percevoir() TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_solde_percevoir() TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_subtiliser(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_subtiliser(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_subtiliser_tenter(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_subtiliser_tenter(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_subtiliser_tenter(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_taux_combat(numeric,numeric,numeric,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_taux_combat(numeric,numeric,numeric,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_terminal_dormir(text,text[],text[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_terminal_dormir(text,text[],text[]) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_terminal_dormir(text,text[],text[]) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_terminal_liaison(text,text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.militaire_terminal_liaison(text,text) TO anon;
GRANT EXECUTE ON FUNCTION public.militaire_terminal_liaison(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_terminal_liaison(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_terminal_liaison(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_terminal_manger(text,text[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_terminal_manger(text,text[]) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_terminal_manger(text,text[]) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_terminal_rejoindre(text,text[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_terminal_rejoindre(text,text[]) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_terminal_rejoindre(text,text[]) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_terminal_section() TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_terminal_section() TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_terminal_section() TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_terminal_transferer(text,text,text,integer,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_terminal_transferer(text,text,text,integer,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_terminal_transferer(text,text,text,integer,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_trousse_retirer() TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_trousse_retirer() TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_trousse_retirer() TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_trousse_utiliser(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_trousse_utiliser(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_trousse_utiliser(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.militaire_unites_objet(jsonb) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.militaire_unites_objet(jsonb) TO anon;
GRANT EXECUTE ON FUNCTION public.militaire_unites_objet(jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.militaire_unites_objet(jsonb) TO postgres;
GRANT EXECUTE ON FUNCTION public.militaire_unites_objet(jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.mutinerie_camp_de(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mutinerie_camp_de(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.mutinerie_camp_de(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.mutinerie_camps_presents(text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mutinerie_camps_presents(text,text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.mutinerie_camps_presents(text,text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.mutinerie_est_camp(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mutinerie_est_camp(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.mutinerie_est_camp(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.mutinerie_pays_du_camp(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mutinerie_pays_du_camp(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.mutinerie_pays_du_camp(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.mutinerie_social_national(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mutinerie_social_national(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.mutinerie_social_national(text) TO service_role;

-- DROITS SUR LES SEQUENCES
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.batailles_engagements_id_seq TO postgres;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.batailles_engagements_id_seq TO service_role;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.batailles_id_seq TO postgres;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.batailles_id_seq TO service_role;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.batailles_rounds_id_seq TO postgres;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.batailles_rounds_id_seq TO service_role;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.contacts_militaires_id_seq TO postgres;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.contacts_militaires_id_seq TO service_role;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.decorations_militaires_id_seq TO postgres;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.decorations_militaires_id_seq TO service_role;
GRANT SELECT, USAGE ON SEQUENCE public.retraits_materiel_militaire_id_seq TO anon;
GRANT SELECT, USAGE ON SEQUENCE public.retraits_materiel_militaire_id_seq TO authenticated;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.retraits_materiel_militaire_id_seq TO postgres;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.retraits_materiel_militaire_id_seq TO service_role;
GRANT SELECT, USAGE ON SEQUENCE public.services_militaires_id_seq TO anon;
GRANT SELECT, USAGE ON SEQUENCE public.services_militaires_id_seq TO authenticated;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.services_militaires_id_seq TO postgres;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.services_militaires_id_seq TO service_role;

-- DROITS SUR LES TABLES
GRANT SELECT ON TABLE public.armureries_dotations TO anon;
GRANT SELECT ON TABLE public.armureries_dotations TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.armureries_dotations TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.armureries_dotations TO service_role;
GRANT SELECT ON TABLE public.batailles TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.batailles TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.batailles TO service_role;
GRANT SELECT ON TABLE public.batailles_engagements TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.batailles_engagements TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.batailles_engagements TO service_role;
GRANT SELECT ON TABLE public.batailles_groupes TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.batailles_groupes TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.batailles_groupes TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.batailles_rounds TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.batailles_rounds TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.camions_destinations TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.camions_destinations TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.camions_embarquements TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.camions_embarquements TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.camions_militaires TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.camions_militaires TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.camions_ordres TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.camions_ordres TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.candidatures_militaires TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.candidatures_militaires TO service_role;
GRANT SELECT ON TABLE public.commandes_militaires TO anon;
GRANT SELECT ON TABLE public.commandes_militaires TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.commandes_militaires TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.commandes_militaires TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.compagnies_militaires TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.compagnies_militaires TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.contacts_militaires TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.contacts_militaires TO service_role;
GRANT SELECT ON TABLE public.decorations_militaires TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.decorations_militaires TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.decorations_militaires TO service_role;
GRANT SELECT ON TABLE public.engagements_militaires TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.engagements_militaires TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.engagements_militaires TO service_role;
GRANT SELECT ON TABLE public.guerres TO anon;
GRANT SELECT ON TABLE public.guerres TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.guerres TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.guerres TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.militaire_armes_bonus TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.militaire_armes_bonus TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.militaire_detections TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.militaire_detections TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.militaire_terminal_requetes TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.militaire_terminal_requetes TO service_role;
GRANT SELECT ON TABLE public.mutineries TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.mutineries TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.mutineries TO service_role;
GRANT SELECT ON TABLE public.mutineries_membres TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.mutineries_membres TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.mutineries_membres TO service_role;
GRANT SELECT ON TABLE public.nominations_militaires TO anon;
GRANT SELECT ON TABLE public.nominations_militaires TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.nominations_militaires TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.nominations_militaires TO service_role;
GRANT SELECT ON TABLE public.recettes_militaires TO anon;
GRANT SELECT ON TABLE public.recettes_militaires TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.recettes_militaires TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.recettes_militaires TO service_role;
GRANT SELECT ON TABLE public.recettes_militaires_empreinte TO anon;
GRANT SELECT ON TABLE public.recettes_militaires_empreinte TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.recettes_militaires_empreinte TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.recettes_militaires_empreinte TO service_role;
GRANT SELECT ON TABLE public.retraits_materiel_militaire TO anon;
GRANT SELECT ON TABLE public.retraits_materiel_militaire TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.retraits_materiel_militaire TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.retraits_materiel_militaire TO service_role;
GRANT SELECT ON TABLE public.services_militaires TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.services_militaires TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.services_militaires TO service_role;
GRANT SELECT ON TABLE public.soldes_militaires TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.soldes_militaires TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.soldes_militaires TO service_role;
