-- Commentaires d'objets
-- ============================================================================
-- BASELINE Human Gambit -- domaine militaire -- phase 80 : commentaires
--
-- Fichier GENERE par outils/baseline/rendre.py depuis les catalogues
-- PostgreSQL. Ne pas editer a la main : toute correction passe par une
-- migration, puis par une nouvelle extraction.
--
-- ORDRE D'APPLICATION : par PHASE croissante, tous domaines confondus, et non
-- domaine par domaine. Voir baseline/README.md.
-- ============================================================================

COMMENT ON FUNCTION public.camion_batiment_interieur() IS 'Identifiant de batiment synthetique designant l''interieur d''un camion. La PIECE vaut l''identifiant du camion, la VILLE celle du camion. Nomme une seule fois, ici.';
COMMENT ON FUNCTION public.camion_deplacer(text,text,boolean,text) IS 'Deplace un camion et ce qu''il transporte, en une transaction. 0 FR, 2 PA par occupant reellement transporte, chacun sur ses propres PA. Refus global si un membre de la section prioritaire ne peut pas payer ; debarquement des seuls opportunistes insolvables. Idempotent par cle de requete.';
COMMENT ON FUNCTION public.camion_descendre(text) IS 'Descendre d''un camion stationne : on revient dans le lieu ou il se trouve reellement. Gratuit. Les accompagnants suivent par resolution dynamique, sans ecriture.';
COMMENT ON FUNCTION public.camion_destinations(text) IS 'Destinations utiles pour CE camion : celles ouvertes a son pays, plus sa propre caserne de rattachement. La position courante est toujours exclue.';
COMMENT ON FUNCTION public.camion_etat(text) IS 'Etat complet d''un camion pour l''appelant : position du camion, sa propre position, droit de commander, destinations. Sert aussi de mecanisme de resynchronisation, faute de temps reel.';
COMMENT ON FUNCTION public.camion_grade_commandant(text) IS 'Grade habilite a commander un camion (lieutenant ou capitaine), ou NULL. Aucune condition nominative.';
COMMENT ON FUNCTION public.camion_monter(text,text) IS 'Monter dans un camion stationne la ou l''on se trouve. Gratuit, ouvert a tout PJ. Applique la priorite militaire : une section qui embarque fait debarquer les opportunistes, dernier monte d''abord.';
COMMENT ON FUNCTION public.camion_occupants(text) IS 'Qui se trouve dans ce camion, PJ et PNJ confondus, par leur position EFFECTIVE. Definition unique : capacite, priorite, PA et deplacement s''y referent tous.';
COMMENT ON FUNCTION public.camions_ici(text,text,text,text) IS 'Camions reellement stationnes dans ce lieu. Le bouton d''acces n''existe que si cette liste n''est pas vide.';
COMMENT ON FUNCTION public.effort_commande_annuler(text) IS 'Seule porte d''annulation du reliquat d''une commande militaire. Exige min_def et le meme pays que la commande. quantite_produite n''est jamais modifiee. Chantier 4D.';
COMMENT ON FUNCTION public.effort_commande_creer(text,integer) IS 'Seule porte de creation d''une commande militaire. Exige le poste min_def, un produit du catalogue canonique (recettes_militaires), une quantite bornee et un Effort de guerre actif. Le pays est celui du ministre, jamais un parametre. Chantier 4D.';
COMMENT ON FUNCTION public.militaire_arme_operationnelle(text) IS 'Arme operationnelle d''un PNJ soldat, DEDUITE de ce qu''il porte reellement dans pnj_possessions. Meme regle que pour un joueur dans militaire_bataille_combattants : meilleur bonus, le tir primant le corps a corps, repli sur corps_a_corps.';
COMMENT ON FUNCTION public.militaire_arme_recalculer(text) IS 'Recalcule l''arme operationnelle d''un PNJ soldat depuis ses possessions et l''ecrit AUX DEUX ENDROITS : le blob de compagnie, qui est le magasin de cet axe metier, et pnj_soldats_metier.arme, que le moteur de combat lit. Ecrire seulement la seconde laisserait pnj_miroir_compagnie reimporter l''ancienne categorie a la prochaine ecriture du blob, et desarmer le soldat en silence.';
COMMENT ON FUNCTION public.militaire_bataille_combattants(bigint,text) IS 'Combattants d''un camp. Le mode (feu ou corps a corps) d''un PNJ est determine par militaire_armes_bonus et non plus par une paire de categories ecrite en dur : arme_de_poing et mitraillette conservent exactement 8 et 15 en feu.';
COMMENT ON FUNCTION public.militaire_equiper_soldat(text,text,text,text) IS 'Equipe un PNJ soldat depuis le stock d''armes de sa section. Depuis le lot T elle POSE UN VRAI OBJET dans pnj_possessions au lieu d''ecrire une categorie abstraite, et rend au stock l''arme precedemment portee. L''arme operationnelle est ensuite recalculee depuis les possessions : les deux chemins -- stock de section et transfert d''objet -- ne peuvent plus se contredire.';
COMMENT ON FUNCTION public.militaire_ma_section() IS 'Section dont l''appelant est le Lieutenant structurel, resolue par le SERVEUR a partir de mon_personnage() : le client n''annonce aucun identifiant et n''a donc pas besoin de lire le blob des compagnies. Rend pas_lieutenant_de_section a tout autre joueur, y compris Capitaine, Commandant et Ministre de la Defense.';
COMMENT ON FUNCTION public.militaire_objet_signature(jsonb) IS 'Signature d''interchangeabilite d''un objet : coalesce(produitMilitaire, name) + type, la meme convention que militaire_armes_bonus utilise pour reconnaitre une arme. Deux objets de meme signature sont comptables ensemble ; c''est ce qui permet de transferer N unites sans exiger que les objets soient empilables.';
COMMENT ON FUNCTION public.militaire_terminal_dormir(text,text[],text[]) IS 'Ordre collectif de dormir, avec designation explicite de qui a une place sous la tente. Valeurs reprises de militaire_reposer_section : caserne 12, terrain +8, tente +8+2, une fois par jour, jamais a 0 PA. Capacite de 13 personnes par tente PJ COMPRIS ; une selection qui la depasse refuse l''ordre ENTIER. Idempotente par cle de requete.';
COMMENT ON FUNCTION public.militaire_terminal_liaison(text,text) IS 'Le Lieutenant peut-il commander ce soldat ? Vrai s''il est physiquement present avec lui, sinon vrai seulement si le Lieutenant porte une radio ET que le groupe distant en porte une -- celle de son leader PJ, ou, a defaut de leader joueur, celle d''un PNJ place au meme endroit, qui fait alors office de leader pour cette liaison.';
COMMENT ON FUNCTION public.militaire_terminal_manger(text,text[]) IS 'Ordre collectif de manger. Chaque soldat selectionne consomme SA propre ration et gagne 1 PA (plafond 12, deux par jour) ; celui qui n''en a pas execute l''ordre sans bonus et ne fait pas echouer l''ordre. La ration du Lieutenant n''est JAMAIS prelevee pour un PNJ. Idempotente par cle de requete.';
COMMENT ON FUNCTION public.militaire_terminal_rejoindre(text,text[]) IS 'Rappelle des soldats aupres du Lieutenant : leader_pj = lui, position propre effacee. Le perimetre est la VILLE et non la piece, et une liaison de commandement est exigee a distance. Une autre ville est refusee nommement (autre_ville_transport_requis) : aucun soldat n''est teleporte, le transport reste le camion militaire existant.';
COMMENT ON FUNCTION public.militaire_terminal_section() IS 'Tout ce que le terminal du Lieutenant affiche, en UN appel : ses soldats PNJ (matricule, PA, arme deduite, position reduite a la VILLE, possessions regroupees par signature, radio, compteurs du jour), son propre inventaire regroupe par signature, et la capacite reelle sous tente. Ne rend QUE la section dont l''appelant est le Lieutenant.';
COMMENT ON FUNCTION public.militaire_terminal_transferer(text,text,text,integer,text) IS 'Deplace N unites d''une signature d''objet entre le Lieutenant et un de ses soldats PNJ, dans les deux sens. Aucune liste blanche : n''importe quel objet passe. Co-presence exigee dans les deux sens. Un objet empile est scinde par son qty, un objet unitaire part en entier. Recalcule l''armement du soldat apres chaque mouvement. Idempotente par cle de requete.';
COMMENT ON TABLE public.batailles_groupes IS 'Unite de decision du combat : un groupe = une section engagee. Porte son effectif initial, son chef et sa decision de repli.';
COMMENT ON TABLE public.camions_destinations IS 'Destinations ouvertes aux camions d''un pays. La caserne de rattachement n''y figure pas : elle est propre a chaque camion et resolue sous la cle reservee __caserne__.';
COMMENT ON TABLE public.camions_embarquements IS 'Instant d''embarquement de chaque PJ, utilise UNIQUEMENT pour ordonner les debarquements par priorite militaire (dernier monte, premier debarque). Ne fait jamais autorite sur la presence a bord.';
COMMENT ON TABLE public.camions_militaires IS 'Parc de vehicules de transport de troupe. Position courante ET caserne de rattachement, distinctes. Ferme au client : toute lecture passe par camions_ici/camion_etat, toute ecriture par camion_deplacer.';
COMMENT ON TABLE public.camions_ordres IS 'Journal idempotent des ordres donnes a un camion. Ecrit uniquement par les RPC SECURITY DEFINER ; ferme au client.';
COMMENT ON TABLE public.candidatures_militaires IS 'Candidatures a un grade militaire. Diffusees a tous les recruteurs eligibles ; le premier qui accepte l''emporte. Un refus individuel s''inscrit dans refus et laisse la candidature active.';
COMMENT ON TABLE public.recettes_militaires IS 'MIROIR GENERE de RECETTES_MILITAIRES (plateau-effort-guerre.js). Ne jamais editer a la main : regenerer par outils/generateurs/generer_recettes_militaires.py. Sert au serveur a valider qu''un produit commande appartient au catalogue. Chantier 4D.';
