-- JUSTICE : PASSE DE FERMETURE (16 septembre 2026).
-- DEJA EXECUTEE en production (migrations MCP : justice_qhs_registre_et_geoles,
-- justice_condamnations_recherchees_canoniques, justice_garde_a_vue_enquete).
--
-- PRINCIPE : `detentions` est la source de verite de toute incarceration effective.
-- `personnages.est_emprisonne` n'est plus qu'un miroir de compatibilite, ecrit par le serveur
-- dans la meme transaction que la table canonique. Une personne CONDAMNEE MAIS LIBRE n'a jamais
-- de ligne `detentions` -- c'est l'invariant pose par le game design.
--
-- 1. REGISTRE QHS. prisonniers_qhs avait la RLS DESACTIVEE : n'importe quel navigateur pouvait y
--    inscrire qui il voulait. La table est alignee sur `detentions` -- lecture publique, ecriture
--    limitee a soi-meme, aucun DELETE. Les deux chemins legitimes du client (placerAuQHS,
--    rebellion matee) inscrivent le joueur lui-meme et fonctionnent toujours ; la sentence QHS du
--    juge, qui visait un tiers, passe desormais par justice_prolonger_peine, qui tient le registre
--    dans la meme transaction que la peine.
--
-- 2. PROLONGATION. justice_prolonger_peine cherchait la detention dans est_emprisonne ; elle lit
--    maintenant `detentions` via detention_active().
--
-- 3. GEOLES. La liste des detenus interrogeait est_emprisonne CHEZ AUTRUI -- masque depuis le
--    chantier B, donc toujours vide. geoles_detenus(pays, ville) la construit depuis `detentions`
--    (mode_fin et jour_fin_effective nuls) et ne renvoie que nom, photo et drapeau QHS. Une peine
--    close disparait de la liste a l'instant ou elle est close.
--
-- 4. CONDAMNES RECHERCHES. L'avis de recherche vivait dans le blob personnages.recherche, ecrit
--    par read-modify-write depuis le navigateur du juge : refuse depuis le chantier B, donc plus
--    personne n'etait jamais recherche -- ni les condamnes, ni les deserteurs. AUCUNE TABLE
--    NOUVELLE : `jugements` existait deja, vide, et porte la bonne notion (accuse, motif, peine,
--    juge, executee). Une condamnation `executee = false` EST l'avis de recherche. Seul ajout,
--    additif : une colonne `data` pour conserver l'entree telle que le jeu la compose.
--      * justice_condamner(cible, entree)        -- reserve au juge
--      * justice_recherches(nom)                 -- lecture minimale
--      * justice_executer_condamnation(id, ville)-- reserve au commissaire : c'est ici, et la
--        seule, que « recherche » devient « detenu ». Elle passe par detention_ouvrir_interne,
--        refuse d'ouvrir une seconde peine sur quelqu'un de deja detenu, et se verrouille
--        (FOR UPDATE) : rejouee, elle ne cree pas de double detention.
--
-- 5. GARDE A VUE APRES ENQUETE. traiterEnquetes ouvrait la detention de la cible par une ecriture
--    directe sur sa fiche -- refusee, et avalee par un .catch() muet : on annoncait « mise en
--    garde a vue immediate » et la personne continuait de jouer. enquete_garde_a_vue passe par la
--    primitive canonique. L'autorite n'est pas declaree mais PROUVEE : le serveur relit le blob
--    enquetes_en_cours SUR LA FICHE DE L'APPELANT et exige d'y retrouver une enquete visant cette
--    cible et arrivee a terme.
--
-- 6. FRAUDE ELECTORALE (cote client). emprisonnerPourFraude posait un est_emprisonne fabrique a
--    la main, SANS detentionId ni debutTs : la peine etait invisible du registre du commissariat
--    ET du filet de liberation nocturne, qui s'ancre sur debutTs. Elle passe par
--    enregistrerDetention comme toutes les autres, et liberationElection est simplement repose
--    apres coup. Sanction inchangee.
--
-- 7. CHASSE A L'HOMME (cote client). Elle lisait le blob `recherche` de la cible (toujours vide,
--    donc injouable contre quiconque) puis ouvrait la detention et retirait l'avis sur la fiche
--    d'autrui (refuse). Elle lit desormais justice_recherches et execute par
--    justice_executer_condamnation ; un refus n'annonce plus ni arrestation, ni mail, ni evenement.
--
-- Aucune duree, aucun motif, aucune autorite, aucune sanction n'a ete modifie.
--
-- Bancs : .scratch/banc_justice_qhs.py (25 controles) + chaine complete eprouvee en transaction
-- annulee sur la base reelle : condamnation -> 0 detention / 1 avis ; execution -> 1 detention,
-- 0 avis, miroir pose, 1 detenu dans les geoles ; rejeu -> toujours 1 detention ; cloture ->
-- 0 detention active, 0 dans les geoles.

-- =====================================================================================
-- COMPLEMENT : CONTESTATION DE RESULTATS (dernier chemin judiciaire)
-- =====================================================================================
-- DEJA EXECUTE en production (migration MCP : fraude_electorale_sanction_serveur, plus une
-- reecriture de justice_prolonger_peine pour qu'elle pose aussi le drapeau detention_qhs).
--
-- LE DEFAUT. Quand une contestation etablit une fraude, le contestataire encaissait ses +200 FR
-- et l'evenement public etait publie -- deux ecritures qui aboutissent. La sanction du fraudeur,
-- elle, passait par une ecriture directe sur SA fiche : refusee depuis le chantier B, avalee par
-- un .catch() muet. Le fraudeur n'etait ni amende ni detenu, et la peine qu'on lui fabriquait
-- n'avait de toute facon ni detentionId ni ligne `detentions`.
--
-- LA REGLE, retrouvee dans le code et NON MODIFIEE : fraudeur -500 FR et 2 jours (peine fixe de
-- la decouverte a posteriori, distincte des peines du flagrant delit) ; contestataire +200 FR ;
-- motif « Fraude électorale (<type>) révélée par contestation ».
--
-- fraude_electorale_sanctionner retrouve la fraude dans `fraudes_electorales`, n'accepte que si
-- elle n'est pas deja revelee, puis applique les quatre effets dans la MEME transaction :
-- revelation, amende, detention (par detention_ouvrir_interne) et recompense. Le navigateur ne
-- declare ni la fraude, ni le coupable (c'est `auteur` en base), ni le montant, ni la duree.
--
-- IDEMPOTENCE : le passage a l'etat « revelee » se fait sous verrou AVANT toute sanction. Rejeu,
-- F5 ou requetes concurrentes : la seconde voit une fraude deja revelee et ne produit rien.
--
-- Eprouve en transaction annulee : fraudeur 3096 -> 2596, contestataire 2600 -> 2800, detention
-- active de 2 jours visible en geole, miroir pose ; rejeu refuse ; fraude inconnue refusee.
--
-- DERNIER CHEMIN FERME AU PASSAGE : la sentence QHS du juge posait encore detention_qhs sur la
-- fiche de la cible. justice_prolonger_peine le pose desormais elle-meme.
--
-- DEPENDANCE MILITAIRE, PAS UN DEFAUT JUDICIAIRE : verifierDesertionsQuotidien appelle
-- ajouterCondamnationRecherche, donc justice_condamner, qui exige le poste de juge -- or la
-- desertion est constatee par une boucle militaire quotidienne, sans juge. Cette branche reste
-- sans effet et releve du chantier Militaire (reQuisition -> presentation -> desertion ->
-- recherche -> arrestation), hors perimetre ici.
