-- =====================================================================================
-- refectoire_repas : le pays n'est plus cru — Res Publica, 17 septembre 2026
--
-- LE DEFAUT. La fonction verifiait la presence physique (current_building = 'caserne-militaire')
-- mais lisait le stock du refectoire sur budgets_nationaux.id = p_pays, un PARAMETRE CLIENT. Or
-- 'caserne-militaire' est LE MEME identifiant de batiment dans les quatre empires (data.js:954,
-- 1197, 1441, 1710) : la presence ne distinguait donc pas la caserne ou l'on se trouve de celle
-- dont on consommait le stock. Un joueur pouvait manger les rations d'un autre empire.
--
-- LE CORRECTIF. v_pays est desormais lu sur la fiche du personnage (territoire ou il se trouve
-- reellement). p_pays reste dans la signature pour ne casser aucun appelant, et est volontairement
-- ignore -- meme convention que p_gain et p_pa_max, deja ignores par cette fonction.
-- Aucune regle de jeu modifiee : +2 PA, plafond 30, recette de 10 rations inchangees.
--
-- BANC 3/3 en transaction annulee : en declarant p_pays='narco' depuis la caserne de Republia,
-- c'est bien REPUBLIA qui est debitee (7 -> 6) et Narcovia reste intacte (99) ; second repas le
-- meme jour refuse (deja_mange) ; p_gain=99 donne toujours +2 PA.
--
-- DEFAUT RESIDUEL NON CORRIGE, signale pour arbitrage : p_jour reste transmis par le client et
-- sert de cle anti-rejeu (stats.repasCaserneJour). Un client qui incremente p_jour mange autant
-- de fois qu'il veut -- le banc l'a constate (scenario 3 : un second repas passe avec p_jour=2).
-- Le fermer demande de choisir la source du jour : le compteur de jeu prive (state.day) ou la
-- date reelle Europe/Paris, comme le fait deja pa_repos_nocturne avec pa_repos_le. C'est un choix
-- de regle, pas un correctif : non tranche ici.
-- =====================================================================================
-- Le corps applique est celui de la migration « refectoire_pays_derive_serveur ».

-- =====================================================================================
-- SUITE (meme jour) : ANTI-REJEU QUOTIDIEN — le jour n'est plus cru non plus
--
-- Arbitrage GD rendu apres audit : ne PAS creer d'horloge jour_de_jeu(). Le depot utilise deja
-- largement, comme convention serveur pour toute garde « une fois par jour », la DATE REELLE
-- Europe/Paris -- pa_repos_nocturne (pa_repos_le), assemblee_verser_indemnite,
-- calomnie_distribuer_interne, corruption_presse_tenter, championnat_*. On applique la meme.
-- p_jour reste dans la signature et est desormais ignore, comme p_pays, p_gain et p_pa_max.
--
-- CONSTAT QUI A MOTIVE CET ARBITRAGE : il n'existe AUCUNE source serveur du jour de jeu.
-- personnages_donnees.day est un compteur PRIVE et divergent ; jourPartageISO() et
-- jourCourantISO() renvoient tous deux la date reelle malgre leur nom ; et
-- corruption_presse_tenter insere « jour: 0, jour_expiration: 0 » dans actions_tracables --
-- preuve directe que le serveur ne sait pas quel jour de jeu il est. La coexistence entre
-- state.day individuel et temporalite serveur releve du chantier TEMPORALITE, pas de ce lot.
--
-- PIEGE EVITE, et il aurait annule le correctif : le client ecrivait
-- state.char.stats.repasCaserneJour = state.day APRES la RPC. La prochaine sauvegarde complete du
-- personnage republiant tout le blob stats, ce state.day aurait ECRASE le marqueur serveur et le
-- rejeu aurait redevenu possible des le lendemain. La RPC renvoie donc « jourCle » et le client
-- recopie exactement ce que le serveur a inscrit (plateau-effort-guerre.js).
--
-- TRANSITION : une valeur heritee au format entier ne peut jamais egaler une date ISO -- le
-- premier repas suivant le deploiement est donc accorde. Voulu, sans consequence.
--
-- BANC 5/5 en transaction annulee : marqueur herite 47 -> premier repas accorde et marqueur
-- devenu « 2026-09-17 » ; puis rejeu refuse (deja_mange) avec p_jour=48, p_jour=9999,
-- p_jour=NULL, et p_jour=123 combine a p_pays='narco'. Rations 7 -> 6 une seule fois, PA 5 -> 7.
-- =====================================================================================
-- Le corps applique est celui de la migration « refectoire_antirejeu_date_reelle ».
