-- GRANT sur tables, colonnes et fonctions
-- ============================================================================
-- BASELINE Human Gambit -- domaine personnage et presence -- phase 70 : droits
--
-- Fichier GENERE par outils/baseline/rendre.py depuis les catalogues
-- PostgreSQL. Ne pas editer a la main : toute correction passe par une
-- migration, puis par une nouvelle extraction.
--
-- ORDRE D'APPLICATION : par PHASE croissante, tous domaines confondus, et non
-- domaine par domaine. Voir baseline/README.md.
-- ============================================================================

-- DROITS SUR LES FUNCTIONS
GRANT EXECUTE ON FUNCTION public.contact_organisation_choisir(text,text,jsonb) TO postgres;
GRANT EXECUTE ON FUNCTION public.contact_organisation_choisir(text,text,jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.contact_organisation_demander(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.contact_organisation_demander(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.contact_organisation_demander(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.contact_organisation_etat(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.contact_organisation_etat(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.contact_organisation_etat(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.cron_journal_ecrire(text,date,text,text,jsonb,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.cron_journal_ecrire(text,date,text,text,jsonb,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.don_argent_deposer(text,text,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.don_argent_deposer(text,text,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.don_argent_deposer(text,text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.employe_liberer(text,text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.employe_liberer(text,text) TO anon;
GRANT EXECUTE ON FUNCTION public.employe_liberer(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.employe_liberer(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.employe_liberer(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.employe_mes_employes() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.employe_mes_employes() TO anon;
GRANT EXECUTE ON FUNCTION public.employe_mes_employes() TO authenticated;
GRANT EXECUTE ON FUNCTION public.employe_mes_employes() TO postgres;
GRANT EXECUTE ON FUNCTION public.employe_mes_employes() TO service_role;
GRANT EXECUTE ON FUNCTION public.employe_metiers_recrutables() TO postgres;
GRANT EXECUTE ON FUNCTION public.employe_metiers_recrutables() TO service_role;
GRANT EXECUTE ON FUNCTION public.employe_pnj_id(text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.employe_pnj_id(text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.employe_recruter(text,text,text,text,integer,integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.employe_recruter(text,text,text,text,integer,integer) TO anon;
GRANT EXECUTE ON FUNCTION public.employe_recruter(text,text,text,text,integer,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.employe_recruter(text,text,text,text,integer,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.employe_recruter(text,text,text,text,integer,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.employeur_candidats(text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.employeur_candidats(text) TO anon;
GRANT EXECUTE ON FUNCTION public.employeur_candidats(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.employeur_candidats(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.employeur_candidats(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.employeur_embaucher(text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.employeur_embaucher(text) TO anon;
GRANT EXECUTE ON FUNCTION public.employeur_embaucher(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.employeur_embaucher(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.employeur_embaucher(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.escort_recruter(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.escort_recruter(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.escort_recruter(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.escort_sociale_actuelle() TO authenticated;
GRANT EXECUTE ON FUNCTION public.escort_sociale_actuelle() TO postgres;
GRANT EXECUTE ON FUNCTION public.escort_sociale_actuelle() TO service_role;
GRANT EXECUTE ON FUNCTION public.escort_sociale_choisir(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.escort_sociale_choisir(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.escort_sociale_choisir(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.escorts_agence() TO authenticated;
GRANT EXECUTE ON FUNCTION public.escorts_agence() TO postgres;
GRANT EXECUTE ON FUNCTION public.escorts_agence() TO service_role;
GRANT EXECUTE ON FUNCTION public.naturalisation_traiter(text,boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.naturalisation_traiter(text,boolean) TO postgres;
GRANT EXECUTE ON FUNCTION public.naturalisation_traiter(text,boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.personnage_ajuster_pop_inf(text,integer,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.personnage_ajuster_pop_inf(text,integer,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.personnage_ajuster_pop_inf(text,text,integer,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.personnage_ajuster_pop_inf(text,text,integer,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.personnage_ajuster_pop_inf(text,text,integer,integer,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.personnage_ajuster_pop_inf(text,text,integer,integer,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.personnage_ajuster_pop_inf(text,text,integer,integer,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.personnages_archiver_suppression() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.personnages_archiver_suppression() TO anon;
GRANT EXECUTE ON FUNCTION public.personnages_archiver_suppression() TO authenticated;
GRANT EXECUTE ON FUNCTION public.personnages_archiver_suppression() TO postgres;
GRANT EXECUTE ON FUNCTION public.personnages_archiver_suppression() TO service_role;
GRANT EXECUTE ON FUNCTION public.personnages_attester_poste() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.personnages_attester_poste() TO anon;
GRANT EXECUTE ON FUNCTION public.personnages_attester_poste() TO authenticated;
GRANT EXECUTE ON FUNCTION public.personnages_attester_poste() TO postgres;
GRANT EXECUTE ON FUNCTION public.personnages_attester_poste() TO service_role;
GRANT EXECUTE ON FUNCTION public.personnages_borner_jour() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.personnages_borner_jour() TO anon;
GRANT EXECUTE ON FUNCTION public.personnages_borner_jour() TO authenticated;
GRANT EXECUTE ON FUNCTION public.personnages_borner_jour() TO postgres;
GRANT EXECUTE ON FUNCTION public.personnages_borner_jour() TO service_role;
GRANT EXECUTE ON FUNCTION public.personnages_fusionner_pop() TO postgres;
GRANT EXECUTE ON FUNCTION public.personnages_fusionner_pop() TO service_role;
GRANT EXECUTE ON FUNCTION public.personnages_lien_militaire_rompu() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.personnages_lien_militaire_rompu() TO anon;
GRANT EXECUTE ON FUNCTION public.personnages_lien_militaire_rompu() TO authenticated;
GRANT EXECUTE ON FUNCTION public.personnages_lien_militaire_rompu() TO postgres;
GRANT EXECUTE ON FUNCTION public.personnages_lien_militaire_rompu() TO service_role;
GRANT EXECUTE ON FUNCTION public.personnages_lien_militaire_supprime() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.personnages_lien_militaire_supprime() TO anon;
GRANT EXECUTE ON FUNCTION public.personnages_lien_militaire_supprime() TO authenticated;
GRANT EXECUTE ON FUNCTION public.personnages_lien_militaire_supprime() TO postgres;
GRANT EXECUTE ON FUNCTION public.personnages_lien_militaire_supprime() TO service_role;
GRANT EXECUTE ON FUNCTION public.personnages_lier_proprietaire() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.personnages_lier_proprietaire() TO anon;
GRANT EXECUTE ON FUNCTION public.personnages_lier_proprietaire() TO authenticated;
GRANT EXECUTE ON FUNCTION public.personnages_lier_proprietaire() TO postgres;
GRANT EXECUTE ON FUNCTION public.personnages_lier_proprietaire() TO service_role;
GRANT EXECUTE ON FUNCTION public.personnages_observer_inventaire() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.personnages_observer_inventaire() TO anon;
GRANT EXECUTE ON FUNCTION public.personnages_observer_inventaire() TO authenticated;
GRANT EXECUTE ON FUNCTION public.personnages_observer_inventaire() TO postgres;
GRANT EXECUTE ON FUNCTION public.personnages_observer_inventaire() TO service_role;
GRANT EXECUTE ON FUNCTION public.personnages_poste_perdu() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.personnages_poste_perdu() TO anon;
GRANT EXECUTE ON FUNCTION public.personnages_poste_perdu() TO authenticated;
GRANT EXECUTE ON FUNCTION public.personnages_poste_perdu() TO postgres;
GRANT EXECUTE ON FUNCTION public.personnages_poste_perdu() TO service_role;
GRANT EXECUTE ON FUNCTION public.personnages_preserver_judiciaire() TO postgres;
GRANT EXECUTE ON FUNCTION public.personnages_preserver_judiciaire() TO service_role;
GRANT EXECUTE ON FUNCTION public.personnages_vue_inserer() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.personnages_vue_inserer() TO anon;
GRANT EXECUTE ON FUNCTION public.personnages_vue_inserer() TO authenticated;
GRANT EXECUTE ON FUNCTION public.personnages_vue_inserer() TO postgres;
GRANT EXECUTE ON FUNCTION public.personnages_vue_inserer() TO service_role;
GRANT EXECUTE ON FUNCTION public.personnages_vue_modifier() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.personnages_vue_modifier() TO anon;
GRANT EXECUTE ON FUNCTION public.personnages_vue_modifier() TO authenticated;
GRANT EXECUTE ON FUNCTION public.personnages_vue_modifier() TO postgres;
GRANT EXECUTE ON FUNCTION public.personnages_vue_modifier() TO service_role;
GRANT EXECUTE ON FUNCTION public.personnages_vue_supprimer() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.personnages_vue_supprimer() TO anon;
GRANT EXECUTE ON FUNCTION public.personnages_vue_supprimer() TO authenticated;
GRANT EXECUTE ON FUNCTION public.personnages_vue_supprimer() TO postgres;
GRANT EXECUTE ON FUNCTION public.personnages_vue_supprimer() TO service_role;
GRANT EXECUTE ON FUNCTION public.referent_pedagogie_contexte(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.referent_pedagogie_contexte(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.referent_pedagogie_contexte(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.referent_pedagogie_noter(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.referent_pedagogie_noter(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.referent_pedagogie_noter(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.referent_pedagogie_noter_sujet(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.referent_pedagogie_noter_sujet(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.referent_pedagogie_noter_sujet(text,text) TO service_role;

-- DROITS SUR LES SEQUENCES
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.dons_en_attente_id_seq TO anon;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.dons_en_attente_id_seq TO authenticated;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.dons_en_attente_id_seq TO postgres;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.dons_en_attente_id_seq TO service_role;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.fiche_hausses_observees_id_seq TO postgres;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.fiche_hausses_observees_id_seq TO service_role;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.fiche_inventaire_observe_id_seq TO anon;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.fiche_inventaire_observe_id_seq TO authenticated;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.fiche_inventaire_observe_id_seq TO postgres;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.fiche_inventaire_observe_id_seq TO service_role;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.historique_deplacements_id_seq TO anon;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.historique_deplacements_id_seq TO authenticated;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.historique_deplacements_id_seq TO postgres;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.historique_deplacements_id_seq TO service_role;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.invitations_diner_id_seq TO anon;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.invitations_diner_id_seq TO authenticated;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.invitations_diner_id_seq TO postgres;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.invitations_diner_id_seq TO service_role;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.personnages_supprimes_archive_id_seq TO postgres;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.personnages_supprimes_archive_id_seq TO service_role;

-- DROITS SUR LES TABLES
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.contacts_organisations TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.contacts_organisations TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.contacts_organisations_passeurs TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.contacts_organisations_passeurs TO service_role;
GRANT MAINTAIN, SELECT ON TABLE public.demandes_mariage TO anon;
GRANT INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, UPDATE ON TABLE public.demandes_mariage TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.demandes_mariage TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.demandes_mariage TO service_role;
GRANT MAINTAIN, SELECT ON TABLE public.demandes_naturalisation TO anon;
GRANT INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, UPDATE ON TABLE public.demandes_naturalisation TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.demandes_naturalisation TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.demandes_naturalisation TO service_role;
GRANT MAINTAIN, SELECT ON TABLE public.dons_en_attente TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, UPDATE ON TABLE public.dons_en_attente TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.dons_en_attente TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.dons_en_attente TO service_role;
GRANT MAINTAIN, SELECT ON TABLE public.dons_requetes TO anon;
GRANT INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, UPDATE ON TABLE public.dons_requetes TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.dons_requetes TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.dons_requetes TO service_role;
GRANT MAINTAIN, SELECT ON TABLE public.escort_evenements_commerciaux TO anon;
GRANT INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, UPDATE ON TABLE public.escort_evenements_commerciaux TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.escort_evenements_commerciaux TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.escort_evenements_commerciaux TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.escorts_agences TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.escorts_agences TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.escorts_catalogue TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.escorts_catalogue TO service_role;
GRANT MAINTAIN, SELECT ON TABLE public.etat_civil_deces TO anon;
GRANT INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, UPDATE ON TABLE public.etat_civil_deces TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.etat_civil_deces TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.etat_civil_deces TO service_role;
GRANT MAINTAIN, SELECT ON TABLE public.etat_civil_naissances TO anon;
GRANT INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, UPDATE ON TABLE public.etat_civil_naissances TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.etat_civil_naissances TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.etat_civil_naissances TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.fiche_hausses_observees TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.fiche_hausses_observees TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.fiche_inventaire_observe TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.fiche_inventaire_observe TO service_role;
GRANT MAINTAIN ON TABLE public.historique_deplacements TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER ON TABLE public.historique_deplacements TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.historique_deplacements TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.historique_deplacements TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, UPDATE ON TABLE public.invitations_diner TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.invitations_diner TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.invitations_diner TO service_role;
GRANT MAINTAIN, SELECT ON TABLE public.mariages TO anon;
GRANT INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, UPDATE ON TABLE public.mariages TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.mariages TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.mariages TO service_role;
GRANT MAINTAIN, SELECT ON TABLE public.objets_abandonnes TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, UPDATE ON TABLE public.objets_abandonnes TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.objets_abandonnes TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.objets_abandonnes TO service_role;
GRANT DELETE, MAINTAIN, SELECT ON TABLE public.objets_recus TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.objets_recus TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.objets_recus TO service_role;
GRANT MAINTAIN, SELECT ON TABLE public.organisations TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, UPDATE ON TABLE public.organisations TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.organisations TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.organisations TO service_role;
GRANT MAINTAIN, SELECT ON TABLE public.personnages TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.personnages TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.personnages TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.personnages TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.personnages_donnees TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.personnages_donnees TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.personnages_supprimes TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.personnages_supprimes TO service_role;
GRANT MAINTAIN, SELECT ON TABLE public.presences TO anon;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, UPDATE ON TABLE public.presences TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.presences TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.presences TO service_role;
GRANT MAINTAIN, SELECT ON TABLE public.quetes_actives TO anon;
GRANT INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, UPDATE ON TABLE public.quetes_actives TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.quetes_actives TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.quetes_actives TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.reconciliation_fantomes TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.reconciliation_fantomes TO service_role;
GRANT MAINTAIN, SELECT ON TABLE public.souvenirs_accueil TO anon;
GRANT INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, UPDATE ON TABLE public.souvenirs_accueil TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.souvenirs_accueil TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.souvenirs_accueil TO service_role;
GRANT INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, UPDATE ON TABLE public.successions TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.successions TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.successions TO service_role;
GRANT INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, UPDATE ON TABLE public.testaments TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.testaments TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.testaments TO service_role;
GRANT INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, UPDATE ON TABLE public.tournees TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.tournees TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.tournees TO service_role;
