-- GRANT sur tables, colonnes et fonctions
-- ============================================================================
-- BASELINE Human Gambit -- domaine finances publiques -- phase 70 : droits
--
-- Fichier GENERE par outils/baseline/rendre.py depuis les catalogues
-- PostgreSQL. Ne pas editer a la main : toute correction passe par une
-- migration, puis par une nouvelle extraction.
--
-- ORDRE D'APPLICATION : par PHASE croissante, tous domaines confondus, et non
-- domaine par domaine. Voir baseline/README.md.
-- ============================================================================

-- DROITS SUR LES FUNCTIONS
GRANT EXECUTE ON FUNCTION public.alimenter_caisse_fonds(text,text,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.alimenter_caisse_fonds(text,text,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.alimenter_caisse_fonds(text,text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.appliquer_taxe_transaction(text,text,numeric) TO postgres;
GRANT EXECUTE ON FUNCTION public.appliquer_taxe_transaction(text,text,numeric) TO service_role;
GRANT EXECUTE ON FUNCTION public.budget_cascade_quotidienne(text,numeric) TO postgres;
GRANT EXECUTE ON FUNCTION public.budget_cascade_quotidienne(text,numeric) TO service_role;
GRANT EXECUTE ON FUNCTION public.budget_coherence() TO postgres;
GRANT EXECUTE ON FUNCTION public.budget_coherence() TO service_role;
GRANT EXECUTE ON FUNCTION public.budget_national_epingler() TO postgres;
GRANT EXECUTE ON FUNCTION public.budget_national_epingler() TO service_role;
GRANT EXECUTE ON FUNCTION public.budget_part_totale(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.budget_part_totale(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.budget_repartir(text,text,numeric) TO postgres;
GRANT EXECUTE ON FUNCTION public.budget_repartir(text,text,numeric) TO service_role;
GRANT EXECUTE ON FUNCTION public.budget_repartition_fixer(text,text,numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.budget_repartition_fixer(text,text,numeric) TO postgres;
GRANT EXECUTE ON FUNCTION public.budget_repartition_fixer(text,text,numeric) TO service_role;
GRANT EXECUTE ON FUNCTION public.budget_repartition_lire(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.budget_repartition_lire(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.budget_repartition_lire(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.budgets_armurerie_verrou() TO postgres;
GRANT EXECUTE ON FUNCTION public.budgets_armurerie_verrou() TO service_role;
GRANT EXECUTE ON FUNCTION public.budgets_virement_caserne_verrou() TO postgres;
GRANT EXECUTE ON FUNCTION public.budgets_virement_caserne_verrou() TO service_role;
GRANT EXECUTE ON FUNCTION public.caisse_client_mouvement(text,numeric,text,boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.caisse_client_mouvement(text,numeric,text,boolean) TO postgres;
GRANT EXECUTE ON FUNCTION public.caisse_client_mouvement(text,numeric,text,boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.caisse_commissariat_lire(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.caisse_commissariat_lire(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.caisse_commissariat_lire(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.caisse_institution_mouvement(text,numeric,boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.caisse_institution_mouvement(text,numeric,boolean) TO postgres;
GRANT EXECUTE ON FUNCTION public.caisse_institution_mouvement(text,numeric,boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.caisse_institution_mouvement_plafonne(text,numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.caisse_institution_mouvement_plafonne(text,numeric) TO postgres;
GRANT EXECUTE ON FUNCTION public.caisse_institution_mouvement_plafonne(text,numeric) TO service_role;
GRANT EXECUTE ON FUNCTION public.caisse_ministere_mouvement(text,numeric,text,boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.caisse_ministere_mouvement(text,numeric,text,boolean) TO postgres;
GRANT EXECUTE ON FUNCTION public.caisse_ministere_mouvement(text,numeric,text,boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.caisse_postes_requis(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.caisse_postes_requis(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.caisse_postes_requis(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.caisse_refus_autorite(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.caisse_refus_autorite(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.caisse_territoire(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.caisse_territoire(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.caisse_ville_de(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.caisse_ville_de(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.debiter_fonds_ordinaires(text,numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.debiter_fonds_ordinaires(text,numeric) TO postgres;
GRANT EXECUTE ON FUNCTION public.debiter_fonds_ordinaires(text,numeric) TO service_role;
GRANT EXECUTE ON FUNCTION public.dotation_attribuer_point(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.dotation_attribuer_point(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.dotation_attribuer_point(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.fonds_acteur_present(text,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fonds_acteur_present(text,jsonb) TO postgres;
GRANT EXECUTE ON FUNCTION public.fonds_acteur_present(text,jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.fonds_cout_revient_reference(text,text) TO anon;
GRANT EXECUTE ON FUNCTION public.fonds_cout_revient_reference(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fonds_cout_revient_reference(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.fonds_cout_revient_reference(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.fonds_crediter_atteste(text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fonds_crediter_atteste(text,text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.fonds_crediter_atteste(text,text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.fonds_definir_types(text,text,text[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fonds_definir_types(text,text,text[]) TO postgres;
GRANT EXECUTE ON FUNCTION public.fonds_definir_types(text,text,text[]) TO service_role;
GRANT EXECUTE ON FUNCTION public.fonds_generiques_accessibles(text) TO anon;
GRANT EXECUTE ON FUNCTION public.fonds_generiques_accessibles(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fonds_generiques_accessibles(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.fonds_generiques_accessibles(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.fonds_matiere_apporter(text,text,text,text,integer,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fonds_matiere_apporter(text,text,text,text,integer,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.fonds_matiere_apporter(text,text,text,text,integer,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.fonds_matiere_parametres(text,text,text,numeric,integer,boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fonds_matiere_parametres(text,text,text,numeric,integer,boolean) TO postgres;
GRANT EXECUTE ON FUNCTION public.fonds_matiere_parametres(text,text,text,numeric,integer,boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.fonds_matieres_accessibles(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fonds_matieres_accessibles(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.fonds_matieres_accessibles(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.fonds_matieres_recherchees(text) TO anon;
GRANT EXECUTE ON FUNCTION public.fonds_matieres_recherchees(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fonds_matieres_recherchees(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.fonds_matieres_recherchees(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.fonds_plafond_stock_matiere(text) TO anon;
GRANT EXECUTE ON FUNCTION public.fonds_plafond_stock_matiere(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fonds_plafond_stock_matiere(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.fonds_plafond_stock_matiere(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.fonds_reference_activer(text,text,text,boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fonds_reference_activer(text,text,text,boolean) TO postgres;
GRANT EXECUTE ON FUNCTION public.fonds_reference_activer(text,text,text,boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.fonds_reference_creer(text,text,text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fonds_reference_creer(text,text,text,text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.fonds_reference_creer(text,text,text,text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.fonds_reference_modifier(text,text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fonds_reference_modifier(text,text,text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.fonds_reference_modifier(text,text,text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.fonds_reference_prix(text,text,text,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fonds_reference_prix(text,text,text,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.fonds_reference_prix(text,text,text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.fonds_reference_produire(text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fonds_reference_produire(text,text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.fonds_reference_produire(text,text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.fonds_reference_produire_lots(text,text,text,text,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fonds_reference_produire_lots(text,text,text,text,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.fonds_reference_produire_lots(text,text,text,text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.fonds_reference_stock_max(text,text,text,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fonds_reference_stock_max(text,text,text,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.fonds_reference_stock_max(text,text,text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.fonds_references_max(text) TO anon;
GRANT EXECUTE ON FUNCTION public.fonds_references_max(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fonds_references_max(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.fonds_references_max(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.fonds_rembourser(uuid,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fonds_rembourser(uuid,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.fonds_rembourser(uuid,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.fonds_types_max(text) TO anon;
GRANT EXECUTE ON FUNCTION public.fonds_types_max(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fonds_types_max(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.fonds_types_max(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pa_bonus_chambre(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.pa_bonus_chambre(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pa_bonus_chambre(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pa_bonus_differe_crediter(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.pa_bonus_differe_crediter(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pa_bonus_differe_crediter(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pa_bonus_differes_empreinte_reelle() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.pa_bonus_differes_empreinte_reelle() TO authenticated;
GRANT EXECUTE ON FUNCTION public.pa_bonus_differes_empreinte_reelle() TO postgres;
GRANT EXECUTE ON FUNCTION public.pa_bonus_differes_empreinte_reelle() TO service_role;
GRANT EXECUTE ON FUNCTION public.pa_crediter_atteste(text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.pa_crediter_atteste(text,text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pa_crediter_atteste(text,text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.pa_crediter_interne(text,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.pa_crediter_interne(text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.pa_repos_nocturne(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.pa_repos_nocturne(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.pa_repos_nocturne(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.percevoir_salaire_directeur(text,text,text,text,text,text,numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.percevoir_salaire_directeur(text,text,text,text,text,text,numeric) TO postgres;
GRANT EXECUTE ON FUNCTION public.percevoir_salaire_directeur(text,text,text,text,text,text,numeric) TO service_role;
GRANT EXECUTE ON FUNCTION public.redressement_fiscal_appliquer(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.redressement_fiscal_appliquer(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.redressement_fiscal_appliquer(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.retirer_caisse_fonds(text,text,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.retirer_caisse_fonds(text,text,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.retirer_caisse_fonds(text,text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.salaire_caisse_de(text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.salaire_caisse_de(text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.salaire_caisse_de(text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.salaire_civil_percevoir() TO authenticated;
GRANT EXECUTE ON FUNCTION public.salaire_civil_percevoir() TO postgres;
GRANT EXECUTE ON FUNCTION public.salaire_civil_percevoir() TO service_role;
GRANT EXECUTE ON FUNCTION public.salaire_religieux_percevoir() TO authenticated;
GRANT EXECUTE ON FUNCTION public.salaire_religieux_percevoir() TO postgres;
GRANT EXECUTE ON FUNCTION public.salaire_religieux_percevoir() TO service_role;
GRANT EXECUTE ON FUNCTION public.salaire_ville_du_poste(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.salaire_ville_du_poste(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.salaire_ville_du_poste(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.salaires_coherence() TO postgres;
GRANT EXECUTE ON FUNCTION public.salaires_coherence() TO service_role;
GRANT EXECUTE ON FUNCTION public.subvention_citoyen_verser(text,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.subvention_citoyen_verser(text,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.subvention_citoyen_verser(text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.vente_structure_encaisser(text,integer,integer,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.vente_structure_encaisser(text,integer,integer,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.vente_structure_encaisser(text,integer,integer,text,text) TO service_role;

-- DROITS SUR LES SEQUENCES
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.caisses_mouvements_clients_id_seq TO postgres;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.caisses_mouvements_clients_id_seq TO service_role;
GRANT SELECT, USAGE ON SEQUENCE public.contributions_piete_id_seq TO anon;
GRANT SELECT, USAGE ON SEQUENCE public.contributions_piete_id_seq TO authenticated;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.contributions_piete_id_seq TO postgres;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.contributions_piete_id_seq TO service_role;
GRANT SELECT, USAGE ON SEQUENCE public.fonds_credits_uniques_id_seq TO anon;
GRANT SELECT, USAGE ON SEQUENCE public.fonds_credits_uniques_id_seq TO authenticated;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.fonds_credits_uniques_id_seq TO postgres;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.fonds_credits_uniques_id_seq TO service_role;

-- DROITS SUR LES TABLES
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.budget_national_champs_regles TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.budget_national_champs_regles TO service_role;
GRANT SELECT ON TABLE public.budgets_clubs TO anon;
GRANT INSERT, SELECT, UPDATE ON TABLE public.budgets_clubs TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.budgets_clubs TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.budgets_clubs TO service_role;
GRANT SELECT ON TABLE public.budgets_municipaux TO anon;
GRANT INSERT, SELECT, UPDATE ON TABLE public.budgets_municipaux TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.budgets_municipaux TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.budgets_municipaux TO service_role;
GRANT SELECT ON TABLE public.budgets_nationaux TO anon;
GRANT INSERT, SELECT, UPDATE ON TABLE public.budgets_nationaux TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.budgets_nationaux TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.budgets_nationaux TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.caisses_autorites TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.caisses_autorites TO service_role;
GRANT SELECT ON TABLE public.caisses_batiments TO anon;
GRANT SELECT ON TABLE public.caisses_batiments TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.caisses_batiments TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.caisses_batiments TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.caisses_mouvements_clients TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.caisses_mouvements_clients TO service_role;
GRANT SELECT ON TABLE public.contributions_piete TO anon;
GRANT INSERT, SELECT ON TABLE public.contributions_piete TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.contributions_piete TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.contributions_piete TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.directions_etablissements TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.directions_etablissements TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.dotations_amorcage_caisses TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.dotations_amorcage_caisses TO service_role;
GRANT SELECT ON TABLE public.fiscalite_journal TO anon;
GRANT SELECT ON TABLE public.fiscalite_journal TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.fiscalite_journal TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.fiscalite_journal TO service_role;
GRANT SELECT ON TABLE public.fonds_credits_sources TO anon;
GRANT SELECT ON TABLE public.fonds_credits_sources TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.fonds_credits_sources TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.fonds_credits_sources TO service_role;
GRANT SELECT ON TABLE public.fonds_credits_uniques TO anon;
GRANT SELECT ON TABLE public.fonds_credits_uniques TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.fonds_credits_uniques TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.fonds_credits_uniques TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.fonds_debits TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.fonds_debits TO service_role;
GRANT SELECT ON TABLE public.pa_bonus_differes TO anon;
GRANT SELECT ON TABLE public.pa_bonus_differes TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pa_bonus_differes TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pa_bonus_differes TO service_role;
GRANT SELECT ON TABLE public.pa_bonus_differes_empreinte TO anon;
GRANT SELECT ON TABLE public.pa_bonus_differes_empreinte TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pa_bonus_differes_empreinte TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pa_bonus_differes_empreinte TO service_role;
GRANT SELECT ON TABLE public.pa_bonus_hotel TO anon;
GRANT SELECT ON TABLE public.pa_bonus_hotel TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pa_bonus_hotel TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pa_bonus_hotel TO service_role;
GRANT SELECT ON TABLE public.pa_credits_sources TO anon;
GRANT SELECT ON TABLE public.pa_credits_sources TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pa_credits_sources TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pa_credits_sources TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pa_credits_uniques TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.pa_credits_uniques TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.repartitions_budgetaires TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.repartitions_budgetaires TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.repartitions_versements TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.repartitions_versements TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.salaires_caisses TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.salaires_caisses TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.salaires_civils_declares TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.salaires_civils_declares TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.salaires_civils_verses TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.salaires_civils_verses TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.salaires_religieux_declares TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.salaires_religieux_declares TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.salaires_religieux_verses TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.salaires_religieux_verses TO service_role;
