-- Commentaires d'objets
-- ============================================================================
-- BASELINE Human Gambit -- domaine finances publiques -- phase 80 : commentaires
--
-- Fichier GENERE par outils/baseline/rendre.py depuis les catalogues
-- PostgreSQL. Ne pas editer a la main : toute correction passe par une
-- migration, puis par une nouvelle extraction.
--
-- ORDRE D'APPLICATION : par PHASE croissante, tous domaines confondus, et non
-- domaine par domaine. Voir baseline/README.md.
-- ============================================================================

COMMENT ON COLUMN public.repartitions_budgetaires.beneficiaire IS 'Motif de caisse beneficiaire. Quand il est egal a la source, la ligne est journalisee mais JAMAIS transferee : c''est la part que le repartiteur conserve.';
COMMENT ON COLUMN public.repartitions_budgetaires.part_denominateur IS 'Denominateur de la part. Vaut 100 quand la regle s''exprime naturellement en pourcentage, et autre chose quand elle ne s''y exprime pas EXACTEMENT : trois parts rigoureusement egales sont 1/3, que 33,33 % ne sait pas ecrire. Un pourcentage est le cas particulier d''une fraction sur cent.';
COMMENT ON COLUMN public.repartitions_budgetaires.part_numerateur IS 'Numerateur de la part, sur part_denominateur. NULL = part NON ARBITREE, que budget_repartir ignore entierement. ZERO = part DECIDEE a zero : le beneficiaire est reconnu, la regle s''applique et verse zero. Ne jamais confondre les deux, et ne jamais ecrire coalesce(part_numerateur, 0).';
COMMENT ON COLUMN public.repartitions_budgetaires.source IS 'Motif de caisse source, au sens de caisses_autorites : le suffixe qui suit <pays>_.';
COMMENT ON COLUMN public.repartitions_versements.part_denominateur IS 'La part EXACTE appliquee ce jour-la, denominateur.';
COMMENT ON COLUMN public.repartitions_versements.part_numerateur IS 'La part EXACTE appliquee ce jour-la, numerateur. Avec base et part_denominateur, le montant verse se recalcule au franc depuis la seule trace.';
COMMENT ON COLUMN public.salaires_civils_declares.pays IS 'L''empire pour lequel ce bareme est declare. Un empire sans ligne recoit bareme_absent, jamais les valeurs de Republia.';
COMMENT ON FUNCTION public.alimenter_caisse_fonds(text,text,integer) IS 'Le proprietaire d''un fonds de commerce verse du NUMERAIRE dans sa caisse. Exige l''identite de l''acteur. Debite arg ET liquide (une caisse contient des especes : un solde bancaire n''est pas debitable par cette voie), ou la caisse de l''organisation proprietaire. Transfert reel, jamais une creation de monnaie.';
COMMENT ON FUNCTION public.budget_cascade_quotidienne(text,numeric) IS 'La cascade budgetaire quotidienne, en UNE transaction : les recettes entrent chez le repartiteur (MEco), qui repartit vers les dix caisses nationales en conservant sa part, puis chaque ministere repartit vers les institutions de son ressort sur la base de ce qu''il vient de recevoir (lu dans le journal). Un empire sans ligne declaree ne recoit rien. RESERVEE AU SERVEUR.';
COMMENT ON FUNCTION public.budget_coherence() IS 'Cinq invariants de l''architecture budgetaire, verifies en FRACTIONS EXACTES : aucune somme de parts au-dela du tout (trois tiers font UN, pas 100,01), aucun beneficiaire a part NON NULLE sans caisse en base (les parts a 0 comptent -- la regle existe), aucun poste d''autorite inconnu, aucun double versement le meme jour, et aucune caisse financee par deux sources differentes (une caisse, un financeur recurrent).';
COMMENT ON FUNCTION public.budget_municipal_cascade(text) IS 'Cascade municipale de minuit : pour chaque VRAIE ville du pays, repartit les recettes municipales DU JOUR -- somme des lignes de recettes_municipales -- selon repartitions_budgetaires, par la brique generique budget_repartir. La base n''est jamais le solde de la caisse mairie, qui accumule la part conservee. L''idempotence vit dans la cle primaire de repartitions_versements. Une ville sans repartition declaree est ignoree : aucun repli sur la configuration de Republia. RESERVEE AU SERVEUR.';
COMMENT ON FUNCTION public.budget_part_totale(text,text) IS 'La somme des parts declarees d''une source, rendue comme UNE SEULE FRACTION exacte (numerateur, denominateur). Aucune division intermediaire : trois tiers rendent 3/3, et non 0,99999999999999999999 -- la division numeric s''arrete a une vingtaine de decimales et trois tiers inexacts ne refont pas un. SEUL endroit du systeme ou cette arithmetique vit ; budget_repartir, budget_repartition_fixer, budget_repartition_lire et budget_coherence l''appellent toutes.';
COMMENT ON FUNCTION public.budget_repartir(text,text,numeric) IS 'Execute la repartition declaree pour (pays, source) sur une base donnee. La part est une FRACTION EXACTE (numerateur sur denominateur) : trois parts rigoureusement egales s''ecrivent 1/3, ce qu''aucun pourcentage decimal ne sait faire. Plus fort reste, aucun FR perdu. A EGALITE de reste, le departage TOURNE avec le jour -- deterministe pour une journee donnee, sans preference permanente pour un beneficiaire. Les parts NULL sont ignorees (rien n''est invente) ; les parts a 0 sont appliquees et journalisees a montant nul (la regle existe et donne zero). La ligne dont le beneficiaire est la source est journalisee mais jamais transferee : c''est ce qui empeche la boucle. La cle primaire du journal porte le jour : la double distribution est impossible par construction. RESERVEE AU SERVEUR.';
COMMENT ON FUNCTION public.budget_repartition_fixer(text,text,numeric) IS 'Fixe la part d''un beneficiaire declare. L''acteur vient de mon_personnage(), son pays et son poste de sa fiche : le navigateur n''annonce jamais son droit. La ligne doit exister -- on ne cree pas un beneficiaire depuis un navigateur. Le parametre est un POURCENTAGE, stocke en fraction sur cent ; la somme des parts d''une source est verifiee en FRACTIONS EXACTES par budget_part_totale() et ne peut jamais depasser le tout -- un refus restaure l''ancienne valeur dans la meme transaction. Modifier une part exprimee en tiers la ramene a un pourcentage : c''est la decision du ministre, et l''ecran lui montre la fraction avant qu''il la remplace.';
COMMENT ON FUNCTION public.budget_repartition_lire(text) IS 'Lit la repartition declaree d''une source, pour l''interface. UNE regle -- la FRACTION EXACTE num/den -- et TROIS representations, toutes calculees a la lecture donc incapables de diverger : le pourcentage arrondi (ce que l''interface fait saisir), la fraction ecrite en clair (pour que l''ecran puisse dire 1/3 la ou 33,3333 % mentirait), et l''equivalent en FR calcule sur le dernier versement REELLEMENT recu par la source. total_pourcent est la somme EXACTE des parts : trois tiers rendent 100,0000. base_reference NULL = la source n''a encore rien recu, et l''interface doit le dire plutot qu''inventer un montant.';
COMMENT ON FUNCTION public.caisse_refus_autorite(text,text) IS 'Le verdict d''autorite sur une sortie d''argent d''une caisse, ecrit UNE fois pour les trois primitives de mouvement. Rend NULL si l''acteur a l''autorite, sinon le motif du refus. Absence de regle = REFUS (caisse_sans_regle_autorite), jamais autorisation implicite.';
COMMENT ON FUNCTION public.caisse_territoire(text,text) IS 'Portee territoriale d''une caisse : national (aucune ville a verifier), ville (territoriale, ville connue) ou indetermine (REFUS). Separe deliberement « nationale » de « ville inconnue », que l''ancien caisse_ville_de confondait en un seul NULL.';
COMMENT ON FUNCTION public.caisse_ville_de(text,text) IS 'La VRAIE ville d''une caisse territoriale, ou NULL. ATTENTION : NULL ne dit pas « nationale » -- il dit seulement « pas de ville ». Pour decider d''une autorite, interroger caisse_territoire(), qui distingue national de indetermine.';
COMMENT ON FUNCTION public.fonds_acteur_present(text,jsonb) IS 'RELAIS (30 septembre 2026) vers acteur_present_sur_site, a partir de l''implantation d''un fonds PJ. Ne contient plus de regle de localisation propre : il n''en existe qu''une dans le jeu.';
COMMENT ON FUNCTION public.fonds_cout_revient_reference(text,text) IS 'Cout de reference d''une reference : le COUT MOYEN PONDERE de son stock de produits finis, c''est-a-dire ce que le commercant a reellement paye pour fabriquer ce qui est en rayon. Une baisse ulterieure du prix des matieres ne reecrit donc jamais le cout d''un produit deja fabrique. Rend disponible=false tant qu''aucun lot n''a ete produit.';
COMMENT ON FUNCTION public.fonds_definir_types(text,text,text[]) IS 'Declare les types de commerce L2 d''un fonds PJ. Plusieurs types possibles, tous valides contre catalogue_types, plafond lu dans entreprises_constantes. Remplace la liste complete. Reserve au proprietaire du fonds.';
COMMENT ON FUNCTION public.fonds_generiques_accessibles(text) IS 'Generiques qu''un fonds peut decliner en references : croisement de ses typesAutorises avec le referentiel L2, RESTREINT aux generiques pour lesquels il existe au moins une recette systeme. Un generique sans recette n''est jamais propose : le joueur ne peut plus aboutir a un produit non fabricable.';
COMMENT ON FUNCTION public.fonds_matiere_apporter(text,text,text,text,integer,text) IS 'Apport d''une matiere premiere a un fonds PJ, par vente (prix fixe par le proprietaire) ou par don. Exige la presence physique ET que le proprietaire ait explicitement ACCEPTE cette matiere. Perimetre derive des activites du commerce. Borne la quantite par la possession reelle, la place restante et la caisse. Met a jour le CMUP. Idempotente par cle de requete.';
COMMENT ON FUNCTION public.fonds_matiere_parametres(text,text,text,numeric,integer,boolean) IS 'Reglages d''une matiere pour un fonds PJ : prix de rachat libre et stock maximum (0 = le commerce n''en veut pas, borne par le plafond du pays). Le perimetre autorise est celui des ACTIVITES du commerce. p_acceptee est conserve pour la compatibilite de signature mais IGNORE : l''acceptation se deduit du maximum.';
COMMENT ON FUNCTION public.fonds_matieres_accessibles(text) IS 'Matieres qu''un fonds PJ PEUT manipuler, derivees de ses activites (typesAutorises -> generiques -> recettes -> materiaux), avec son stock, son stock maximum et son prix de rachat. LE MAXIMUM EST LA SEULE GRANDEUR : 0 signifie que le commerce refuse la matiere, un maximum non declare vaut 2, et le plafond du pays borne le tout. La colonne acceptee est CALCULEE (maximum > 0) et conservee pour la garde de fonds_matiere_apporter.';
COMMENT ON FUNCTION public.fonds_matieres_recherchees(text) IS 'Matieres premieres qu''un fonds PJ recherche, DEDUITES des recettes systeme de ses references (actives ou non). Rend pour chacune le stock, le maximum choisi par le proprietaire, le plafond du pays, le prix de rachat affiche et la place restante.';
COMMENT ON FUNCTION public.fonds_plafond_stock_matiere(text) IS 'Plafond de stock d''une matiere premiere dans un fonds de commerce PJ. Politique economique PAR PAYS, lue dans entreprises_constantes. Rend NULL pour un pays non arbitre : aucune valeur n''est inventee, l''approvisionnement y est refuse.';
COMMENT ON FUNCTION public.fonds_reference_activer(text,text,text,boolean) IS 'Met une reference en vente ou la retire, sans jamais la supprimer : une transaction passee doit pouvoir continuer a la designer. Le plafond porte sur les references actives. Une reference sans prix ne peut pas etre activee.';
COMMENT ON FUNCTION public.fonds_reference_creer(text,text,text,text,text,text) IS 'Cree une reference commerciale sur un generique autorise par les types L2 du fonds, avec la recette systeme choisie parmi celles de ce generique. Le choix de recette est obligatoire des lors que le generique en possede, et FIGE : commercialiser une autre recette demande une autre reference.';
COMMENT ON FUNCTION public.fonds_reference_modifier(text,text,text,text,text) IS 'Modifie l''habillage commercial d''une reference : nom et description uniquement. N''accepte aucun parametre mecanique -- generique_id et variante_id sont structurellement inatteignables par cette porte.';
COMMENT ON FUNCTION public.fonds_reference_prix(text,text,text,integer) IS 'Fixe le prix de vente d''une reference. Plafond SERVEUR : cout de revient unitaire x coefficient du pays. Refuse tout prix lorsque le cout n''est pas calculable -- jamais de cout suppose a zero, jamais de plafond invente.';
COMMENT ON FUNCTION public.fonds_reference_produire(text,text,text,text) IS 'Fabrique UN lot d''une reference PJ. Relais vers fonds_reference_produire_lots(..., 1) : toute l''economie de la production vit desormais la-bas, et cette porte-ci existe pour le parcours visiteur et les appels historiques, a comportement identique.';
COMMENT ON FUNCTION public.fonds_reference_produire_lots(text,text,text,text,integer) IS 'Fabrique de 1 a 99 lots d''une reference PJ en UNE transaction. Ouverte a tout joueur physiquement present : le commerce fournit ses matieres et paie 50 FR par PA depense, le producteur fournit ses PA, le produit va au stock du commerce. La commande est indivisible comme le rendement : PA, matieres, stock maximum ou caisse insuffisants pour le TOTAL refusent la commande entiere avant la premiere ecriture -- jamais de demi-production. Idempotente par cle de requete, et laisse une seule ligne de preuve aux grandeurs agregees.';
COMMENT ON FUNCTION public.fonds_reference_stock_max(text,text,text,integer) IS 'Stock maximum souhaite pour UNE reference (data->parametres->stockMaxReferences). Grandeur DISTINCTE du maximum des matieres. Stockee et affichee ; volontairement non opposee a la production tant que le comportement du depassement par le rendement d''une recette n''est pas arbitre.';
COMMENT ON FUNCTION public.fonds_references_max(text) IS 'Nombre maximum de references qu''un commerce peut POSSEDER (son catalogue), gratuit = 4. Oppose une seule fois, a la creation. Retirer une reference de la vente ne libere aucune place : elle appartient toujours au commerce. Le parametre proprietaire est conserve pour qu''un statut Premium puisse relever ce plafond sans changer d''appelants.';
COMMENT ON FUNCTION public.fonds_types_max(text) IS 'Nombre maximal de types de commerce L2 qu''un fonds peut declarer. Lu dans entreprises_constantes, jamais code en dur. Point d''extension unique pour une future differenciation par offre : le proprietaire est deja recu en parametre, mais aucun statut d''abonnement n''existe encore en base.';
COMMENT ON FUNCTION public.mairie_virement_batiment(text,numeric) IS 'Virement ponctuel de la caisse de la mairie vers la caisse d''un batiment de SA commune, par le maire ou son adjoint. Debit et credit dans la meme transaction : aucune fenetre ou l''argent a quitte la mairie sans arriver, ni l''inverse. La cible doit etre territorialement dans la ville du poste -- une caisse nationale ou d''une autre commune est refusee.';
COMMENT ON FUNCTION public.pa_bonus_differes_empreinte_reelle() IS 'Empreinte reelle du miroir des bonus de PA differes. Pendant SQL de outils/generateurs/generer_pa_bonus_differes.py. Chantier 4C.';
COMMENT ON FUNCTION public.percevoir_salaire_directeur(text,text,text,text,text,text,numeric) IS 'Le montant, la ville et le batiment viennent de directions_etablissements, JAMAIS des parametres : p_pays, p_ville, p_batiment, p_souscle et p_montant sont ignores et ne subsistent que pour la compatibilite de deploiement.';
COMMENT ON FUNCTION public.preemption_mensualite_prelever(text) IS 'Preleve la mensualite de la preemption d''Etat d''un pays : debit de la caisse du Ministere des
Finances ET reduction de la dette, dans UNE SEULE transaction ouverte par une revendication
d''acte nocturne. Appelable par service_role seulement (le cron).
VERDICTS : aucun_budget, aucune_preemption, preemption_illisible (fail-closed, aucun mouvement,
journee non prise), deja_traite, reporte (caisse insuffisante -- dette intacte), preleve, solde.';
COMMENT ON FUNCTION public.recette_municipale(text,text,numeric,text) IS 'SEUL point d''entree d''une recette municipale. Credite caisses_batiments.<pays>_mairie_<ville> -- la SEULE tresorerie -- et incremente la ligne du jour de recettes_municipales, qui est une MESURE et non une bourse. Les deux ecritures sont dans la meme transaction. N''arrondit rien. Refuse toute ville absente du referentiel `villes` : la caserne, le QHS et les villes de test n''encaissent rien. RESERVEE AU SERVEUR.';
COMMENT ON FUNCTION public.retirer_caisse_fonds(text,text,integer) IS 'Le proprietaire reprend du NUMERAIRE dans la caisse de son fonds. Exige l''identite de l''acteur. Credite arg ET liquide, ou la caisse de l''organisation proprietaire. Ce n''est pas un revenu : ce qui sort de la caisse entre dans le patrimoine, et rien d''autre.';
COMMENT ON FUNCTION public.salaire_civil_percevoir() IS 'Bareme de poste, puis emploi BNE, puis revenu universel -- chacun cherche DANS L''EMPIRE de l''acteur. Un empire sans bareme recoit bareme_absent, jamais les valeurs de Republia. Le revenu universel est attache au citoyen : il n''est pas supprime parce que l''acteur percoit un salaire de direction (arbitrage du 7 octobre 2026, Republia uniquement).';
COMMENT ON FUNCTION public.salaires_coherence() IS 'Quatre invariants des baremes. Les deux derniers protegent l''arbitrage du 7 octobre 2026 : un poste de direction ne doit jamais etre declare en bareme de poste (il perdrait le revenu universel), et aucun bareme ne doit exister sans empire declare.';
COMMENT ON TABLE public.budgets_municipaux IS 'CONFIGURATION municipale, et plus une tresorerie. Porte les taux fixes par le maire (tauxFoncier, tauxLocal) et les indices de la ville. La tresorerie d''une mairie est caisses_batiments.<pays>_mairie_<ville>, et elle seule ; la mesure des recettes du jour est recettes_municipales. Les cles `caisse`, `allocation` et `derniereDistribJour` ont ete retirees le 8 octobre 2026 : la premiere etait une seconde bourse, la deuxieme une seconde regle de repartition, la troisieme le marqueur d''une distribution cliente qui n''existe plus.';
COMMENT ON TABLE public.directions_etablissements IS 'Quel etablissement chaque poste de direction dirige, ou, et pour quel salaire quotidien. C''est cette table que lit percevoir_salaire_directeur : ni la ville ni le batiment ni le montant ne viennent plus du navigateur.';
COMMENT ON TABLE public.pa_credits_sources IS 'LISTE BLANCHE des sources de credit de PA, avec le montant autorise. Lue par pa_crediter_atteste, qui credite exactement ce montant. ECRITURE FERMEE AU CLIENT le 26 septembre 2026 : y inserer une ligne equivalait a s''octroyer des PA sans limite, la garde pa_credits_uniques ne portant que sur la reference. Ne jamais rouvrir INSERT/UPDATE a anon ni a authenticated.';
COMMENT ON TABLE public.recettes_municipales IS 'COMPTEUR des recettes municipales percues, par commune, par jour et par canal. Ce n''est PAS une tresorerie : aucune fonction n''en soustrait jamais, et le CHECK montant > 0 l''interdit. L''argent correspondant est, lui, deja dans caisses_batiments.<pays>_mairie_<ville>, credite a l''instant de la perception. Cette table dit seulement COMBIEN est arrive, pour que la cascade de minuit connaisse sa base. Equivalent municipal de budgets_nationaux.data.reserveJour, a ceci pres que reserveJour porte l''argent et que ce compteur n''en porte pas.';
COMMENT ON TABLE public.repartitions_budgetaires IS 'Qui repartit son budget vers qui, quelle part, et quel poste peut la modifier. UNE seule table pour les deux niveaux : le national est la repartition dont la source est la caisse du Ministere de l''Economie et des Finances, qui figure parmi ses propres beneficiaires. part_pourcent NULL = non arbitre (la fonction ne verse rien) ; 0 = decide a zero.';
COMMENT ON TABLE public.repartitions_versements IS 'Journal des versements de repartition, une ligne par (pays, source, beneficiaire, jour). La cle primaire porte le jour : elle rend la double distribution impossible par construction, et non par un marqueur qu''une ecriture avalee peut perdre. transfere=false marque la part que le repartiteur conserve (beneficiaire = source) : elle est journalisee pour que le circuit soit lisible, mais aucun mouvement n''a lieu.';
