-- ============================================================================
-- MIGRATION HISTORIQUE -- DEJA APPLIQUEE -- NE PAS EXECUTER
-- ============================================================================
-- Version Supabase  : 20260927235118
-- Nom original      : catalogue_objets_seed_correspondances
-- Categorie         : DML -- DML seul (mutation de donnees)
-- Date (deduite de la version) : 2026-09-27 23:51:18 UTC
-- Etat              : DEJA APPLIQUEE A LA BASE DE PRODUCTION
-- MD5 du SQL historique : 6d2471baa76293df922393bcc6c1843c
--
-- ARCHIVE DOCUMENTAIRE exportee de supabase_migrations.schema_migrations.
-- Ce fichier NE FAIT PAS partie d'une chaine de reconstruction et NE DOIT
-- PAS etre rejoue, ni execute automatiquement, ni servir a installer une
-- base neuve. Voir historique/registre-supabase/README.md.
--
-- Le SQL ci-dessous est conserve INTEGRALEMENT, SANS AUCUNE MODIFICATION :
-- ni correction, ni mise en forme, ni separation des parties DDL et DML,
-- ni ajout d'idempotence. On archive ce qui s'est reellement passe.
-- ============================================================================
-- >>> DEBUT DU SQL HISTORIQUE -- ne rien inserer au-dessus de cette ligne <<<
insert into public.catalogue_generique_type (generique_id, type_id) values
  ('arme-blanche','armurerie'),('arme-de-poing','armurerie'),('arme-longue','armurerie'),
  ('accessoire-d-arme','armurerie'),('explosif','armurerie'),
  ('protection-corporelle','armurerie'),('protection-corporelle','sport-loisirs'),
  ('livre','arts-culture'),('imprime','arts-culture'),('affiche','arts-culture'),
  ('oeuvre-d-art','arts-culture'),('instrument-de-musique','arts-culture'),
  ('support-culturel','arts-culture'),('spectacle','arts-culture'),
  ('encas','bar-restauration'),('plat-simple','bar-restauration'),
  ('plat-elabore','bar-restauration'),('menu-gastronomique','bar-restauration'),
  ('boisson','bar-restauration'),('boisson','commerce-alimentaire'),
  ('produit-cosmetique','bien-etre-mode'),('coiffure','bien-etre-mode'),
  ('soin-esthetique','bien-etre-mode'),('tatouage','bien-etre-mode'),
  ('piercing','bien-etre-mode'),('bijou','bien-etre-mode'),('accessoire-de-mode','bien-etre-mode'),
  ('outil-a-main','bricolage-outillage'),('outil-electrique','bricolage-outillage'),
  ('equipement-professionnel','bricolage-outillage'),('materiau-de-construction','bricolage-outillage'),
  ('fourniture-de-bricolage','bricolage-outillage'),('equipement-de-protection-professionnelle','bricolage-outillage'),
  ('aliment-brut','commerce-alimentaire'),('aliment-prepare','commerce-alimentaire'),
  ('encas-a-emporter','commerce-alimentaire'),('encas-a-emporter','bar-restauration'),
  ('vegetal','commerce-non-alimentaire'),('animal-de-compagnie','commerce-non-alimentaire'),
  ('accessoire-pour-animal','commerce-non-alimentaire'),('article-du-quotidien','commerce-non-alimentaire'),
  ('souvenir','commerce-non-alimentaire'),('carte-postale','commerce-non-alimentaire'),
  ('article-de-supporter','commerce-non-alimentaire'),('article-de-supporter','sport-loisirs'),
  ('objet-de-collection','commerce-non-alimentaire'),
  ('appareil-de-communication','electronique-informatique'),('ordinateur-complet','electronique-informatique'),
  ('peripherique-informatique','electronique-informatique'),('appareil-electronique','electronique-informatique'),
  ('camera-de-surveillance','electronique-informatique'),('console-de-jeu','electronique-informatique'),
  ('jeu-video','electronique-informatique'),
  ('voiture','garage-automobile'),('deux-roues','garage-automobile'),
  ('vehicule-utilitaire','garage-automobile'),('piece-automobile','garage-automobile'),
  ('accessoire-automobile','garage-automobile'),('produit-d-entretien-automobile','garage-automobile'),
  ('reparation','garage-automobile'),('installation-de-piece','garage-automobile'),
  ('hebergement-standard','hotellerie-hebergement'),('hebergement-superieur','hotellerie-hebergement'),
  ('hebergement-prestige','hotellerie-hebergement'),
  ('meuble-de-rangement','maison-decoration'),('meuble-de-repos','maison-decoration'),
  ('meuble-de-prestige','maison-decoration'),('objet-decoratif','maison-decoration'),
  ('decoration-murale','maison-decoration'),('equipement-domestique','maison-decoration'),
  ('luminaire','maison-decoration'),
  ('medicament','pharmacie'),('materiel-de-premiers-secours','pharmacie'),
  ('soin-pharmaceutique','pharmacie'),('produit-de-sante','pharmacie'),
  ('equipement-sportif','sport-loisirs'),('activite-sportive','sport-loisirs'),
  ('equipement-de-plein-air','sport-loisirs'),('tente','sport-loisirs'),
  ('jeu','sport-loisirs'),('jouet','sport-loisirs'),
  ('costume-complet','vetements'),('haut','vetements'),('bas','vetements'),
  ('chaussures','vetements'),('accessoire-vestimentaire','vetements'),
  ('tenue-militaire','vetements'),('accessoire-militaire','vetements')
on conflict (generique_id, type_id) do nothing;

insert into public.catalogue_variantes (id, generique_id, cle, libelle, regime, capacites, note) values
  ('appareil-de-communication--militaire','appareil-de-communication','militaire','Radio de campagne','reglemente',
   '["transmettre_ordre_collectif_a_distance"]'::jsonb,
   'Exigee des DEUX cotes de la chaine de commandement (militaire_ordre_collectif, refus radio_manquante).'),
  ('tente--militaire','tente','militaire','Tente de campagne','reglemente',
   '["abriter_bivouac","reposer_section"]'::jsonb,
   'Abrite 13 personnes, leader compris. Non consommee, aucune usure.'),
  ('equipement-de-plein-air--militaire','equipement-de-plein-air','militaire','Jumelles','reglemente',
   '["observer_secteur"]'::jsonb,
   'Ordre « Observer » a 1 PA via militaire_observer. Le chemin passif d''entree de zone est actuellement casse (anomalie documentee, non corrigee ici).'),
  ('materiel-de-premiers-secours--militaire','materiel-de-premiers-secours','militaire','Trousse de premiers secours','reglemente',
   '["soigner_co_present"]'::jsonb,
   'Usage unique. Co-presence stricte exigee si la cible n''est pas soi.'),
  ('protection-corporelle--militaire','protection-corporelle','militaire','Gilet pare-balles réglementaire','reglemente',
   '["absorber_tir_en_bataille"]'::jsonb,
   'Une seule chance, definitive : un gilet fragilise reste inerte, aucun code ne le repare.'),
  ('encas-a-emporter--militaire','encas-a-emporter','militaire','Ration de combat','reglemente',
   '["nourrir_soldat_pnj"]'::jsonb,
   'Consommable par le PJ ou distribuable a des soldats PNJ menes.')
on conflict (id) do update set
  libelle = excluded.libelle, regime = excluded.regime,
  capacites = excluded.capacites, note = excluded.note;

insert into public.catalogue_correspondance_legacy
  (motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) values
  ('type_soustype','arme|blanche','arme-blanche',null,100,null,
   'plateau-actions-illegales-rumeurs.js:1478 (affichage seul) ; getStatEffective ne lit jamais item.bonus',
   'bonus {VOL,5} declare, affiche, JAMAIS applique : absent des effets effectifs.'),
  ('type_soustype','arme|poing','arme-de-poing',null,100,null,
   'plateau-actions-illegales-rumeurs.js:1478 ; getStatEffective',
   'bonus {PER,8} declare, jamais applique.'),
  ('type_soustype','arme|carabine','arme-longue',null,100,null,
   'plateau-actions-illegales-rumeurs.js:1478 ; getStatEffective',
   'bonus {PER,15} declare, jamais applique.'),
  ('produit_militaire','arme_de_poing','arme-de-poing',null,200,'{"bonus_combat_feu": 8}'::jsonb,
   'table militaire_armes_bonus, lue par militaire_bataille_combattants',null),
  ('produit_militaire','mitraillette','arme-longue',null,200,'{"bonus_combat_feu": 15}'::jsonb,
   'table militaire_armes_bonus, lue par militaire_bataille_combattants',null),
  ('type_produit_militaire','explosif|explosif_militaire','explosif',null,300,
   '{"ferme_batiment_jours": 5, "blesse_presents": true}'::jsonb,
   'confirmerUtiliserExplosifs, plateau-actions-illegales-rumeurs.js:2248-2330','Exemplaire retire legalement.'),
  ('type_produit_militaire','arme|explosif_militaire','explosif',null,300,null,
   'doUtiliserExplosifs cherche type===''explosif'' (plateau-actions-illegales-rumeurs.js:2226) ; inventaire_consommer refuse objet_non_consommable',
   'ANOMALIE : exemplaire SUBTILISE, type ''arme''. Introuvable par le handler et refuse par la RPC. Objet inerte. Documente, non corrige.'),
  ('type','explosif','explosif',null,100,
   '{"ferme_batiment_jours": 5, "blesse_presents": true}'::jsonb,
   'confirmerUtiliserExplosifs','Explosif de chantier (marche noir).'),
  ('type','protection','protection-corporelle',null,100,null,
   'militaire_gilet_absorber cherche produitMilitaire=''gilet_pare_balles'', absent de cet objet',
   'Gilet civil a 600 FR : effet annonce, jamais cable. Documente, non corrige.'),
  ('produit_militaire','gilet_pare_balles','protection-corporelle','protection-corporelle--militaire',200,
   '{"absorption_tir_probabilite": 0.5, "une_seule_fois": true, "garantit_pa_minimum": 1, "condition": "bataille, mode feu uniquement"}'::jsonb,
   'militaire_gilet_absorber, appelee par militaire_bataille_appliquer',null),
  ('type_tracttype','tract|pour','imprime',null,200,'{"voix_pnj": 1}'::jsonb,
   'tracts_electoraux_distribuer_interne',null),
  ('type_tracttype','tract|contre','imprime',null,200,'{"voix_pnj": -1, "plancher": 0}'::jsonb,
   'tracts_electoraux_distribuer_interne',null),
  ('type','tract_calomnieux','imprime',null,100,'{"pop_cible": -5, "inf_cible": -2}'::jsonb,
   'calomnie_distribuer, verrou PNJ x cible x jour (calomnies_actes_verrou)',null),
  ('objet_id','tract|origineQuete=jean_lou','imprime',null,300,'{"voix_pnj": 1}'::jsonb,
   'plateau-pnj.js:621-624 (enregistrerVotePNJ)',
   'Objet de QUETE : hors catalogue commercial. Mappe pour que la fiche sache repondre.'),
  ('recette_id','snack_buvette','encas',null,100,'{"hp": 2, "moral": 1}'::jsonb,
   'recettes_commerce.effets ; applique par plateau-actions-illegales-rumeurs.js:4779-4781',null),
  ('recette_id','petit_dejeuner','encas',null,100,'{"hp": 3, "moral": 1}'::jsonb,'recettes_commerce.effets',null),
  ('recette_id','sandwich_cheminots','plat-simple',null,100,'{"hp": 5, "moral": 1}'::jsonb,'recettes_commerce.effets',null),
  ('recette_id','boeuf_bourguignon','plat-elabore',null,100,'{"hp": 8, "moral": 2}'::jsonb,'recettes_commerce.effets',null),
  ('recette_id','saucisse_puree','plat-elabore',null,100,'{"hp": 8, "moral": 2}'::jsonb,'recettes_commerce.effets',null),
  ('recette_id','plat_de_poisson','plat-elabore',null,100,'{"hp": 8, "moral": 2}'::jsonb,'recettes_commerce.effets',null),
  ('recette_id','carbonade_frites','plat-elabore',null,100,'{"hp": 8, "moral": 3}'::jsonb,
   'recettes_commerce.effets','Seul plat elabore a +3 Moral : specialite verrouillee sur ville_b.'),
  ('recette_id','menu_gastronomique_1','menu-gastronomique',null,100,'{"hp": 10, "moral": 1, "pa_differe": 3}'::jsonb,
   'recettes_commerce.effets ; PA differe atteste serveur par pa_bonus_differes',null),
  ('recette_id','menu_gastronomique_2','menu-gastronomique',null,100,'{"hp": 10, "moral": 1, "pa_differe": 3}'::jsonb,
   'recettes_commerce.effets ; pa_bonus_differes',null),
  ('recette_id','menu_gastronomique_3','menu-gastronomique',null,100,'{"hp": 10, "moral": 1, "pa_differe": 3}'::jsonb,
   'recettes_commerce.effets ; pa_bonus_differes',null),
  ('recette_id','menu_psm_1','menu-gastronomique',null,100,'{"hp": 10, "moral": 1, "pa_differe": 3}'::jsonb,
   'recettes_commerce.effets ; pa_bonus_differes',null),
  ('recette_id','menu_psm_2','menu-gastronomique',null,100,'{"hp": 10, "moral": 1, "pa_differe": 3}'::jsonb,
   'recettes_commerce.effets ; pa_bonus_differes',null),
  ('recette_id','menu_psm_3','menu-gastronomique',null,100,'{"hp": 10, "moral": 1, "pa_differe": 3}'::jsonb,
   'recettes_commerce.effets ; pa_bonus_differes',null),
  ('recette_id','biere_pression','boisson',null,100,'{"moral": 2}'::jsonb,'recettes_commerce.effets',null),
  ('recette_id','vin','boisson',null,100,'{"moral": 2}'::jsonb,
   'recettes_commerce.effets','Seule boisson exigee nommement par le diner d''affaires.'),
  ('recette_id','cafe_boisson','boisson',null,100,'{"moral": 2}'::jsonb,'recettes_commerce.effets',null),
  ('recette_id','jus_de_fruits','boisson',null,100,'{"moral": 2}'::jsonb,'recettes_commerce.effets',null),
  ('recette_id','boisson_sans_alcool','boisson',null,100,'{"moral": 1}'::jsonb,'recettes_commerce.effets',
   'ANOMALIE : seule recette a materiaux vides. Ne fait pas jurisprudence pour le generique.'),
  ('recette_id','sandwich','plat-simple',null,100,'{"hp": 5, "moral": 1, "pa_differe": 1}'::jsonb,
   'recettes_commerce.effets ; pa_bonus_differes',
   'ANOMALIE : retire de toutes les cartes, non produisible. Recette conservee dans les deux registres.'),
  ('famille_produit_marche','aliment','encas-a-emporter',null,100,
   '{"pa_si_frais": 1, "pa_si_perime": -1, "fraicheur_jours_reels": 7}'::jsonb,
   'inventaire_consommer (RPC) ; DUREE_FRAICHEUR_ALIMENT_MS, plateau-personnage.js:3253',
   'Aucun hp ni moral : ces produits n''ont aucune valeur nutritive codee.'),
  ('famille_produit_marche','carte_postale','carte-postale',null,100,
   '{"moral_lecteur": 10, "moral_expediteur": 10, "plafond_quotidien_lecteur": 1, "plafond_quotidien_expediteur": 1}'::jsonb,
   'plateau-personnage.js:3583-3592 (lecteur) ; plateau-communication.js:1688-1697 (expediteur, file impacts_indices_attente) ; colonne persistee carte_postale_moral_jour',
   'Deux plafonds quotidiens distincts sur la meme colonne persistee.'),
  ('recette_id','porte_cle_palais_luthecia','souvenir',null,100,null,
   'recettes_commerce.bonus_integration_ville = null',
   'Classe integration_locale SANS bonus : distinction mecanique avec les 3 textiles.'),
  ('recette_id','garde_republien_plomb','souvenir',null,100,null,
   'recettes_commerce.bonus_integration_ville = null',null),
  ('recette_id','figurine_maxence_monfils','souvenir',null,100,null,
   'recettes_commerce.bonus_integration_ville = null',null),
  ('type','accessoire_sport','article-de-supporter',null,100,null,
   'plateau-organisations-quetes.js:9026 ; aucun lecteur du type accessoire_sport',
   'Aucune recette, aucun stock, aucun effet. Fonctionnement preserve tel quel.'),
  ('stack_key','cereales','aliment-brut',null,100,null,'ressources_economie','Intrant (GD3).'),
  ('stack_key','viande','aliment-brut',null,100,null,'ressources_economie','Intrant (GD3).'),
  ('stack_key','poisson','aliment-brut',null,100,null,'ressources_economie','Intrant (GD3).'),
  ('stack_key','fruits_legumes','aliment-brut',null,100,null,'ressources_economie','Intrant (GD3).'),
  ('stack_key','produits_exotiques','aliment-brut',null,100,null,'ressources_economie','Intrant (GD3).'),
  ('recette_id','tshirt_psm','haut',null,100,
   '{"ent": 1, "condition": "presence_ville_a", "non_cumulable": true}'::jsonb,
   'bonusEntIntegrationLocale, plateau-organisations-quetes.js:3341-3345 ; lu par getStatEffective',
   'SEUL bonus reellement calcule depuis l''inventaire. Reste une propriete de CET objet, pas du generique Haut.'),
  ('recette_id','casquette_montrouge','accessoire-vestimentaire',null,100,
   '{"ent": 1, "condition": "presence_ville_b", "non_cumulable": true}'::jsonb,
   'bonusEntIntegrationLocale ; getStatEffective',null),
  ('recette_id','echarpe_luthecia','accessoire-vestimentaire',null,100,
   '{"ent": 1, "condition": "presence_capitale", "non_cumulable": true}'::jsonb,
   'bonusEntIntegrationLocale ; getStatEffective',null),
  ('produit_militaire','tenue_camouflage','tenue-militaire',null,200,
   '{"camouflage_groupe": 20, "condition": "porte par un soldat PNJ via pnj_possessions (origine blob_accessoires) ; AUCUN effet sur un PJ"}'::jsonb,
   'militaire_camouflage_groupe, lue par militaire_observer',
   'La description annoncee (« protege celui qui la porte ») est fausse pour un PJ. Documente, non corrige.'),
  ('produit_militaire','radio','appareil-de-communication','appareil-de-communication--militaire',200,null,
   'militaire_ordre_collectif (refus radio_manquante)',
   'Aucun delta : la capacite est portee par la variante.'),
  ('produit_militaire','tente','tente','tente--militaire',200,
   '{"pa_bivouac_par_soldat": 1, "pa_repos_section": 10, "pa_repos_nocturne_pj": 10, "capacite_personnes": 13, "consommee": false, "usure": null}'::jsonb,
   'militaire_ordre_collectif (bivouac) ; militaire_reposer_section ; pa_repos_nocturne ; plateau-multijoueur.js:2591',null),
  ('produit_militaire','jumelles','equipement-de-plein-air','equipement-de-plein-air--militaire',200,
   '{"bonus_detection": 30}'::jsonb,'militaire_observer -> militaire_chance_detection',null),
  ('produit_militaire','trousse_secours','materiel-de-premiers-secours','materiel-de-premiers-secours--militaire',200,
   '{"pa_formule": "2 + floor(min(100, secourisme)/25)", "pa_min": 2, "pa_max": 6, "plafond_pa": 30, "usage_unique": true, "condition": "co-presence exigee si la cible n''est pas soi"}'::jsonb,
   'militaire_trousse_utiliser',
   'competences_militaires est vide pour tous les personnages : le gain reel est aujourd''hui toujours +2.'),
  ('produit_militaire','ration_combat','encas-a-emporter','encas-a-emporter--militaire',200,
   '{"pa": 1, "max_par_jour": 2, "plafond_pa": 30, "usage_unique": true}'::jsonb,
   'militaire_ration_consommer ; militaire_ordre_collectif (action ration)',
   'Objet detruit dans la meme transaction que le gain. Refus non destructifs : pa_maximum, maximum_quotidien.'),
  ('ordre','hebergement|hotel-mineur','hebergement-standard',null,100,'{"pa_lendemain": 2, "moral": 3}'::jsonb,
   'pa_bonus_hotel (serveur) ; confortMap plateau-personnage.js:2943-2948',null),
  ('ordre','hebergement|hotel-port','hebergement-standard',null,100,'{"pa_lendemain": 2, "moral": 3}'::jsonb,
   'pa_bonus_hotel ; confortMap plateau-personnage.js:2943-2948',null),
  ('ordre','hebergement|hotel-republica','hebergement-standard',null,100,'{"pa_lendemain": 2, "moral": 3}'::jsonb,
   'pa_bonus_hotel = 2 ; confortMap plateau-personnage.js:2943-2948 applique {moral:3, paBonus:2}',
   'ANOMALIE A TRAITER SEPAREMENT : plateau-personnage.js:437 ANNONCE {moral:5, paBonus:5}. Trois sources divergentes. Seule la valeur APPLIQUEE est retenue ici.'),
  ('ordre','hebergement|palais-presidentiel','hebergement-prestige',null,100,'{"pa_lendemain": 8, "moral": 8}'::jsonb,
   'pa_bonus_hotel = 8 ; confortMap plateau-personnage.js:2947',null),
  ('objet_id','armoire_souvenirs','meuble-de-rangement',null,100,null,
   'creerExemplaireArmoireSouvenirs, plateau-justice-economie.js:5512-5528 ; seuls lecteurs : plateau-personnage.js:3338 et :3373 (affichage)',
   'Aucun effet mecanique hormis encombrement 3. contenu et verrouillee ne sont ni lus ni ecrits. AUCUN bonus de sommeil. Actuellement IMPOSSIBLE A OBTENIR : la ligne batiments_etat[republic_ville_a_zone-production] n''existe pas.')
on conflict (motif, valeur) do update set
  generique_id = excluded.generique_id, variante_id = excluded.variante_id,
  priorite = excluded.priorite, effets_effectifs = excluded.effets_effectifs,
  source_audit = excluded.source_audit, note = excluded.note;