-- GRANT sur tables, colonnes et fonctions
-- ============================================================================
-- BASELINE Human Gambit -- domaine economie -- phase 70 : droits
--
-- Fichier GENERE par outils/baseline/rendre.py depuis les catalogues
-- PostgreSQL. Ne pas editer a la main : toute correction passe par une
-- migration, puis par une nouvelle extraction.
--
-- ORDRE D'APPLICATION : par PHASE croissante, tous domaines confondus, et non
-- domaine par domaine. Voir baseline/README.md.
-- ============================================================================

-- DROITS SUR LES FUNCTIONS
GRANT EXECUTE ON FUNCTION public.acheter_a_entrepot(text,text,text,text,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.acheter_a_entrepot(text,text,text,text,jsonb) TO postgres;
GRANT EXECUTE ON FUNCTION public.acheter_a_entrepot(text,text,text,text,jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.acheter_a_la_criee(text,text,text,text,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.acheter_a_la_criee(text,text,text,text,jsonb) TO postgres;
GRANT EXECUTE ON FUNCTION public.acheter_a_la_criee(text,text,text,text,jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.acheter_produit_commerce(text,text,text,text,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.acheter_produit_commerce(text,text,text,text,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.acheter_produit_commerce(text,text,text,text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.acheter_produit_manufacture(text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.acheter_produit_manufacture(text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.acheter_produit_manufacture(text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.acheter_vente_directe_usine(text,text,text,text,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.acheter_vente_directe_usine(text,text,text,text,jsonb) TO postgres;
GRANT EXECUTE ON FUNCTION public.acheter_vente_directe_usine(text,text,text,text,jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.approvisionner_chantier(text,text,text,text,jsonb,jsonb,numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.approvisionner_chantier(text,text,text,text,jsonb,jsonb,numeric) TO postgres;
GRANT EXECUTE ON FUNCTION public.approvisionner_chantier(text,text,text,text,jsonb,jsonb,numeric) TO service_role;
GRANT EXECUTE ON FUNCTION public.capacite_entrepot() TO authenticated;
GRANT EXECUTE ON FUNCTION public.capacite_entrepot() TO postgres;
GRANT EXECUTE ON FUNCTION public.capacite_entrepot() TO service_role;
GRANT EXECUTE ON FUNCTION public.chantier_lancer(text,text,text,text,numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.chantier_lancer(text,text,text,text,numeric) TO postgres;
GRANT EXECUTE ON FUNCTION public.chantier_lancer(text,text,text,text,numeric) TO service_role;
GRANT EXECUTE ON FUNCTION public.chantier_travailler(text,text,text,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.chantier_travailler(text,text,text,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.chantier_travailler(text,text,text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.chantier_verser(text,text,text,numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.chantier_verser(text,text,text,numeric) TO postgres;
GRANT EXECUTE ON FUNCTION public.chantier_verser(text,text,text,numeric) TO service_role;
GRANT EXECUTE ON FUNCTION public.coef_prix_max_pj(text) TO anon;
GRANT EXECUTE ON FUNCTION public.coef_prix_max_pj(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.coef_prix_max_pj(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.coef_prix_max_pj(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.commerce_acheter_matiere(text,text,text,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.commerce_acheter_matiere(text,text,text,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.commerce_acheter_matiere(text,text,text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.commerce_apporter_matiere(text,text,text,text,integer,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.commerce_apporter_matiere(text,text,text,text,integer,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.commerce_apporter_matiere(text,text,text,text,integer,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.commerce_cout_revient_portion(jsonb,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.commerce_cout_revient_portion(jsonb,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.commerce_fixer_parametres(text,text,jsonb,jsonb,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.commerce_fixer_parametres(text,text,jsonb,jsonb,jsonb) TO postgres;
GRANT EXECUTE ON FUNCTION public.commerce_fixer_parametres(text,text,jsonb,jsonb,jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.commerce_produire(text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.commerce_produire(text,text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.commerce_produire(text,text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.commerce_vendre_produit(text,text,jsonb,text,text,integer,integer,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.commerce_vendre_produit(text,text,jsonb,text,text,integer,integer,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.commerce_vendre_produit(text,text,jsonb,text,text,integer,integer,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.creer_fonds_commerce(text,text,text,integer,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.creer_fonds_commerce(text,text,text,integer,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.creer_fonds_commerce(text,text,text,integer,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.creer_oeuvre(text,text,text,text,integer,text,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.creer_oeuvre(text,text,text,text,integer,text,jsonb) TO postgres;
GRANT EXECUTE ON FUNCTION public.creer_oeuvre(text,text,text,text,integer,text,jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.creer_offre(text,text,text,text,integer,bigint,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.creer_offre(text,text,text,text,integer,bigint,jsonb) TO postgres;
GRANT EXECUTE ON FUNCTION public.creer_offre(text,text,text,text,integer,bigint,jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.employer_fonds(text,text,text,text,integer,boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.employer_fonds(text,text,text,text,integer,boolean) TO postgres;
GRANT EXECUTE ON FUNCTION public.employer_fonds(text,text,text,text,integer,boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.entrepot_caisse_lire(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.entrepot_caisse_lire(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.entrepot_capacite_disponible(text,text) TO anon;
GRANT EXECUTE ON FUNCTION public.entrepot_capacite_disponible(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.entrepot_capacite_disponible(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.entrepot_capacite_disponible(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.entrepot_commander(text,text,integer,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.entrepot_commander(text,text,integer,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.entrepot_commander(text,text,integer,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.entrepot_du_directeur(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.entrepot_du_directeur(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.entrepot_du_directeur(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.entrepot_fixer_desiderata(text,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.entrepot_fixer_desiderata(text,jsonb) TO postgres;
GRANT EXECUTE ON FUNCTION public.entrepot_fixer_desiderata(text,jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.entrepot_livrer_transits() TO postgres;
GRANT EXECUTE ON FUNCTION public.entrepot_livrer_transits() TO service_role;
GRANT EXECUTE ON FUNCTION public.entrepot_reverser(text,numeric,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.entrepot_reverser(text,numeric,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.entrepot_virement_mairie(text,numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.entrepot_virement_mairie(text,numeric) TO postgres;
GRANT EXECUTE ON FUNCTION public.entrepot_virement_mairie(text,numeric) TO service_role;
GRANT EXECUTE ON FUNCTION public.entrepots_reverser_excedent() TO postgres;
GRANT EXECUTE ON FUNCTION public.entrepots_reverser_excedent() TO service_role;
GRANT EXECUTE ON FUNCTION public.entreprise_acte_preemption(text,text,text,text,integer,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.entreprise_acte_preemption(text,text,text,text,integer,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.entreprise_acte_preemption(text,text,text,text,integer,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.entreprise_acte_rachat(text,text,text,integer,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.entreprise_acte_rachat(text,text,text,integer,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.entreprise_acte_rachat(text,text,text,integer,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.entreprise_ajouter_historique(jsonb,numeric,text,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.entreprise_ajouter_historique(jsonb,numeric,text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.entreprise_assurer_existence(text,text,text,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.entreprise_assurer_existence(text,text,text,text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.entreprise_assurer_existence(text,text,text,text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.entreprise_mouvement_fiscal(text,text,numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.entreprise_mouvement_fiscal(text,text,numeric) TO postgres;
GRANT EXECUTE ON FUNCTION public.entreprise_mouvement_fiscal(text,text,numeric) TO service_role;
GRANT EXECUTE ON FUNCTION public.entreprise_preempter(text,text,numeric,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.entreprise_preempter(text,text,numeric,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.entreprise_preempter(text,text,numeric,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.entreprise_prix_rachat(jsonb) TO postgres;
GRANT EXECUTE ON FUNCTION public.entreprise_prix_rachat(jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.entreprise_signer_compromis(text,text,numeric,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.entreprise_signer_compromis(text,text,numeric,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.entreprise_signer_compromis(text,text,numeric,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.entreprise_succession_annuler_compromis(text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.entreprise_succession_annuler_compromis(text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.entreprise_succession_annuler_compromis(text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.entreprise_succession_geler(text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.entreprise_succession_geler(text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.entreprise_succession_geler(text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.fabriquer_produit_manufacture(text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fabriquer_produit_manufacture(text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.fabriquer_produit_manufacture(text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.fixer_prix_entrepot(text,text,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fixer_prix_entrepot(text,text,jsonb) TO postgres;
GRANT EXECUTE ON FUNCTION public.fixer_prix_entrepot(text,text,jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.fixer_prix_vente_directe(text,text,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fixer_prix_vente_directe(text,text,jsonb) TO postgres;
GRANT EXECUTE ON FUNCTION public.fixer_prix_vente_directe(text,text,jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.fixer_repartition_port(text,numeric,numeric,numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fixer_repartition_port(text,numeric,numeric,numeric) TO postgres;
GRANT EXECUTE ON FUNCTION public.fixer_repartition_port(text,numeric,numeric,numeric) TO service_role;
GRANT EXECUTE ON FUNCTION public.fixer_repartition_production(text,text,numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fixer_repartition_production(text,text,numeric) TO postgres;
GRANT EXECUTE ON FUNCTION public.fixer_repartition_production(text,text,numeric) TO service_role;
GRANT EXECUTE ON FUNCTION public.fournisseurs_etrangers() TO anon;
GRANT EXECUTE ON FUNCTION public.fournisseurs_etrangers() TO authenticated;
GRANT EXECUTE ON FUNCTION public.fournisseurs_etrangers() TO postgres;
GRANT EXECUTE ON FUNCTION public.fournisseurs_etrangers() TO service_role;
GRANT EXECUTE ON FUNCTION public.fret_dedouaner(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fret_dedouaner(uuid) TO postgres;
GRANT EXECUTE ON FUNCTION public.fret_dedouaner(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.fret_unitaire_international() TO anon;
GRANT EXECUTE ON FUNCTION public.fret_unitaire_international() TO authenticated;
GRANT EXECUTE ON FUNCTION public.fret_unitaire_international() TO postgres;
GRANT EXECUTE ON FUNCTION public.fret_unitaire_international() TO service_role;
GRANT EXECUTE ON FUNCTION public.local_vocation_commerciale(text) TO anon;
GRANT EXECUTE ON FUNCTION public.local_vocation_commerciale(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.local_vocation_commerciale(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.local_vocation_commerciale(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.matiere_circuits_disponibles(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.matiere_circuits_disponibles(text) TO postgres;
GRANT EXECUTE ON FUNCTION public.matiere_circuits_disponibles(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.matiere_refus_circuit_legal(text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.matiere_refus_circuit_legal(text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.matiere_refus_circuit_legal(text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.matiere_refus_circuit_legal_lot(text,jsonb,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.matiere_refus_circuit_legal_lot(text,jsonb,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.matiere_refus_circuit_legal_lot(text,jsonb,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.ordres_couts_empreinte_reelle() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.ordres_couts_empreinte_reelle() TO anon;
GRANT EXECUTE ON FUNCTION public.ordres_couts_empreinte_reelle() TO authenticated;
GRANT EXECUTE ON FUNCTION public.ordres_couts_empreinte_reelle() TO postgres;
GRANT EXECUTE ON FUNCTION public.ordres_couts_empreinte_reelle() TO service_role;
GRANT EXECUTE ON FUNCTION public.payer_ordre(text,text,integer,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.payer_ordre(text,text,integer,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.payer_ordre(text,text,integer,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.prix_ressource_selon_stock(text,numeric) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.prix_ressource_selon_stock(text,numeric) TO anon;
GRANT EXECUTE ON FUNCTION public.prix_ressource_selon_stock(text,numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.prix_ressource_selon_stock(text,numeric) TO postgres;
GRANT EXECUTE ON FUNCTION public.prix_ressource_selon_stock(text,numeric) TO service_role;
GRANT EXECUTE ON FUNCTION public.produire_en_usine(text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.produire_en_usine(text,text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.produire_en_usine(text,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.recevoir_soin(text,text,text,text,text,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.recevoir_soin(text,text,text,text,text,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.recevoir_soin(text,text,text,text,text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.refectoire_repas(text,text,integer,integer,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.refectoire_repas(text,text,integer,integer,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.refectoire_repas(text,text,integer,integer,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.repondre_offre(text,text,boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.repondre_offre(text,text,boolean) TO postgres;
GRANT EXECUTE ON FUNCTION public.repondre_offre(text,text,boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.ressources_economie_empreinte_reelle() TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.ressources_economie_empreinte_reelle() TO anon;
GRANT EXECUTE ON FUNCTION public.ressources_economie_empreinte_reelle() TO authenticated;
GRANT EXECUTE ON FUNCTION public.ressources_economie_empreinte_reelle() TO postgres;
GRANT EXECUTE ON FUNCTION public.ressources_economie_empreinte_reelle() TO service_role;
GRANT EXECUTE ON FUNCTION public.ressources_economie_nombre(numeric) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.ressources_economie_nombre(numeric) TO anon;
GRANT EXECUTE ON FUNCTION public.ressources_economie_nombre(numeric) TO authenticated;
GRANT EXECUTE ON FUNCTION public.ressources_economie_nombre(numeric) TO postgres;
GRANT EXECUTE ON FUNCTION public.ressources_economie_nombre(numeric) TO service_role;
GRANT EXECUTE ON FUNCTION public.restituer_reliquats_chantier(text,text) TO postgres;
GRANT EXECUTE ON FUNCTION public.restituer_reliquats_chantier(text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.vendre_fonds_commerce(text,text,text,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.vendre_fonds_commerce(text,text,text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.vendre_materiaux_chantier(text,text,text,text,integer,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.vendre_materiaux_chantier(text,text,text,text,integer,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.vendre_materiaux_chantier(text,text,text,text,integer,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.vendre_matiere_a_usine(text,text,text,text,text,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.vendre_matiere_a_usine(text,text,text,text,text,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.vendre_matiere_a_usine(text,text,text,text,text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.vendre_ressource_medicale(text,text,text,text,text,integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.vendre_ressource_medicale(text,text,text,text,text,integer) TO postgres;
GRANT EXECUTE ON FUNCTION public.vendre_ressource_medicale(text,text,text,text,text,integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.ventes_snapshots_append_only() TO postgres;
GRANT EXECUTE ON FUNCTION public.ventes_snapshots_append_only() TO service_role;

-- DROITS SUR LES SEQUENCES
GRANT SELECT, USAGE ON SEQUENCE public.catalogue_correspondance_legacy_id_seq TO anon;
GRANT SELECT, USAGE ON SEQUENCE public.catalogue_correspondance_legacy_id_seq TO authenticated;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.catalogue_correspondance_legacy_id_seq TO postgres;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.catalogue_correspondance_legacy_id_seq TO service_role;
GRANT SELECT, USAGE ON SEQUENCE public.entrepot_journal_id_seq TO anon;
GRANT SELECT, USAGE ON SEQUENCE public.entrepot_journal_id_seq TO authenticated;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.entrepot_journal_id_seq TO postgres;
GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.entrepot_journal_id_seq TO service_role;

-- DROITS SUR LES TABLES
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.apports_matieres TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.apports_matieres TO service_role;
GRANT SELECT ON TABLE public.caisses_fret TO anon;
GRANT INSERT, SELECT, UPDATE ON TABLE public.caisses_fret TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.caisses_fret TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.caisses_fret TO service_role;
GRANT SELECT ON TABLE public.catalogue_correspondance_legacy TO anon;
GRANT SELECT ON TABLE public.catalogue_correspondance_legacy TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.catalogue_correspondance_legacy TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.catalogue_correspondance_legacy TO service_role;
GRANT SELECT ON TABLE public.catalogue_familles TO anon;
GRANT SELECT ON TABLE public.catalogue_familles TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.catalogue_familles TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.catalogue_familles TO service_role;
GRANT SELECT ON TABLE public.catalogue_generique_type TO anon;
GRANT SELECT ON TABLE public.catalogue_generique_type TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.catalogue_generique_type TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.catalogue_generique_type TO service_role;
GRANT SELECT ON TABLE public.catalogue_generiques TO anon;
GRANT SELECT ON TABLE public.catalogue_generiques TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.catalogue_generiques TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.catalogue_generiques TO service_role;
GRANT SELECT ON TABLE public.catalogue_generiques_raccordes TO anon;
GRANT SELECT ON TABLE public.catalogue_generiques_raccordes TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.catalogue_generiques_raccordes TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.catalogue_generiques_raccordes TO service_role;
GRANT SELECT ON TABLE public.catalogue_types TO anon;
GRANT SELECT ON TABLE public.catalogue_types TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.catalogue_types TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.catalogue_types TO service_role;
GRANT SELECT ON TABLE public.catalogue_variantes TO anon;
GRANT SELECT ON TABLE public.catalogue_variantes TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.catalogue_variantes TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.catalogue_variantes TO service_role;
GRANT SELECT ON TABLE public.chaines_production_usine TO anon;
GRANT SELECT ON TABLE public.chaines_production_usine TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.chaines_production_usine TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.chaines_production_usine TO service_role;
GRANT SELECT ON TABLE public.chantiers_besoins_jour TO anon;
GRANT SELECT ON TABLE public.chantiers_besoins_jour TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.chantiers_besoins_jour TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.chantiers_besoins_jour TO service_role;
GRANT SELECT ON TABLE public.chantiers_paliers TO anon;
GRANT SELECT ON TABLE public.chantiers_paliers TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.chantiers_paliers TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.chantiers_paliers TO service_role;
GRANT SELECT ON TABLE public.commerces_dotations TO anon;
GRANT SELECT ON TABLE public.commerces_dotations TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.commerces_dotations TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.commerces_dotations TO service_role;
GRANT SELECT ON TABLE public.commerces_types TO anon;
GRANT SELECT ON TABLE public.commerces_types TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.commerces_types TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.commerces_types TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.confiscations_douanieres TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.confiscations_douanieres TO service_role;
GRANT SELECT ON TABLE public.contenu_caisses_fret TO anon;
GRANT INSERT, SELECT, UPDATE ON TABLE public.contenu_caisses_fret TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.contenu_caisses_fret TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.contenu_caisses_fret TO service_role;
GRANT SELECT ON TABLE public.directeurs_usine TO anon;
GRANT SELECT ON TABLE public.directeurs_usine TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.directeurs_usine TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.directeurs_usine TO service_role;
GRANT SELECT ON TABLE public.entrepot_journal TO anon;
GRANT SELECT ON TABLE public.entrepot_journal TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.entrepot_journal TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.entrepot_journal TO service_role;
GRANT SELECT ON TABLE public.entrepot_transits TO anon;
GRANT SELECT ON TABLE public.entrepot_transits TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.entrepot_transits TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.entrepot_transits TO service_role;
GRANT SELECT ON TABLE public.entrepots_par_ville TO anon;
GRANT SELECT ON TABLE public.entrepots_par_ville TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.entrepots_par_ville TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.entrepots_par_ville TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.entrepots_reversements TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.entrepots_reversements TO service_role;
GRANT SELECT ON TABLE public.entreprises TO anon;
GRANT SELECT ON TABLE public.entreprises TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.entreprises TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.entreprises TO service_role;
GRANT SELECT ON TABLE public.entreprises_constantes TO anon;
GRANT SELECT ON TABLE public.entreprises_constantes TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.entreprises_constantes TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.entreprises_constantes TO service_role;
GRANT SELECT ON TABLE public.entreprises_prix_rachat TO anon;
GRANT SELECT ON TABLE public.entreprises_prix_rachat TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.entreprises_prix_rachat TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.entreprises_prix_rachat TO service_role;
GRANT SELECT ON TABLE public.imprimeries_declarees TO anon;
GRANT SELECT ON TABLE public.imprimeries_declarees TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.imprimeries_declarees TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.imprimeries_declarees TO service_role;
GRANT SELECT ON TABLE public.investissements TO anon;
GRANT SELECT ON TABLE public.investissements TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.investissements TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.investissements TO service_role;
GRANT SELECT ON TABLE public.oeuvres TO anon;
GRANT SELECT ON TABLE public.oeuvres TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.oeuvres TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.oeuvres TO service_role;
GRANT SELECT ON TABLE public.offres TO anon;
GRANT SELECT ON TABLE public.offres TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.offres TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.offres TO service_role;
GRANT SELECT ON TABLE public.ordres_couts TO anon;
GRANT SELECT ON TABLE public.ordres_couts TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.ordres_couts TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.ordres_couts TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.ordres_couts_ecarts TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.ordres_couts_ecarts TO service_role;
GRANT SELECT ON TABLE public.ordres_couts_empreinte TO anon;
GRANT SELECT ON TABLE public.ordres_couts_empreinte TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.ordres_couts_empreinte TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.ordres_couts_empreinte TO service_role;
GRANT SELECT ON TABLE public.ordres_couts_inconnus TO anon;
GRANT SELECT ON TABLE public.ordres_couts_inconnus TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.ordres_couts_inconnus TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.ordres_couts_inconnus TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.productions_references TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.productions_references TO service_role;
GRANT SELECT ON TABLE public.produits_manufactures TO anon;
GRANT SELECT ON TABLE public.produits_manufactures TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.produits_manufactures TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.produits_manufactures TO service_role;
GRANT SELECT ON TABLE public.recettes_commerce TO anon;
GRANT SELECT ON TABLE public.recettes_commerce TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.recettes_commerce TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.recettes_commerce TO service_role;
GRANT SELECT ON TABLE public.recettes_production TO anon;
GRANT SELECT ON TABLE public.recettes_production TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.recettes_production TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.recettes_production TO service_role;
GRANT SELECT ON TABLE public.ressources_economie TO anon;
GRANT SELECT ON TABLE public.ressources_economie TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.ressources_economie TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.ressources_economie TO service_role;
GRANT SELECT ON TABLE public.ressources_economie_empreinte TO anon;
GRANT SELECT ON TABLE public.ressources_economie_empreinte TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.ressources_economie_empreinte TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.ressources_economie_empreinte TO service_role;
GRANT SELECT ON TABLE public.structures_medicales TO anon;
GRANT SELECT ON TABLE public.structures_medicales TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.structures_medicales TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.structures_medicales TO service_role;
GRANT SELECT ON TABLE public.usines_rachat_config TO anon;
GRANT SELECT ON TABLE public.usines_rachat_config TO authenticated;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.usines_rachat_config TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.usines_rachat_config TO service_role;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.ventes_snapshots TO postgres;
GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE public.ventes_snapshots TO service_role;
