-- Commentaires d'objets
-- ============================================================================
-- BASELINE Human Gambit -- domaine economie -- phase 80 : commentaires
--
-- Fichier GENERE par outils/baseline/rendre.py depuis les catalogues
-- PostgreSQL. Ne pas editer a la main : toute correction passe par une
-- migration, puis par une nouvelle extraction.
--
-- ORDRE D'APPLICATION : par PHASE croissante, tous domaines confondus, et non
-- domaine par domaine. Voir baseline/README.md.
-- ============================================================================

COMMENT ON COLUMN public.catalogue_correspondance_legacy.effets_effectifs IS 'UNIQUEMENT les effets que le moteur applique reellement a cet objet historique. NULL = aucun effet effectif, ce qui produira « Aucun effet » sur la fiche. Les proprietes declarees mais jamais lues n''y figurent jamais.';
COMMENT ON COLUMN public.catalogue_correspondance_legacy.source_audit IS 'chemin:ligne ou nom de fonction prouvant l''effet. Obligatoire : une correspondance sans preuve ne doit pas exister.';
COMMENT ON COLUMN public.catalogue_generiques.capacites IS 'Ce que l''objet permet de faire. Jamais herite d''un autre generique, jamais deduit du nom commercial.';
COMMENT ON COLUMN public.catalogue_generiques.equipable IS 'Affectation REELLEMENT existante dans le moteur actuel uniquement. Aucune anticipation des futures mecaniques d''installation.';
COMMENT ON COLUMN public.catalogue_generiques.est_service IS 'true = ne produit jamais d''objet d''inventaire. Le mode de commercialisation d''un bien (livre ou consomme sur place) n''est PAS une propriete du generique : il releve de la reference (L5).';
COMMENT ON COLUMN public.recettes_commerce.generique_id IS 'Etiquette de referentiel (L2). Nullable, aucun lecteur historique. Ne modifie aucun comportement.';
COMMENT ON COLUMN public.recettes_commerce.label_forme IS 'Nom de la FORME fabriquee, neutre sur le plan narratif et commercial, affiche par C6 quand un joueur choisit comment fabriquer sa reference. NULL = on garde le libelle historique. Le moteur legacy ne lit jamais cette colonne.';
COMMENT ON FUNCTION public.acheter_produit_commerce(text,text,text,text,integer) IS 'Achat d''une reference commerciale. Le client ne fournit qu''une intention : cle de requete, acteur, fonds, reference, quantite. Prix, quantite transferable, nature de l''objet et montant sont relus ou construits par le serveur sous verrou. Le prix est REVALIDE contre le plafond du pays au moment de la vente. Paiement, decrement de stock, credit de caisse, livraison et preuve immuable sont dans la meme transaction. Idempotent par ventes_snapshots.requete, garde permanente.';
COMMENT ON FUNCTION public.coef_prix_max_pj(text) IS 'Coefficient de plafond du prix libre d''un commercant PJ, applique au cout de revient unitaire. Politique economique PAR PAYS, lue dans entreprises_constantes. Rend NULL pour un pays dont le coefficient n''a pas ete arbitre : aucune valeur n''est jamais inventee, et la fixation de prix y est alors refusee.';
COMMENT ON FUNCTION public.commerce_acheter_matiere(text,text,text,integer) IS 'RELAIS HISTORIQUE (30 septembre 2026) vers commerce_apporter_matiere en mode vente. Ne contient plus aucune logique economique ; conserve pour ne casser aucun appelant. Non idempotente (aucune cle de requete recue) ; preferer commerce_apporter_matiere.';
COMMENT ON FUNCTION public.commerce_apporter_matiere(text,text,text,text,integer,text) IS 'Apport d''une matiere premiere a un commerce du moteur historique, par vente (prix fixe par le commerce) ou par don (prix 0, aucun mouvement d''argent, possible caisse vide). EXIGE LA PRESENCE PHYSIQUE sur le site du commerce (acteur_present_sur_site), verifiee sous verrou avant toute ecriture. Deduit la matiere acceptee de la carte du commerce (recettes de production pour l''armurerie). Conserve plafond, possession reelle, CMUP et historique. Idempotente par cle de requete, dans le meme registre apports_matieres que les fonds PJ.';
COMMENT ON FUNCTION public.local_vocation_commerciale(text) IS 'Vocation commerciale d''un local locatif, derivee de son batiment. NULL = le local ne peut pas heberger un fonds de commerce (logement, suite d''hotel, coffre, salle de reunion). N''exprime AUCUNE contrainte de type L2 : la compatibilite fine type x centre n''est pas arbitree.';
COMMENT ON FUNCTION public.matiere_circuits_disponibles(text) IS 'Decrit, pour une matiere economique, les circuits qui EXISTENT reellement dans le jeu : achat (entrepot, criee), vente (commerce, armurerie, usine, structure medicale), production (chaine d''usine, recolte), transformation, et les categories parlementaires qui permettent de la viser. Deduit des tables du jeu. Rend NULL si la matiere est inconnue. Sert a Seb Lex pour ne poser que les questions pertinentes.';
COMMENT ON FUNCTION public.matiere_refus_circuit_legal(text,text,text) IS 'Garde COMMUNE des circuits economiques legaux portant sur une matiere premiere. Rend NULL si le mouvement est licite, sinon le refus complet (raison matiere_interdite, avec la loi). Modes : don (TOUJOURS licite -- l''Assemblee ferme les circuits legaux, elle ne rend pas la matiere intransferable), vente et achat (bloques), production (bloquee), transformation (bloquee SEULEMENT si la loi a vote le cas B, data.portee.transformation_stock_interdite). La juridiction est celle du personnage, lue dans personnages_donnees et jamais recue de l''appelant. Une loi adoptee mais non appliquee ne bloque rien.';
COMMENT ON FUNCTION public.matiere_refus_circuit_legal_lot(text,jsonb,text) IS 'matiere_refus_circuit_legal appliquee a un panier {matiere: quantite}. Rend le refus de la premiere matiere interdite du panier, ou NULL si tout est licite.';
COMMENT ON FUNCTION public.recettes_militaires_empreinte_reelle() IS 'Empreinte reelle du miroir des recettes militaires. Pendant SQL de outils/generateurs/generer_recettes_militaires.py. Chantier 4D.';
COMMENT ON TABLE public.apports_matieres IS 'Journal des apports de matiere premiere a un commerce (vente ou don), pour les DEUX moteurs : fonds PJ via fonds_matiere_apporter, commerces historiques via commerce_apporter_matiere. La colonne fonds_id porte l''identifiant entreprises dans les deux cas. La cle de requete porte l''idempotence. Ferme au client.';
COMMENT ON TABLE public.catalogue_familles IS 'Familles commerciales. Liste plate en L2 ; le rattachement aux types arrive en L5.';
COMMENT ON TABLE public.catalogue_types IS 'Les 14 types de commerce du referentiel cible. Lecture publique, ecriture service_role.';
COMMENT ON TABLE public.ordres_couts IS 'Miroir des couts declares dans data.js. Genere par .scratch/generer_ordres_couts.py, jamais saisi a la main.';
COMMENT ON TABLE public.productions_references IS 'Journal des productions de references PJ. La cle primaire requete est la garde d''idempotence, verifiee avant tout debit. Conserve le cout REELLEMENT supporte par chaque lot. Ferme aux clients : ecriture et lecture par les RPC seules.';
COMMENT ON TABLE public.ventes_snapshots IS 'Preuve immuable d''une vente. Ecrite dans la MEME transaction que le paiement, le decrement de stock et la livraison. Fige le texte commercial affiche et la fiche officielle du moment : une reference renommee, redecrite, retarifee ou desactivee ensuite ne change rien a une vente passee. Append-only, y compris pour service_role.';
