-- SEED -- catalogue_correspondance_legacy
-- ============================================================================
-- Table      : public.catalogue_correspondance_legacy
-- Domaine    : economie
-- Categorie  : D (mixte)
-- Strategie  : seed_complet (classification du chantier 2C)
-- Lignes     : 58
--
-- Fichier GENERE par outils/baseline/seeds.py. Ne pas editer a la main.
-- Les litteraux sont ceux que PostgreSQL lui-meme a produits (quote_nullable) :
-- aucune regle d'echappement n'a ete reimplementee.
--
-- JUSTIFICATION DU SEED (chantier 2C)
-- 58 correspondances vers les anciens identifiants.
--
-- ARBITRAGE DE GAME DESIGN
-- Table de transition : a-t-elle encore un sens dans un monde neuf ?
-- ============================================================================

INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('1', 'type_soustype', 'arme|blanche', 'arme-blanche', NULL, '100', NULL, 'plateau-actions-illegales-rumeurs.js:1478 (affichage seul) ; getStatEffective ne lit jamais item.bonus', 'bonus {VOL,5} declare, affiche, JAMAIS applique : absent des effets effectifs.');
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('2', 'type_soustype', 'arme|poing', 'arme-de-poing', NULL, '100', NULL, 'plateau-actions-illegales-rumeurs.js:1478 ; getStatEffective', 'bonus {PER,8} declare, jamais applique.');
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('3', 'type_soustype', 'arme|carabine', 'arme-longue', NULL, '100', NULL, 'plateau-actions-illegales-rumeurs.js:1478 ; getStatEffective', 'bonus {PER,15} declare, jamais applique.');
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('4', 'produit_militaire', 'arme_de_poing', 'arme-de-poing', NULL, '200', '{"bonus_combat_feu": 8}', 'table militaire_armes_bonus, lue par militaire_bataille_combattants', NULL);
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('5', 'produit_militaire', 'mitraillette', 'arme-longue', NULL, '200', '{"bonus_combat_feu": 15}', 'table militaire_armes_bonus, lue par militaire_bataille_combattants', NULL);
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('6', 'type_produit_militaire', 'explosif|explosif_militaire', 'explosif', NULL, '300', '{"blesse_presents": true, "ferme_batiment_jours": 5}', 'confirmerUtiliserExplosifs, plateau-actions-illegales-rumeurs.js:2248-2330', 'Exemplaire retire legalement.');
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('7', 'type_produit_militaire', 'arme|explosif_militaire', 'explosif', NULL, '300', NULL, 'doUtiliserExplosifs cherche type===''explosif'' (plateau-actions-illegales-rumeurs.js:2226) ; inventaire_consommer refuse objet_non_consommable', 'ANOMALIE : exemplaire SUBTILISE, type ''arme''. Introuvable par le handler et refuse par la RPC. Objet inerte. Documente, non corrige.');
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('8', 'type', 'explosif', 'explosif', NULL, '100', '{"blesse_presents": true, "ferme_batiment_jours": 5}', 'confirmerUtiliserExplosifs', 'Explosif de chantier (marche noir).');
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('9', 'type', 'protection', 'protection-corporelle', NULL, '100', NULL, 'militaire_gilet_absorber cherche produitMilitaire=''gilet_pare_balles'', absent de cet objet', 'Gilet civil a 600 FR : effet annonce, jamais cable. Documente, non corrige.');
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('10', 'produit_militaire', 'gilet_pare_balles', 'protection-corporelle', 'protection-corporelle--militaire', '200', '{"condition": "bataille, mode feu uniquement", "une_seule_fois": true, "garantit_pa_minimum": 1, "absorption_tir_probabilite": 0.5}', 'militaire_gilet_absorber, appelee par militaire_bataille_appliquer', NULL);
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('11', 'type_tracttype', 'tract|pour', 'imprime', NULL, '200', '{"voix_pnj": 1}', 'tracts_electoraux_distribuer_interne', NULL);
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('12', 'type_tracttype', 'tract|contre', 'imprime', NULL, '200', '{"plancher": 0, "voix_pnj": -1}', 'tracts_electoraux_distribuer_interne', NULL);
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('13', 'type', 'tract_calomnieux', 'imprime', NULL, '100', '{"inf_cible": -2, "pop_cible": -5}', 'calomnie_distribuer, verrou PNJ x cible x jour (calomnies_actes_verrou)', NULL);
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('14', 'type_originequete', 'tract|jean_lou', 'imprime', NULL, '400', '{"voix_pnj": 1}', 'plateau-pnj.js:621-624 (enregistrerVotePNJ)', 'Objet de QUETE : hors catalogue commercial. Mappe pour que la fiche sache repondre.');
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('15', 'recette_id', 'snack_buvette', 'encas', NULL, '100', '{"hp": 2, "moral": 1}', 'recettes_commerce.effets ; applique par plateau-actions-illegales-rumeurs.js:4779-4781', NULL);
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('16', 'recette_id', 'petit_dejeuner', 'encas', NULL, '100', '{"hp": 3, "moral": 1}', 'recettes_commerce.effets', NULL);
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('17', 'recette_id', 'sandwich_cheminots', 'plat-simple', NULL, '100', '{"hp": 5, "moral": 1}', 'recettes_commerce.effets', NULL);
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('18', 'recette_id', 'boeuf_bourguignon', 'plat-elabore', NULL, '100', '{"hp": 8, "moral": 2}', 'recettes_commerce.effets', NULL);
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('19', 'recette_id', 'saucisse_puree', 'plat-elabore', NULL, '100', '{"hp": 8, "moral": 2}', 'recettes_commerce.effets', NULL);
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('20', 'recette_id', 'plat_de_poisson', 'plat-elabore', NULL, '100', '{"hp": 8, "moral": 2}', 'recettes_commerce.effets', NULL);
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('21', 'recette_id', 'carbonade_frites', 'plat-elabore', NULL, '100', '{"hp": 8, "moral": 3}', 'recettes_commerce.effets', 'Seul plat elabore a +3 Moral : specialite verrouillee sur ville_b.');
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('22', 'recette_id', 'menu_gastronomique_1', 'menu-gastronomique', NULL, '100', '{"hp": 10, "moral": 1, "pa_differe": 3}', 'recettes_commerce.effets ; PA differe atteste serveur par pa_bonus_differes', NULL);
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('23', 'recette_id', 'menu_gastronomique_2', 'menu-gastronomique', NULL, '100', '{"hp": 10, "moral": 1, "pa_differe": 3}', 'recettes_commerce.effets ; pa_bonus_differes', NULL);
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('24', 'recette_id', 'menu_gastronomique_3', 'menu-gastronomique', NULL, '100', '{"hp": 10, "moral": 1, "pa_differe": 3}', 'recettes_commerce.effets ; pa_bonus_differes', NULL);
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('25', 'recette_id', 'menu_psm_1', 'menu-gastronomique', NULL, '100', '{"hp": 10, "moral": 1, "pa_differe": 3}', 'recettes_commerce.effets ; pa_bonus_differes', NULL);
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('26', 'recette_id', 'menu_psm_2', 'menu-gastronomique', NULL, '100', '{"hp": 10, "moral": 1, "pa_differe": 3}', 'recettes_commerce.effets ; pa_bonus_differes', NULL);
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('27', 'recette_id', 'menu_psm_3', 'menu-gastronomique', NULL, '100', '{"hp": 10, "moral": 1, "pa_differe": 3}', 'recettes_commerce.effets ; pa_bonus_differes', NULL);
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('28', 'recette_id', 'biere_pression', 'boisson', NULL, '100', '{"moral": 2}', 'recettes_commerce.effets', NULL);
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('29', 'recette_id', 'vin', 'boisson', NULL, '100', '{"moral": 2}', 'recettes_commerce.effets', 'Seule boisson exigee nommement par le diner d''affaires.');
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('30', 'recette_id', 'cafe_boisson', 'boisson', NULL, '100', '{"moral": 2}', 'recettes_commerce.effets', NULL);
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('31', 'recette_id', 'jus_de_fruits', 'boisson', NULL, '100', '{"moral": 2}', 'recettes_commerce.effets', NULL);
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('32', 'recette_id', 'boisson_sans_alcool', 'boisson', NULL, '100', '{"moral": 1}', 'recettes_commerce.effets', 'ANOMALIE : seule recette a materiaux vides. Ne fait pas jurisprudence pour le generique.');
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('33', 'recette_id', 'sandwich', 'plat-simple', NULL, '100', '{"hp": 5, "moral": 1, "pa_differe": 1}', 'recettes_commerce.effets ; pa_bonus_differes', 'ANOMALIE : retire de toutes les cartes, non produisible. Recette conservee dans les deux registres.');
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('34', 'famille_produit_marche', 'aliment', 'encas-a-emporter', NULL, '100', '{"pa_si_frais": 1, "pa_si_perime": -1, "fraicheur_jours_reels": 7}', 'inventaire_consommer (RPC) ; DUREE_FRAICHEUR_ALIMENT_MS, plateau-personnage.js:3253', 'Aucun hp ni moral : ces produits n''ont aucune valeur nutritive codee.');
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('35', 'famille_produit_marche', 'carte_postale', 'carte-postale', NULL, '100', '{"moral_lecteur": 10, "moral_expediteur": 10, "plafond_quotidien_lecteur": 1, "plafond_quotidien_expediteur": 1}', 'plateau-personnage.js:3583-3592 (lecteur) ; plateau-communication.js:1688-1697 (expediteur, file impacts_indices_attente) ; colonne persistee carte_postale_moral_jour', 'Deux plafonds quotidiens distincts sur la meme colonne persistee.');
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('36', 'recette_id', 'porte_cle_palais_luthecia', 'souvenir', NULL, '100', NULL, 'recettes_commerce.bonus_integration_ville = null', 'Classe integration_locale SANS bonus : distinction mecanique avec les 3 textiles.');
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('37', 'recette_id', 'garde_republien_plomb', 'souvenir', NULL, '100', NULL, 'recettes_commerce.bonus_integration_ville = null', NULL);
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('38', 'recette_id', 'figurine_maxence_monfils', 'souvenir', NULL, '100', NULL, 'recettes_commerce.bonus_integration_ville = null', NULL);
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('39', 'type', 'accessoire_sport', 'article-de-supporter', NULL, '100', NULL, 'plateau-organisations-quetes.js:9026 ; aucun lecteur du type accessoire_sport', 'Aucune recette, aucun stock, aucun effet. Fonctionnement preserve tel quel.');
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('40', 'stack_key', 'cereales', 'aliment-brut', NULL, '100', NULL, 'ressources_economie', 'Intrant (GD3).');
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('41', 'stack_key', 'viande', 'aliment-brut', NULL, '100', NULL, 'ressources_economie', 'Intrant (GD3).');
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('42', 'stack_key', 'poisson', 'aliment-brut', NULL, '100', NULL, 'ressources_economie', 'Intrant (GD3).');
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('43', 'stack_key', 'fruits_legumes', 'aliment-brut', NULL, '100', NULL, 'ressources_economie', 'Intrant (GD3).');
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('44', 'stack_key', 'produits_exotiques', 'aliment-brut', NULL, '100', NULL, 'ressources_economie', 'Intrant (GD3).');
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('45', 'recette_id', 'tshirt_psm', 'haut', NULL, '100', '{"ent": 1, "condition": "presence_ville_a", "non_cumulable": true}', 'bonusEntIntegrationLocale, plateau-organisations-quetes.js:3341-3345 ; lu par getStatEffective', 'SEUL bonus reellement calcule depuis l''inventaire. Reste une propriete de CET objet, pas du generique Haut.');
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('46', 'recette_id', 'casquette_montrouge', 'accessoire-vestimentaire', NULL, '100', '{"ent": 1, "condition": "presence_ville_b", "non_cumulable": true}', 'bonusEntIntegrationLocale ; getStatEffective', NULL);
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('47', 'recette_id', 'echarpe_luthecia', 'accessoire-vestimentaire', NULL, '100', '{"ent": 1, "condition": "presence_capitale", "non_cumulable": true}', 'bonusEntIntegrationLocale ; getStatEffective', NULL);
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('48', 'produit_militaire', 'tenue_camouflage', 'tenue-militaire', NULL, '200', '{"condition": "porte par un soldat PNJ via pnj_possessions (origine blob_accessoires) ; AUCUN effet sur un PJ", "camouflage_groupe": 20}', 'militaire_camouflage_groupe, lue par militaire_observer', 'La description annoncee (« protege celui qui la porte ») est fausse pour un PJ. Documente, non corrige.');
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('49', 'produit_militaire', 'radio', 'appareil-de-communication', 'appareil-de-communication--militaire', '200', NULL, 'militaire_ordre_collectif (refus radio_manquante)', 'Aucun delta : la capacite est portee par la variante.');
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('50', 'produit_militaire', 'tente', 'tente', 'tente--militaire', '200', '{"usure": null, "consommee": false, "pa_repos_section": 10, "capacite_personnes": 13, "pa_repos_nocturne_pj": 10, "pa_bivouac_par_soldat": 1}', 'militaire_ordre_collectif (bivouac) ; militaire_reposer_section ; pa_repos_nocturne ; plateau-multijoueur.js:2591', NULL);
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('51', 'produit_militaire', 'jumelles', 'equipement-de-plein-air', 'equipement-de-plein-air--militaire', '200', '{"bonus_detection": 30}', 'militaire_observer -> militaire_chance_detection', NULL);
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('52', 'produit_militaire', 'trousse_secours', 'materiel-de-premiers-secours', 'materiel-de-premiers-secours--militaire', '200', '{"pa_max": 6, "pa_min": 2, "condition": "co-presence exigee si la cible n''est pas soi", "pa_formule": "2 + floor(min(100, secourisme)/25)", "plafond_pa": 30, "usage_unique": true}', 'militaire_trousse_utiliser', 'competences_militaires est vide pour tous les personnages : le gain reel est aujourd''hui toujours +2.');
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('53', 'produit_militaire', 'ration_combat', 'encas-a-emporter', 'encas-a-emporter--militaire', '200', '{"pa": 1, "plafond_pa": 30, "max_par_jour": 2, "usage_unique": true}', 'militaire_ration_consommer ; militaire_ordre_collectif (action ration)', 'Objet detruit dans la meme transaction que le gain. Refus non destructifs : pa_maximum, maximum_quotidien.');
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('54', 'ordre', 'hebergement|hotel-mineur', 'hebergement-standard', NULL, '100', '{"moral": 3, "pa_lendemain": 2}', 'pa_bonus_hotel (serveur) ; confortMap plateau-personnage.js:2943-2948', NULL);
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('55', 'ordre', 'hebergement|hotel-port', 'hebergement-standard', NULL, '100', '{"moral": 3, "pa_lendemain": 2}', 'pa_bonus_hotel ; confortMap plateau-personnage.js:2943-2948', NULL);
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('56', 'ordre', 'hebergement|hotel-republica', 'hebergement-standard', NULL, '100', '{"moral": 3, "pa_lendemain": 2}', 'pa_bonus_hotel = 2 ; confortMap plateau-personnage.js:2943-2948 applique {moral:3, paBonus:2}', 'ANOMALIE A TRAITER SEPAREMENT : plateau-personnage.js:437 ANNONCE {moral:5, paBonus:5}. Trois sources divergentes. Seule la valeur APPLIQUEE est retenue ici.');
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('57', 'ordre', 'hebergement|palais-presidentiel', 'hebergement-prestige', NULL, '100', '{"moral": 8, "pa_lendemain": 8}', 'pa_bonus_hotel = 8 ; confortMap plateau-personnage.js:2947', NULL);
INSERT INTO public.catalogue_correspondance_legacy (id, motif, valeur, generique_id, variante_id, priorite, effets_effectifs, source_audit, note) VALUES ('58', 'type', 'armoire_souvenirs', 'meuble-de-rangement', NULL, '100', NULL, 'creerExemplaireArmoireSouvenirs, plateau-justice-economie.js:5512-5528 ; seuls lecteurs : plateau-personnage.js:3338 et :3373 (affichage)', 'Aucun effet mecanique hormis encombrement 3. contenu et verrouillee ne sont ni lus ni ecrits. AUCUN bonus de sommeil. Actuellement IMPOSSIBLE A OBTENIR : la ligne batiments_etat[republic_ville_a_zone-production] n''existe pas.');

-- Recalage de la sequence : sans lui, le premier INSERT applicatif
-- entrerait en collision avec un identifiant seede.
select setval('catalogue_correspondance_legacy_id_seq', (select coalesce(max(id), 0) + 1 from public.catalogue_correspondance_legacy), false);
