-- SEED -- catalogue_generiques
-- ============================================================================
-- Table      : public.catalogue_generiques
-- Domaine    : economie
-- Categorie  : D (mixte)
-- Strategie  : seed_complet (classification du chantier 2C)
-- Lignes     : 84
--
-- Fichier GENERE par outils/baseline/seeds.py. Ne pas editer a la main.
-- Les litteraux sont ceux que PostgreSQL lui-meme a produits (quote_nullable) :
-- aucune regle d'echappement n'a ete reimplementee.
--
-- JUSTIFICATION DU SEED (chantier 2C)
-- 84 generiques d'objets.
--
-- ARBITRAGE DE GAME DESIGN
-- Voir catalogue_types.
-- ============================================================================

INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('accessoire-automobile', 'Accessoire automobile', 'pieces-accessoires', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('accessoire-d-arme', 'Accessoire d''arme', 'accessoires-armes', 'reglemente', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('accessoire-de-mode', 'Accessoire de mode', 'bijoux-accessoires', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('accessoire-militaire', 'Accessoire militaire', 'vetements-militaires', 'reglemente', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('accessoire-pour-animal', 'Accessoire pour animal', 'animaux', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('accessoire-vestimentaire', 'Accessoire vestimentaire', 'vetements-civils', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('activite-sportive', 'Activité sportive', 'sport', 'libre', 'true', 'false', 'false', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('affiche', 'Affiche', 'edition-papeterie', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('aliment-brut', 'Aliment brut', 'produits-frais', 'libre', 'false', 'true', 'false', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Raccorde aux 5 matieres alimentaires uniquement pour que la fiche sache repondre. Ce n''est PAS un produit commercial : les ressources restent des intrants (GD3).');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('aliment-prepare', 'Aliment préparé', 'produits-transformes', 'libre', 'false', 'false', 'true', 'true', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent. Regle deja arbitree : minimum 2 matieres premieres, a porter par le gabarit (L6).');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('animal-de-compagnie', 'Animal de compagnie', 'animaux', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('appareil-de-communication', 'Appareil de communication', 'communication', 'reglemente', 'false', 'false', 'true', 'false', 'true', NULL, NULL, NULL, NULL, NULL, NULL, 'La capacite militaire est portee par la VARIANTE, jamais par le generique.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('appareil-electronique', 'Appareil électronique', 'electronique', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('arme-blanche', 'Arme blanche', 'armes', 'reglemente', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('arme-de-poing', 'Arme de poing', 'armes', 'reglemente', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('arme-longue', 'Arme longue', 'armes', 'reglemente', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('article-de-supporter', 'Article de supporter', 'souvenirs-collections', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('article-du-quotidien', 'Article du quotidien', 'articles-quotidien', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Generique de repli : aucun effet, aucune capacite empruntee a un autre generique.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('bas', 'Bas', 'vetements-civils', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('bijou', 'Bijou', 'bijoux-accessoires', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('boisson', 'Boisson', 'boissons', 'libre', 'false', 'false', 'false', 'true', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Au comptoir elle ne produit aucun objet ; en epicerie une bouteille en produirait un. Le generique est le meme : la difference releve du mode de commercialisation (L5).');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('camera-de-surveillance', 'Caméra de surveillance', 'electronique', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('carte-postale', 'Carte postale', 'souvenirs-collections', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Individualisation necessaire a son contenu (etat vierge/ecrite, auteur, message, destinataire initial).');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('chaussures', 'Chaussures', 'vetements-civils', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('coiffure', 'Coiffure', 'coiffure-esthetique', 'libre', 'true', 'false', 'false', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('console-de-jeu', 'Console de jeu', 'jeux-electroniques', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('costume-complet', 'Costume complet', 'vetements-civils', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('decoration-murale', 'Décoration murale', 'decoration', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('deux-roues', 'Deux-roues', 'vehicules', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('encas', 'Encas', 'restauration', 'libre', 'false', 'false', 'false', 'true', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Consomme sur place aujourd''hui : c''est le mode de commercialisation actuel, pas une propriete du generique.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('encas-a-emporter', 'Encas à emporter', 'produits-transformes', 'libre', 'false', 'false', 'true', 'true', 'true', NULL, NULL, NULL, NULL, NULL, NULL, 'A la fois marchandise et consommable : c''est ce que la suppression de la « nature » exclusive permet de representer.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('equipement-de-plein-air', 'Équipement de plein air', 'plein-air', 'reglemente', 'false', 'false', 'true', 'false', 'true', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('equipement-de-protection-professionnelle', 'Équipement de protection professionnelle', 'securite-travail', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('equipement-domestique', 'Équipement domestique', 'equipement-domestique', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('equipement-professionnel', 'Équipement professionnel', 'outillage', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('equipement-sportif', 'Équipement sportif', 'sport', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('explosif', 'Explosif', 'accessoires-armes', 'reglemente', 'false', 'false', 'true', 'true', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('fourniture-de-bricolage', 'Fourniture de bricolage', 'materiaux-fournitures', 'libre', 'false', 'true', 'false', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('haut', 'Haut', 'vetements-civils', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Le +1 ENT d''un tee-shirt historique reste une propriete de CET objet, jamais du generique.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('hebergement-prestige', 'Hébergement prestige', 'hebergement', 'institutionnel', 'true', 'false', 'false', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('hebergement-standard', 'Hébergement standard', 'hebergement', 'libre', 'true', 'false', 'false', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Les trois hotels existants appliquent tous {moral:3, paBonus:2}.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('hebergement-superieur', 'Hébergement supérieur', 'hebergement', 'libre', 'true', 'false', 'false', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent : aucun hebergement existant ne se situe entre les hotels et le palais. Non rattache a l''Hotel Republia, dont l''ecart n''existe que dans un affichage incoherent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('imprime', 'Imprimé', 'edition-papeterie', 'reglemente', 'false', 'true', 'false', 'true', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('installation-de-piece', 'Installation de pièce/accessoire', 'entretien', 'libre', 'true', 'false', 'false', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('instrument-de-musique', 'Instrument de musique', 'musique-audiovisuel', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('jeu', 'Jeu', 'jeux-jouets', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('jeu-video', 'Jeu vidéo', 'jeux-electroniques', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('jouet', 'Jouet', 'jeux-jouets', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('livre', 'Livre', 'edition-papeterie', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent : le « Livre publie » historique est une fonction sans appelant.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('luminaire', 'Luminaire', 'equipement-domestique', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('materiau-de-construction', 'Matériau de construction', 'materiaux-fournitures', 'libre', 'false', 'true', 'false', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent : bois/minerai/metal restent des intrants (GD3).');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('materiel-de-premiers-secours', 'Matériel de premiers secours', 'soins-premiers-secours', 'reglemente', 'false', 'false', 'true', 'true', 'true', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('medicament', 'Médicament', 'medicaments', 'reglemente', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent : la ressource historique `medicaments` est un intrant, pas ce generique (GD3).');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('menu-gastronomique', 'Menu gastronomique', 'restauration', 'libre', 'false', 'false', 'false', 'true', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('meuble-de-prestige', 'Meuble de prestige', 'mobilier', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('meuble-de-rangement', 'Meuble de rangement', 'mobilier', 'libre', 'false', 'false', 'true', 'false', 'false', '3', NULL, NULL, NULL, NULL, NULL, 'Seul generique de mobilier ayant un antecedent. Aucun bonus de mobilier n''est invente.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('meuble-de-repos', 'Meuble de repos', 'mobilier', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent. Les bonus de sommeil restent portes par les logements/baux.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('objet-de-collection', 'Objet de collection', 'souvenirs-collections', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent. La famille « Collection » de Sport & loisirs est absorbee ici.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('objet-decoratif', 'Objet décoratif', 'decoration', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('oeuvre-d-art', 'Œuvre d''art', 'arts', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent : la table oeuvres est vide et ses RPC sont sans appelant.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('ordinateur-complet', 'Ordinateur complet', 'informatique', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('outil-a-main', 'Outil à main', 'outillage', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('outil-electrique', 'Outil électrique', 'outillage', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('peripherique-informatique', 'Périphérique informatique', 'informatique', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('piece-automobile', 'Pièce automobile', 'pieces-accessoires', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('piercing', 'Piercing', 'tatouage-piercing', 'libre', 'true', 'false', 'false', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('plat-elabore', 'Plat élaboré', 'restauration', 'libre', 'false', 'false', 'false', 'true', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('plat-simple', 'Plat simple', 'restauration', 'libre', 'false', 'false', 'false', 'true', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('produit-cosmetique', 'Produit cosmétique', 'coiffure-esthetique', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('produit-d-entretien-automobile', 'Produit d''entretien automobile', 'entretien', 'libre', 'false', 'false', 'true', 'true', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('produit-de-sante', 'Produit de santé', 'produits-sante', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent : la ressource historique `desinfectant` est un intrant.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('protection-corporelle', 'Protection corporelle', 'protection', 'reglemente', 'false', 'false', 'true', 'false', 'true', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('reparation', 'Réparation', 'entretien', 'libre', 'true', 'false', 'false', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('soin-esthetique', 'Soin esthétique', 'coiffure-esthetique', 'libre', 'true', 'false', 'false', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('soin-pharmaceutique', 'Soin pharmaceutique', 'soins-premiers-secours', 'libre', 'true', 'false', 'false', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent : les soins de dispensaire et de clinique sont des prestations institutionnelles de structures medicales, hors catalogue commercial.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('souvenir', 'Souvenir', 'souvenirs-collections', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('spectacle', 'Spectacle', 'spectacles', 'libre', 'true', 'false', 'false', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('support-culturel', 'Support culturel', 'musique-audiovisuel', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('tatouage', 'Tatouage', 'tatouage-piercing', 'libre', 'true', 'false', 'false', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('tente', 'Tente', 'plein-air', 'reglemente', 'false', 'false', 'true', 'false', 'true', NULL, NULL, NULL, NULL, NULL, NULL, 'Agit depuis l''inventaire du porteur : elle n''est installee nulle part aujourd''hui.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('tenue-militaire', 'Tenue militaire', 'vetements-militaires', 'reglemente', 'false', 'false', 'true', 'false', 'true', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('vegetal', 'Végétal', 'fleurs-vegetaux', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('vehicule-utilitaire', 'Véhicule utilitaire', 'vehicules', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
INSERT INTO public.catalogue_generiques (id, libelle, famille_id, regime, est_service, empilable, individualise, consommable, equipable, encombrement, effets, capacites, durabilite, conditions, contraintes, note) VALUES ('voiture', 'Voiture', 'vehicules', 'libre', 'false', 'false', 'true', 'false', 'false', NULL, NULL, NULL, NULL, NULL, NULL, 'Aucun antecedent.');
