-- SEED -- recettes_commerce
-- ============================================================================
-- Table      : public.recettes_commerce
-- Domaine    : economie
-- Categorie  : D (mixte)
-- Strategie  : seed_complet (classification du chantier 2C)
-- Lignes     : 37
--
-- Fichier GENERE par outils/baseline/seeds.py. Ne pas editer a la main.
-- Les litteraux sont ceux que PostgreSQL lui-meme a produits (quote_nullable) :
-- aucune regle d'echappement n'a ete reimplementee.
--
-- JUSTIFICATION DU SEED (chantier 2C)
-- 37 recettes. Contrairement a recettes_production, la table PORTE deja la
-- dimension : pays_autorises, villes_autorisees et buildings_autorises. 26
-- recettes sont restreintes a des villes, 24 a des pays, 11 sont sans
-- restriction.
--
-- ARBITRAGE DE GAME DESIGN
-- La structure sait exprimer la granularite ville ; le melange est dans le
-- contenu du seed (identifiants psm/montrouge), pas dans le schema.
--
-- AVERTISSEMENT : CETTE TABLE EST UN MIROIR DE data.js
-- Un generateur existe deja :
-- outils/generateurs/generer_miroirs_entreprises.py. Les lignes ci-dessous
-- sont copiees depuis la base, conformement a la strategie seed_complet du
-- chantier 2C -- mais copier un miroir fige sa derive. Celui des couts
-- d'ordre avait derive de 24 lignes mortes et 19 ordres gratuits non
-- declares. A terme, ce fichier doit etre ecrit par son generateur depuis
-- data.js, et la table doit rejoindre 95_a-regenerer.
-- ============================================================================

INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('biere_pression', 'alimentaire', 'Bière', '1', '15', '{"cereales": 1}', NULL, 'boisson', '["buvette", "bar", "cafe", "brasserie"]', NULL, NULL, NULL, '{"moral": 2}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('boeuf_bourguignon', 'alimentaire', 'Bœuf bourguignon — plat du jour', '1', '5', '{"viande": 1, "cereales": 1}', NULL, 'plat', '["cafe", "brasserie"]', NULL, NULL, NULL, '{"hp": 8, "moral": 2}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('boisson_sans_alcool', 'alimentaire', 'Boisson sans alcool', '1', '10', '{}', NULL, 'boisson', '["buvette", "bar", "cafe"]', NULL, NULL, NULL, '{"moral": 1}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('cafe_boisson', 'alimentaire', 'Café', '1', '15', '{"produits_exotiques": 1}', NULL, 'boisson', '["cafe", "bar", "brasserie"]', NULL, NULL, NULL, '{"moral": 2}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('carbonade_frites', 'alimentaire', 'Carbonade-frites', '1', '5', '{"viande": 1, "cereales": 1}', NULL, 'plat', '["brasserie"]', NULL, '["ville_b"]', NULL, '{"hp": 8, "moral": 3}', NULL, NULL, NULL, 'images/montrouge/montrouge-plat-carbonade.jpg', NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('carte_luthecia_culture', 'marche', 'Carte postale — Musées et Jardin botanique', '1', '16', '{"bois": 1}', NULL, 'objet', '["marche"]', '["republic"]', '["capitale"]', '["marche"]', NULL, NULL, NULL, 'ti-mail', 'images/luthecia-carte-postale-culture.png', NULL, 'carte_postale', NULL, 'carte-postale', NULL);
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('carte_luthecia_institutions', 'marche', 'Carte postale — Institutions de Luthécia', '1', '16', '{"bois": 1}', NULL, 'objet', '["marche"]', '["republic"]', '["capitale"]', '["marche"]', NULL, NULL, NULL, 'ti-mail', 'images/luthecia-carte-postale-institutions.png', NULL, 'carte_postale', NULL, 'carte-postale', 'Carte postale');
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('carte_luthecia_internationale', 'marche', 'Carte postale — Luthécia, ville internationale', '1', '16', '{"bois": 1}', NULL, 'objet', '["marche"]', '["republic"]', '["capitale"]', '["marche"]', NULL, NULL, NULL, 'ti-mail', 'images/luthecia-carte-postale-internationale.png', NULL, 'carte_postale', NULL, 'carte-postale', NULL);
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('carte_montrouge_musee_rail', 'marche', 'Carte postale — Musée du Rail', '1', '16', '{"bois": 1}', NULL, 'objet', '["marche"]', '["republic"]', '["ville_b"]', '["marche"]', NULL, NULL, NULL, 'ti-mail', 'images/montrouge/montrouge-carte-postale-musee-rail.png', NULL, 'carte_postale', NULL, 'carte-postale', NULL);
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('carte_montrouge_place_rail', 'marche', 'Carte postale — Place du Rail', '1', '16', '{"bois": 1}', NULL, 'objet', '["marche"]', '["republic"]', '["ville_b"]', '["marche"]', NULL, NULL, NULL, 'ti-mail', 'images/montrouge/montrouge-carte-postale-place-rail.png', NULL, 'carte_postale', NULL, 'carte-postale', NULL);
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('carte_montrouge_touristique', 'marche', 'Carte postale — Souvenir de Montrouge', '1', '16', '{"bois": 1}', NULL, 'objet', '["marche"]', '["republic"]', '["ville_b"]', '["marche"]', NULL, NULL, NULL, 'ti-mail', 'images/montrouge/montrouge-carte-postale-touristique.png', NULL, 'carte_postale', NULL, 'carte-postale', NULL);
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('carte_psm_culture_marine', 'marche', 'Carte postale — Traditions de la Marine', '1', '16', '{"bois": 1}', NULL, 'objet', '["marche"]', '["republic"]', '["ville_a"]', '["marche-psm"]', NULL, NULL, NULL, 'ti-mail', 'images/port-sainte-marie-carte-postale-culture-marine.png', NULL, 'carte_postale', NULL, 'carte-postale', NULL);
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('carte_psm_notre_dame_mer', 'marche', 'Carte postale — Notre-Dame de la Mer', '1', '16', '{"bois": 1}', NULL, 'objet', '["marche"]', '["republic"]', '["ville_a"]', '["marche-psm"]', NULL, NULL, NULL, 'ti-mail', 'images/port-sainte-marie-carte-postale-notre-dame-mer.png', NULL, 'carte_postale', NULL, 'carte-postale', NULL);
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('carte_psm_touristique', 'marche', 'Carte postale — Souvenir de Port-Sainte-Marie', '1', '16', '{"bois": 1}', NULL, 'objet', '["marche"]', '["republic"]', '["ville_a"]', '["marche-psm"]', NULL, NULL, NULL, 'ti-mail', 'images/port-sainte-marie-carte-postale-touristique.png', NULL, 'carte_postale', NULL, 'carte-postale', NULL);
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('casquette_montrouge', 'marche', 'Casquette de cheminot', '1', '6', '{"textile": 2}', NULL, 'objet', '["marche"]', '["republic"]', '["ville_b"]', '["marche"]', NULL, NULL, NULL, 'ti-shirt', 'images/montrouge/montrouge-marche-casquette.png', NULL, 'integration_locale', 'ville_b', 'accessoire-vestimentaire', 'Casquette');
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('casse_croute_cheminot', 'marche', 'Casse-croûte du Cheminot', '1', '8', '{"viande": 1, "cereales": 1}', NULL, 'objet', '["marche"]', '["republic"]', '["ville_b"]', '["marche"]', NULL, NULL, NULL, 'ti-meat', 'images/montrouge/montrouge-marche-casse-croute.png', NULL, 'aliment', NULL, NULL, NULL);
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('cornet_friture_psm', 'marche', 'Cornet de friture de poissons', '1', '8', '{"poisson": 1, "cereales": 1}', NULL, 'objet', '["marche"]', '["republic"]', '["ville_a"]', '["marche-psm"]', NULL, NULL, NULL, 'ti-fish', 'images/port-sainte-marie-marche-friture.png', NULL, 'aliment', NULL, NULL, NULL);
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('croque_monsieur_luthecia', 'marche', 'Croque-Monsieur du Marché', '1', '8', '{"viande": 1, "cereales": 1, "fruits_legumes": 1}', NULL, 'objet', '["marche"]', '["republic"]', '["capitale"]', '["marche"]', NULL, NULL, NULL, 'ti-meat', 'images/luthecia-marche-croque-monsieur.png', NULL, 'aliment', NULL, NULL, NULL);
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('echarpe_luthecia', 'marche', 'Écharpe en soie', '1', '6', '{"textile": 1, "produits_exotiques": 1}', NULL, 'objet', '["marche"]', '["republic"]', '["capitale"]', '["marche"]', NULL, NULL, NULL, 'ti-shirt', 'images/luthecia-marche-echarpe.png', NULL, 'integration_locale', 'capitale', 'accessoire-vestimentaire', 'Écharpe');
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('figurine_maxence_monfils', 'marche', 'Figurine de Maxence Monfils', '1', '6', '{"metal": 1}', NULL, 'objet', '["marche"]', '["republic"]', '["capitale"]', '["marche"]', NULL, NULL, NULL, 'ti-user', 'images/luthecia-souvenir-maxence-monfils.png', 'Figurine représentant Maxence Monfils enfant, avec une loupe et une sauterelle.', 'integration_locale', NULL, 'souvenir', 'Figurine');
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('garde_republien_plomb', 'marche', 'Garde républien en plomb', '1', '6', '{"metal": 1}', NULL, 'objet', '["marche"]', '["republic"]', '["capitale"]', '["marche"]', NULL, NULL, NULL, 'ti-chess-knight', 'images/luthecia-souvenir-garde-republien.png', 'Petite figurine de collection représentant un garde républien en uniforme.', 'integration_locale', NULL, 'souvenir', 'Figurine en plomb');
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('jus_de_fruits', 'alimentaire', 'Jus de fruits', '1', '15', '{"fruits_legumes": 1}', NULL, 'boisson', '["cafe"]', NULL, NULL, NULL, '{"moral": 2}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('menu_gastronomique_1', 'alimentaire', 'Menu 1 — Carpaccio de Saint-Jacques aux agrumes, Pavé de cerf sauce aux airelles, Omelette norvégienne', '1', '5', '{"viande": 1, "poisson": 1, "cereales": 1}', NULL, 'menu', '["brasserie"]', '["republic"]', '["capitale"]', '["hotel-republica"]', '{"hp": 10, "moral": 1, "paDiffere": 3}', NULL, NULL, NULL, 'images/luthecia-restaurant-menu-1.jpg', NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('menu_gastronomique_2', 'alimentaire', 'Menu 2 — Huîtres gratinées au four (origine Port-Sainte-Marie), Turbot sauce hollandaise, Soufflé au Grand Marnier', '1', '5', '{"poisson": 2, "cereales": 1}', NULL, 'menu', '["brasserie"]', '["republic"]', '["capitale"]', '["hotel-republica"]', '{"hp": 10, "moral": 1, "paDiffere": 3}', NULL, NULL, NULL, 'images/luthecia-restaurant-menu-2.jpg', NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('menu_gastronomique_3', 'alimentaire', 'Menu 3 — Foie gras et sa gelée de gewurztraminer, Chapon sauce aux morilles, Pavlova aux fruits rouges', '1', '5', '{"viande": 2, "fruits_legumes": 1}', NULL, 'menu', '["brasserie"]', '["republic"]', '["capitale"]', '["hotel-republica"]', '{"hp": 10, "moral": 1, "paDiffere": 3}', NULL, NULL, NULL, 'images/luthecia-restaurant-menu-3.jpg', NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('menu_psm_1', 'alimentaire', 'Menu 1 — Salade verte à l''ail et aux noix, Poulpe à la mariannaise, Riz au lait à la cannelle', '1', '6', '{"poisson": 1, "cereales": 1, "fruits_legumes": 1}', NULL, 'menu', '["brasserie"]', '["republic"]', '["ville_a"]', '["capitaine-sauvage"]', '{"hp": 10, "moral": 1, "paDiffere": 3}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('menu_psm_2', 'alimentaire', 'Menu 2 — Salade de chou rouge et pomme verte, Magret de canard colvert, Île flottante', '1', '6', '{"viande": 1, "cereales": 1, "fruits_legumes": 1}', NULL, 'menu', '["brasserie"]', '["republic"]', '["ville_a"]', '["capitaine-sauvage"]', '{"hp": 10, "moral": 1, "paDiffere": 3}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('menu_psm_3', 'alimentaire', 'Menu 3 — Huîtres de PSM, Tourte au crabe, Crème brûlée au Grand Marnier', '1', '6', '{"poisson": 2, "cereales": 1}', NULL, 'menu', '["brasserie"]', '["republic"]', '["ville_a"]', '["capitaine-sauvage"]', '{"hp": 10, "moral": 1, "paDiffere": 3}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('petit_dejeuner', 'alimentaire', 'Petit-déjeuner', '1', '10', '{"cereales": 1}', NULL, 'petit_dej', '["cafe"]', NULL, NULL, NULL, '{"hp": 3, "moral": 1}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('plat_de_poisson', 'alimentaire', 'Plat de poisson', '1', '5', '{"poisson": 1, "cereales": 1}', NULL, 'plat', '["brasserie"]', NULL, NULL, NULL, '{"hp": 8, "moral": 2}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('porte_cle_palais_luthecia', 'marche', 'Porte-clé du Palais présidentiel', '1', '6', '{"metal": 1}', NULL, 'objet', '["marche"]', '["republic"]', '["capitale"]', '["marche"]', NULL, NULL, NULL, 'ti-key', 'images/luthecia-souvenir-porte-cle-palais.png', 'Souvenir représentant le Palais présidentiel de Luthécia en miniature.', 'integration_locale', NULL, 'souvenir', 'Porte-clé');
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('sandwich', 'alimentaire', 'Sandwich', '1', '8', '{"viande": 1, "cereales": 1, "fruits_legumes": 1}', NULL, 'plat', '["marche"]', NULL, '["capitale"]', NULL, '{"hp": 5, "moral": 1, "paDiffere": 1}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('sandwich_cheminots', 'alimentaire', 'Sandwich jambon-beurre-cornichon', '1', '5', '{"viande": 1, "cereales": 1}', NULL, 'plat', '["cafe"]', NULL, NULL, '["cafe-tabac-cheminots-montrouge"]', '{"hp": 5, "moral": 1}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('saucisse_puree', 'alimentaire', 'Saucisse-purée', '1', '5', '{"viande": 1, "cereales": 1}', NULL, 'plat', '["brasserie"]', NULL, NULL, NULL, '{"hp": 8, "moral": 2}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('snack_buvette', 'alimentaire', 'Cacahuètes salées', '1', '15', '{"cereales": 1}', NULL, 'snack', '["buvette", "bar", "brasserie"]', NULL, NULL, NULL, '{"hp": 2, "moral": 1}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('tshirt_psm', 'marche', 'T-shirt de Port-Sainte-Marie', '1', '6', '{"textile": 2}', NULL, 'objet', '["marche"]', '["republic"]', '["ville_a"]', '["marche-psm"]', NULL, NULL, NULL, 'ti-shirt', 'images/port-sainte-marie-marche-tshirt.png', NULL, 'integration_locale', 'ville_a', 'haut', 'T-shirt');
INSERT INTO public.recettes_commerce (id, source, label, pa, portions, materiaux, prix_fixe, categorie, types_autorises, pays_autorises, villes_autorisees, buildings_autorises, effets, stack_key, sous_type, icone, image, description, famille_produit_marche, bonus_integration_ville, generique_id, label_forme) VALUES ('vin', 'alimentaire', 'Vin', '1', '15', '{"fruits_legumes": 1}', NULL, 'boisson', '["cafe", "brasserie", "bar"]', NULL, NULL, NULL, '{"moral": 2}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
